METABOLIC = {
    'LEVEL': {
        'LEVELSELECTION': {
            '1': 'Yeni (Acemi)',
            '2': 'Orta Seviye',
            '3': 'Deneyimli',
            '4': 'Sporcu',
        },
        'DIFFICULTY': {
            '1': '%30-50',
            '2': '%51-69',
            '3': '%70-85',
            '4': '%86-100',
        },
        'LOADRATE': {
            '1': '1 - 1/2',
            '2': '1 - 1/3',
            '3': '1:1',
            '4': '1:2',
            '5': '1:3',
            '6': '1:4',
        },
        'LOADTIME': {
            '1': '15:15',
            '2': '15:30',
            '3': '15:45',
            '4': '20:10',
            '5': '20:20',
            '6': '20:30',
            '7': '20:40',
            '8': '20:60',
            '9': '20:80',
            '10': '30:10',
            '11': '30:15',
            '12': '30:30',
            '13': '30:45',
            '14': '30:60',
            '15': '30:90',
            '16': '40:20',
            '17': '40:40',
            '18': '40:60',
            '19': '40:80',
            '20': '45:30',
            '21': '45:45',
            '22': '45:90',
            '23': '45:135',
            '24': '60:30',
            '25': '60:60',
            '26': '60:90',
            '27': '60:120',
        },
    },
    'START': {
        'NEW': {
            'nw_Squat1': 'Squat',
            'nw_Lateral1': 'Lateral Jump',
            'nw_In': 'In out ledder',
            'nw_Forward1': 'Forward Bunny Hop',
            'nw_Mountain1': 'Mountain Climber',
            'nw_High1': 'High Knee',
            'nw_Jumping1': 'Jumping Jack',
            'nw_Forward2': 'Forward Running',
            'nw_Lateral2': 'Lateral Shuffle',
            'nw_Step1': 'Step up',
            'nw_Heel': 'Heel Touch to Butt Kick',
            'nw_Trippling': 'Trippling High Knee',
            'nw_Burpee': 'Burpee',
            'nw_Plank': 'Plank w/Toe Touch',
            'nw_Inchworm': 'Inchworm Plank',
            'nw_Double': 'Double Climbers',
            'nw_Crossbody': 'Crossbody Knees',
            'nw_Step2': 'Step Jack',
            'nw_Press': 'Press Jack',
            'nw_Toe': 'Toe Touches into Squat',
            'nw_Overhead1': 'Overhead Hands Hold In-Out Lea',
            'nw_Lateral3': 'Lateral Hops',
            'nw_Scissor': 'Scissor Kick',
            'nw_Leg': 'Leg Raise',
            'nw_Forward3': 'Forward Running',
            'nw_Back1': 'Back Running',
            'nw_Squat3': 'Squat Press',
            'nw_Squat4': 'Squat Press',
            'nw_Jumping2': 'Jumping Jack',
            'nw_Deadlift': 'Deadlift w/RB Row',
            'nw_High2': 'High Knee',
            'nw_TRX': 'TRX Row',
            'nw_Front1': 'Front Plank',
            'nw_Lateral4': 'Lateral Squat Jump',
            'nw_Split': 'Split Lunge',
            'nw_Pushup1': 'Push-up',
            'nw_Mountain2': 'Mountain Climber',
            'nw_Glute': 'Glute Bridge',
            'nw_Woodchopper': 'Woodchopper',
            'nw_Jump1': 'Jump Rope',
            'nw_Jump2': 'Jump Ghost Rope',
            'nw_Bear1': 'Bear Crawl',
            'nw_Bear2': 'Bear Crawl Lateral',
            'nw_Lateral5': 'Lateral Hops',
            'nw_Squat5': 'Squat Front Kick',
            'nw_Back2': 'Back Lunge',
            'nw_Pushup2': 'Push-Up Leg Lift',
            'nw_Seated1': 'Seated Pull Down RB',
            'nw_Seated2': 'Seated Row RB',
            'nw_Shoulder': 'Shoulder Press RB',
            'nw_Lateral': 'Lateral Raise RB',
            'nw_Chest': 'Chest Press RB',
            'nw_Superman': 'Superman',
            'nw_Thoracic': 'Thoracic Extension',
            'nw_Front2': 'Front Raise RB',
            'nw_Biceps': 'Biceps Curl RB',
            'nw_Overhead2': 'Overhead Triceps Extension RB',
            'nw_Lunge': 'Lunge w/Push Down RB',
            'nw_Reverse': 'Reverse Fly RB',
            'nw_Overhead': 'Overhead Press RB',
            'nw_Facepull': 'Facepull RB',
            'nw_Sumo': 'Sumo Squat Pulse 3x to Calf Raise ',
            'nw_Kneeling1': 'Kneeling Hip Extension w/RB Row',
            'nw_Kneeling2': 'Kneeling Hip Extension w/Chest Press RB',
            'nw_Side': 'Side Plank Chest Press',
        },
        'MIDDLE': {
            'mdl_Squat1': 'Squat Triple Extension',
            'mdl_Lateral1': 'Lateral Bounding',
            'mdl_Spider': 'Spider Climber',
            'mdl_High1': 'High Knee + Truck Jump',
            'mdl_Jumping1': 'Jumping Jack + Squat',
            'mdl_Lateral2': 'Lateral Shuffle + Reverse Lunge',
            'mdl_Step1': 'Step up + Jump',
            'mdl_Skater1': 'Skater',
            'mdl_Burpee1': 'Burpee Jump',
            'mdl_Squat2': 'Squat Jack',
            'mdl_Forward': 'Forward Hops',
            'mdl_Lateral3': 'Lateral Hops',
            'mdl_Pushup1': 'Push Up Walk Back',
            'mdl_Roll': 'Roll To Stand',
            'mdl_Lunge1': 'Lunge Skip',
            'mdl_Wacky': 'Wacky Jack',
            'mdl_Lunge2': 'Lunge Jack',
            'mdl_Froggers': 'Froggers',
            'mdl_Leg1': 'Leg Raise',
            'mdl_Scissor': 'Scissor Kick',
            'mdl_Skipping1': 'Skipping',
            'mdl_Skipping2': 'Skipping Ghost Rope Hops',
            'mdl_Step2': 'Step Jump',
            'mdl_Lateral4': 'Lateral Hops w/Step board',
            'mdl_Squat3': 'Squat Shoulder Press w/Resband',
            'mdl_Kneeling1': 'Kneeling Pull Down w/RB',
            'mdl_Lateral5': 'Lateral Shuffle',
            'mdl_Goblet': 'Goblet Squat',
            'mdl_High2': 'High Knee Lateral',
            'mdl_Kneeling2': 'Kneeling Landmine Press',
            'mdl_Pallof': 'Pallof Press',
            'mdl_Jumping2': 'Jumping Rope',
            'mdl_Romanian': 'Romanian Dumbbell Deadlift',
            'mdl_Seated': 'Seated Shoulder Press',
            'mdl_Jump': 'Jump Squat',
            'mdl_Bird': 'Bird Dog',
            'mdl_Barbell': 'Barbell Torque',
            'mdl_Bear': 'Bear Crawl Shoulder Tap',
            'mdl_Hollow': 'Hollow Hold',
            'mdl_Burpee2': 'Burpee',
            'mdl_Deadlift1': 'Deadlift Dumbell',
            'mdl_Bench': 'Bench Dips',
            'mdl_Farmers': 'Farmers Walk',
            'mdl_Trx': 'Trx Row',
            'mdl_Side1': 'Side Plank',
            'mdl_Side2': 'Side Plank Hip Lift',
            'mdl_Side3': 'Side Plank Row RB',
            'mdl_Side4': 'Side Plank Reverse Fly RB',
            'mdl_Side5': 'Side Plank Rotation',
            'mdl_Skater2': 'Skater Jump',
            'mdl_Leg2': 'Leg Raise',
            'mdl_Step3': 'Step Up',
            'mdl_Sumo': 'Sumo Deadlift',
            'mdl_Interved': 'Interved Row',
            'mdl_Pushup2': 'Push Up Shoulder Tap',
            'mdl_Landmine': 'Landmine Press Kneeling',
            'mdl_Kneeling3': 'Kneeling Landmine Rotation',
            'mdl_Push1': 'Push Bird Dog',
            'mdl_Dead': 'Dead Bug Chest Press',
            'mdl_Sandbag': 'Sandbag Rotational Lunge',
            'mdl_Right': 'Right Leg Forward Lunge to Back Lunge Hops 2x',
            'mdl_Left': 'Left Leg Forward Lunge to Back Lunge Hops 2x',
            'mdl_Alt': 'Alt. Cursty Lunge to Jump Squat',
            'mdl_Side6': 'Side Steps ',
            'mdl_Lunge3': 'Lunge Shoulder Press',
            'mdl_Split1': 'Split Lunge Overhead Lift',
            'mdl_Split2': 'Split Lunge Forward Kettlebell Press',
            'mdl_Scapular': 'Scapular Push Up',
            'mdl_Push2': 'Push & Plank',
            'mdl_Bentover': 'Bentover Banded Aparat',
            'mdl_Deadlift2': 'Deadlift + Squat press plate',
            'mdl_Farmers1': 'Farmers Carry KB',
            'mdl_Farmers2': 'Farmers Carry DB',
            'mdl_Farmers3': 'Farmers Carry Barbell',
        },
        'HIGH': {
            'hgh_Squat1': 'Squat Jump',
            'hgh_Single1': 'Single Leg Jump',
            'hgh_Single2': 'Single Leg Lateral Jump',
            'hgh_High1': 'High Knee + Jump Lunge',
            'hgh_Jumping': 'Jumping Jack + Tuck Jump',
            'hgh_Lateral1': 'Lateral Shuffle + Squat Jump',
            'hgh_Power1': 'Power Jack',
            'hgh_Step1': 'Step Jump',
            'hgh_Skater1': 'Skater + Vertical Jumps',
            'hgh_Burpee1': 'Burpee Jump',
            'hgh_Burpee2': 'Burpee Lateral Jump',
            'hgh_Burpee3': 'Burpee + Lunge Jump',
            'hgh_Plyo': 'Plyo Push Up',
            'hgh_Plank1': 'Plank Jack',
            'hgh_Donkey': 'Donkey Kick Sit Thru',
            'hgh_Skater2': 'Skater Hops',
            'hgh_Plank2': 'Plank Skiier Hops',
            'hgh_Back1': 'Back Hops',
            'hgh_Hop': 'Hop Overs',
            'hgh_Single3': 'Single Leg Deadlift Hops',
            'hgh_Single4': 'Single Leg Burpee',
            'hgh_Pushup1': 'Push Up Walk Back + Jump',
            'hgh_Burpee4': 'Burpee Sit Thru',
            'hgh_Power2': 'Power Squat Knee Tuck',
            'hgh_Jump1': 'Jump Knee Tuck',
            'hgh_Banana': 'Banana Split',
            'hgh_Rainbow': 'Rainbow Split Squat Jumps',
            'hgh_Knee1': 'Knee Tuck Push Up',
            'hgh_Crawl': 'Crawl Pull Sandbag',
            'hgh_Crossover': 'Crossover Jack',
            'hgh_Jack': 'Jack Burpees',
            'hgh_Atlas1': 'Atlas Swing',
            'hgh_Bent1': 'Bent Over Swing',
            'hgh_Woodchopper': 'Woodchopper Kettlebell',
            'hgh_High2': 'High Rotation KB',
            'hgh_Rotational1': 'Rotational Squat Jump',
            'hgh_Rotational2': 'Rotational Squat Jump w/Board',
            'hgh_Burpee5': 'Burpee Squat',
            'hgh_Squat2': 'Squat Jump + Mountain Climber',
            'hgh_Spider': 'Spider Climber',
            'hgh_Mountain': '2x Mountain Climber 2x Spider Climber',
            'hgh_Lateral2': 'Lateral Shuffle 2x Burpee 2x',
            'hgh_Lateral3': 'Lateral Bear Crawl & Squat Jump 2x',
            'hgh_Pogo1': 'Pogo Jump',
            'hgh_One1': 'One Arm KB Swing',
            'hgh_Push1': 'Push Position Open & Close Legs',
            'hgh_Push2': 'Push Position Open & Close Hands',
            'hgh_Single5': 'Single Leg Hops Forward & Back',
            'hgh_Single6': 'Single Leg Hops Lateral',
            'hgh_Thruster': 'Thruster Barbel',
            'hgh_Forward1': 'Forward Lunge w/RB',
            'hgh_Dumbbell': 'Dumbbell Bench Press',
            'hgh_Front': 'Front Plank + Leg Lift',
            'hgh_High3': 'High Knee',
            'hgh_Bent2': 'Bent-over Dumbbell Row',
            'hgh_Single7': 'Single Leg Deadlift w/DB',
            'hgh_Pogo2': 'Pogo Jump',
            'hgh_Hip1': 'Hip Thrust',
            'hgh_Landmine1': 'Landmine Press',
            'hgh_Plank3': 'Plank Shoulder Tap',
            'hgh_Vertical1': 'Vertical Pallof Press',
            'hgh_Side1': 'Side Plank Clam',
            'hgh_Kettlebell1': 'Kettlebell Swing',
            'hgh_Plank4': 'Plank Get Up',
            'hgh_Single8': 'Single Arm KB Push Press',
            'hgh_Barbell1': 'Barbell Thruster',
            'hgh_Interved': 'Interved Row Single Leg',
            'hgh_Barbell2': 'Barbell Jumps Squat',
            'hgh_Dumbell1': 'Dumbell Push Press',
            'hgh_Plank5': 'Plank Shoulder Tap',
            'hgh_Forearm': 'Forearm Press Up',
            'hgh_Bird1': 'Bird Dog Row',
                'hgh_Hip2': 'Hip Thrust Single Arm Dumbell Press',
            'hgh_Landmine2': 'Landmine Press (Triple Extension)',
            'hgh_Single9': 'Single Arm Landmine Press',
            'hgh_Single10': 'Single Leg Landmine Press',
            'hgh_Single11': 'Single Leg & Single Arm Contralateral Landmine Press',
            'hgh_Landmine3': 'Landmine Rotation Clen Press',
            'hgh_Landmine4': 'Landmine Rotation',
            'hgh_Landmine5': 'Landmine Jerk',
            'hgh_Cophengan': 'Cophengan Curl',
            'hgh_Single12': 'Single Leg RDL Horizontal Overhead Press',
            'hgh_Dumbell2': 'Dumbell Jerk',
            'hgh_Barbell3': 'Barbell Jerk',
            'hgh_Dumbell3': 'Dumbell Clean',
            'hgh_Single13': 'Single KB Clean',
            'hgh_Barrier': 'Barrier Jump Lateral',
            'hgh_Box1': 'Box Jump',
            'hgh_Box2': 'Box Jump Lateral',
            'hgh_Broad1': 'Broad Jump',
            'hgh_Burpee6': 'Burpee + Pull ups',
            'hgh_High4': 'High Pull Barbell',
            'hgh_High5': 'High Pull Dumbell',
            'hgh_Single14': 'Single Leg Countermovement Jump',
            'hgh_Single15': 'Single Leg Squat',
            'hgh_Pullup': 'Pull Up',
            'hgh_Goodmorning': 'Goodmorning Barbell',
            'hgh_Chin': 'Chin Up',
            'hgh_KB1': 'KB Swing Single Arm',
            'hgh_Turkish': 'Turkish Get Up',
            'hgh_Single16': 'Single Arm Dumbell Deadlift',
            'hgh_Broad2': 'Broad Jump to Reverse Monster Walk',
            'hgh_Knee2': 'Knee Seated Jump to Knee Tuck',
            'hgh_Rotational3': 'Rotational Squat Jump',
            'hgh_Kettlebell2': 'Kettlebell Rotational Press',
            'hgh_Bentover': 'Bentover Kettlebell Swing',
            'hgh_Rotational4': 'Rotational Kettlebell Swing',
            'hgh_Single17': 'Single Leg Kettlebell Swing & Change Arm',
            'hgh_Windmill': 'Windmill',
            'hgh_Atlas2': 'Atlas Swing',
            'hgh_One2': 'One Arm Atlas Swing',
            'hgh_Side2': 'Side Swing',
            'hgh_One3': 'One Arm Side Swing',
            'hgh_Bent3': 'Bent Over Swing',
            'hgh_High6': 'High Rotation KB',
            'hgh_Horizontal1': 'Horizontal Swing ',
            'hgh_One4': 'One Arm Horizontal Swing',
            'hgh_Barbell4': 'Barbell Deadlift w/RB',
            'hgh_Deadbug1': 'Deadbug Chest Press',
            'hgh_Bird2': 'Bird Dog Single Arm Row on the bench',
            'hgh_Step2': 'Step Lunge Sholuder Press',
            'hgh_Step3': 'Step Lunge One Arm Shoulder Press',
            'hgh_Step4': 'Step Lunge One Arm Bottom Shoulder Press',
            'hgh_Dumbell4': 'Dumbell Split Snatch',
            'hgh_Single18': 'Single Arm Pallof Press',
            'hgh_Single19': 'Single Leg pallof press',
            'hgh_Single20': 'Single Leg & Single Arm Pallof Press',
            'hgh_Overhead': 'Overhead Plate Carry',
            'hgh_Jump2': 'Jump Lunge Landmine Press ',
            'hgh_Jump3': 'Jump Lunge Landmine Press Single Arm',
            'hgh_Band': 'Band Tall Kneel Front Lift',
            'hgh_Deadbug2': 'Deadbug To Roll and Side Plank',
            'hgh_Deadbug3': 'Deadbug To Roll and Side Plankc',
            'hgh_Step5': 'Step Jump',
            'hgh_Vertical2': 'Vertical Jump + Burpees',
            'hgh_Pushup2': 'Push Up + Kettlebell Row on KB',
            'hgh_Push3': 'Push Position Shoulder Flexion (Horizontal)',
            'hgh_Atlas3': 'Atlas Swing',
            'hgh_One5': 'One Arm Atlas Swing',
            'hgh_Side3': 'Side Swing KB',
            'hgh_One6': 'One Arm Side Swing KB',
            'hgh_Horizontal2': 'Horizontal Arms Swing',
            'hgh_Horizontal3': 'Horizontal One Arm Swing',
            'hgh_Bent4': 'Bent Over Swing',
            'hgh_One7': 'One Arm Bent Over Swing',
            'hgh_Lunge': 'Lunge Kettlebell Press + Windmill',
            'hgh_Landmine6': 'Landmine Snatch',
            'hgh_Kneeling': 'Kneeling Landmine Snatch',
            'hgh_KB2': 'KB Overhead Press (Sit Up)',
            'hgh_Ball': 'Ball Thoracic Extension + Row w/RB',
            'hgh_Side4': 'Side Plank Hip up w/RB Row',
            'hgh_Side5': 'Side Plank Hip up w/RB Press',
            'hgh_Deadbug4': 'Deadbug to Roll Side plank',
            'hgh_Double1': 'Double Kettlebell Clean',
            'hgh_Double2': 'Double Kettlebell Swing',
            'hgh_Kettlebell3': 'Kettlebell Deadlift to Swing',
            'hgh_Forward2': 'Forward Lunge Single Arm Overhead Press',
            'hgh_Back2': 'Back lunge Single Arm Bottom Overhead Shoulder Press',
            'hgh_G2OH': 'G2OH March Complex',
            'hgh_Hang': 'Hang Snatch + Hip Flexion w/KB',
        },
    },

}
