from datetime import datetime

from django.db import models

# Create your models here.
from django.urls import reverse

from registration.models import Trainer, Personal





class Metabolic2(models.Model):
    # İleri Seviye
    hgh_Squat1 = models.CharField(verbose_name='Squat Jump', max_length=40, blank=True, null=True)
    hgh_Single1 = models.CharField(verbose_name='Single Leg Jump', max_length=40, blank=True, null=True)
    hgh_Single2 = models.CharField(verbose_name='Single Leg Lateral Jump', max_length=40, blank=True, null=True)
    hgh_High1 = models.CharField(verbose_name='High Knee + Jump Lunge', max_length=40, blank=True, null=True)
    hgh_Jumping = models.CharField(verbose_name='Jumping Jack + Tuck Jump', max_length=40, blank=True, null=True)
    hgh_Lateral1 = models.CharField(verbose_name='Lateral Shuffle + Squat Jump', max_length=40, blank=True, null=True)
    hgh_Power1 = models.CharField(verbose_name='Power Jack', max_length=40, blank=True, null=True)
    hgh_Step1 = models.CharField(verbose_name='Step Jump', max_length=40, blank=True, null=True)
    hgh_Skater1 = models.CharField(verbose_name='Skater + Vertical Jumps', max_length=40, blank=True, null=True)
    hgh_Burpee1 = models.CharField(verbose_name='Burpee Jump', max_length=40, blank=True, null=True)
    hgh_Burpee2 = models.CharField(verbose_name='Burpee Lateral Jump', max_length=40, blank=True, null=True)
    hgh_Burpee3 = models.CharField(verbose_name='Burpee + Lunge Jump', max_length=40, blank=True, null=True)
    hgh_Plyo = models.CharField(verbose_name='Plyo Push Up', max_length=40, blank=True, null=True)
    hgh_Plank1 = models.CharField(verbose_name='Plank Jack', max_length=40, blank=True, null=True)
    hgh_Donkey = models.CharField(verbose_name='Donkey Kick Sit Thru', max_length=40, blank=True, null=True)
    hgh_Skater2 = models.CharField(verbose_name='Skater Hops', max_length=40, blank=True, null=True)
    hgh_Plank2 = models.CharField(verbose_name='Plank Skiier Hops', max_length=40, blank=True, null=True)
    hgh_Back1 = models.CharField(verbose_name='Back Hops', max_length=40, blank=True, null=True)
    hgh_Hop = models.CharField(verbose_name='Hop Overs', max_length=40, blank=True, null=True)
    hgh_Single3 = models.CharField(verbose_name='Single Leg Deadlift Hops', max_length=40, blank=True, null=True)
    hgh_Single4 = models.CharField(verbose_name='Single Leg Burpee', max_length=40, blank=True, null=True)
    hgh_Pushup1 = models.CharField(verbose_name='Push Up Walk Back + Jump', max_length=40, blank=True, null=True)
    hgh_Burpee4 = models.CharField(verbose_name='Burpee Sit Thru', max_length=40, blank=True, null=True)
    hgh_Power2 = models.CharField(verbose_name='Power Squat Knee Tuck', max_length=40, blank=True, null=True)
    hgh_Jump1 = models.CharField(verbose_name='Jump Knee Tuck', max_length=40, blank=True, null=True)
    hgh_Banana = models.CharField(verbose_name='Banana Split', max_length=40, blank=True, null=True)
    hgh_Rainbow = models.CharField(verbose_name='Rainbow Split Squat Jumps', max_length=40, blank=True, null=True)
    hgh_Knee1 = models.CharField(verbose_name='Knee Tuck Push Up', max_length=40, blank=True, null=True)
    hgh_Crawl = models.CharField(verbose_name='Crawl Pull Sandbag', max_length=40, blank=True, null=True)
    hgh_Crossover = models.CharField(verbose_name='Crossover Jack', max_length=40, blank=True, null=True)
    hgh_Jack = models.CharField(verbose_name='Jack Burpees', max_length=40, blank=True, null=True)
    hgh_Atlas1 = models.CharField(verbose_name='Atlas Swing', max_length=40, blank=True, null=True)
    hgh_Bent1 = models.CharField(verbose_name='Bent Over Swing', max_length=40, blank=True, null=True)
    hgh_Woodchopper = models.CharField(verbose_name='Woodchopper Kettlebell', max_length=40, blank=True, null=True)
    hgh_High2 = models.CharField(verbose_name='High Rotation KB', max_length=40, blank=True, null=True)
    hgh_Rotational1 = models.CharField(verbose_name='Rotational Squat Jump', max_length=40, blank=True, null=True)
    hgh_Rotational2 = models.CharField(verbose_name='Rotational Squat Jump w/Board', max_length=40, blank=True,
                                       null=True)
    hgh_Burpee5 = models.CharField(verbose_name='Burpee Squat', max_length=40, blank=True, null=True)
    hgh_Squat2 = models.CharField(verbose_name='Squat Jump + Mountain Climber', max_length=40, blank=True, null=True)
    hgh_Spider = models.CharField(verbose_name='Spider Climber', max_length=40, blank=True, null=True)
    hgh_Mountain = models.CharField(verbose_name='2x Mountain Climber 2x Spider Climber', max_length=40, blank=True,
                                    null=True)
    hgh_Lateral2 = models.CharField(verbose_name='Lateral Shuffle 2x Burpee 2x', max_length=40, blank=True, null=True)
    hgh_Lateral3 = models.CharField(verbose_name='Lateral Bear Crawl & Squat Jump 2x', max_length=40, blank=True,
                                    null=True)
    hgh_Pogo1 = models.CharField(verbose_name='Pogo Jump', max_length=40, blank=True, null=True)
    hgh_One1 = models.CharField(verbose_name='One Arm KB Swing', max_length=40, blank=True, null=True)
    hgh_Push1 = models.CharField(verbose_name='Push Position Open & Close Legs', max_length=40, blank=True, null=True)
    hgh_Push2 = models.CharField(verbose_name='Push Position Open & Close Hands', max_length=40, blank=True, null=True)
    hgh_Single5 = models.CharField(verbose_name='Single Leg Hops Forward & Back', max_length=40, blank=True, null=True)
    hgh_Single6 = models.CharField(verbose_name='Single Leg Hops Lateral', max_length=40, blank=True, null=True)
    hgh_Thruster = models.CharField(verbose_name='Thruster Barbel', max_length=40, blank=True, null=True)
    hgh_Forward1 = models.CharField(verbose_name='Forward Lunge w/RB', max_length=40, blank=True, null=True)
    hgh_Dumbbell = models.CharField(verbose_name='Dumbbell Bench Press', max_length=40, blank=True, null=True)
    hgh_Front = models.CharField(verbose_name='Front Plank + Leg Lift', max_length=40, blank=True, null=True)
    hgh_High3 = models.CharField(verbose_name='High Knee', max_length=40, blank=True, null=True)
    hgh_Bent2 = models.CharField(verbose_name='Bent-over Dumbbell Row', max_length=40, blank=True, null=True)
    hgh_Single7 = models.CharField(verbose_name='Single Leg Deadlift w/DB', max_length=40, blank=True, null=True)
    hgh_Pogo2 = models.CharField(verbose_name='Pogo Jump', max_length=40, blank=True, null=True)
    hgh_Hip1 = models.CharField(verbose_name='Hip Thrust', max_length=40, blank=True, null=True)
    hgh_Landmine1 = models.CharField(verbose_name='Landmine Press', max_length=40, blank=True, null=True)
    hgh_Plank3 = models.CharField(verbose_name='Plank Shoulder Tap', max_length=40, blank=True, null=True)
    hgh_Vertical1 = models.CharField(verbose_name='Vertical Pallof Press', max_length=40, blank=True, null=True)
    hgh_Side1 = models.CharField(verbose_name='Side Plank Clam', max_length=40, blank=True, null=True)
    hgh_Kettlebell1 = models.CharField(verbose_name='Kettlebell Swing', max_length=40, blank=True, null=True)
    hgh_Plank4 = models.CharField(verbose_name='Plank Get Up', max_length=40, blank=True, null=True)
    hgh_Single8 = models.CharField(verbose_name='Single Arm KB Push Press', max_length=40, blank=True, null=True)
    hgh_Barbell1 = models.CharField(verbose_name='Barbell Thruster', max_length=40, blank=True, null=True)
    hgh_Interved = models.CharField(verbose_name='Interved Row Single Leg', max_length=40, blank=True, null=True)
    hgh_Barbell2 = models.CharField(verbose_name='Barbell Jumps Squat', max_length=40, blank=True, null=True)
    hgh_Dumbell1 = models.CharField(verbose_name='Dumbell Push Press', max_length=40, blank=True, null=True)
    hgh_Plank5 = models.CharField(verbose_name='Plank Shoulder Tap', max_length=40, blank=True, null=True)
    hgh_Forearm = models.CharField(verbose_name='Forearm Press Up', max_length=40, blank=True, null=True)
    hgh_Bird1 = models.CharField(verbose_name='Bird Dog Row', max_length=40, blank=True, null=True)
    hgh_Hip2 = models.CharField(verbose_name='Hip Thrust Single Arm Dumbell Press', max_length=40, blank=True,
                                null=True)
    hgh_Landmine2 = models.CharField(verbose_name='Landmine Press (Triple Extension)', max_length=40, blank=True,
                                     null=True)
    hgh_Single9 = models.CharField(verbose_name='Single Arm Landmine Press', max_length=40, blank=True, null=True)
    hgh_Single10 = models.CharField(verbose_name='Single Leg Landmine Press', max_length=40, blank=True, null=True)
    hgh_Single11 = models.CharField(verbose_name='Single Leg & Single Arm Contralateral Landmine Press', max_length=60,
                                    blank=True, null=True)
    hgh_Landmine3 = models.CharField(verbose_name='Landmine Rotation Clen Press', max_length=40, blank=True, null=True)
    hgh_Landmine4 = models.CharField(verbose_name='Landmine Rotation', max_length=40, blank=True, null=True)
    hgh_Landmine5 = models.CharField(verbose_name='Landmine Jerk', max_length=40, blank=True, null=True)
    hgh_Cophengan = models.CharField(verbose_name='Cophengan Curl', max_length=40, blank=True, null=True)
    hgh_Single12 = models.CharField(verbose_name='Single Leg RDL Horizontal Overhead', max_length=40, blank=True,
                                    null=True)
    hgh_Dumbell2 = models.CharField(verbose_name='Dumbell Jerk', max_length=40, blank=True, null=True)
    hgh_Barbell3 = models.CharField(verbose_name='Barbell Jerk', max_length=40, blank=True, null=True)
    hgh_Dumbell3 = models.CharField(verbose_name='Dumbell Clean', max_length=40, blank=True, null=True)
    hgh_Single13 = models.CharField(verbose_name='Single KB Clean', max_length=40, blank=True, null=True)
    hgh_Barrier = models.CharField(verbose_name='Barrier Jump Lateral', max_length=40, blank=True, null=True)
    hgh_Box1 = models.CharField(verbose_name='Box Jump', max_length=40, blank=True, null=True)
    hgh_Box2 = models.CharField(verbose_name='Box Jump Lateral', max_length=40, blank=True, null=True)
    hgh_Broad1 = models.CharField(verbose_name='Broad Jump', max_length=40, blank=True, null=True)
    hgh_Burpee6 = models.CharField(verbose_name='Burpee + Pull ups', max_length=40, blank=True, null=True)
    hgh_High4 = models.CharField(verbose_name='High Pull Barbell', max_length=40, blank=True, null=True)
    hgh_High5 = models.CharField(verbose_name='High Pull Dumbell', max_length=40, blank=True, null=True)
    hgh_Single14 = models.CharField(verbose_name='Single Leg Countermovement Jump', max_length=40, blank=True,
                                    null=True)
    hgh_Single15 = models.CharField(verbose_name='Single Leg Squat', max_length=40, blank=True, null=True)
    hgh_Pullup = models.CharField(verbose_name='Pull Up', max_length=40, blank=True, null=True)
    hgh_Goodmorning = models.CharField(verbose_name='Goodmorning Barbell', max_length=40, blank=True, null=True)
    hgh_Chin = models.CharField(verbose_name='Chin Up', max_length=40, blank=True, null=True)
    hgh_KB1 = models.CharField(verbose_name='KB Swing Single Arm', max_length=40, blank=True, null=True)
    hgh_Turkish = models.CharField(verbose_name='Turkish Get Up', max_length=40, blank=True, null=True)
    hgh_Single16 = models.CharField(verbose_name='Single Arm Dumbell Deadlift', max_length=40, blank=True, null=True)
    hgh_Broad2 = models.CharField(verbose_name='Broad Jump to Reverse Monster Walk', max_length=40, blank=True,
                                  null=True)
    hgh_Knee2 = models.CharField(verbose_name='Knee Seated Jump to Knee Tuck', max_length=40, blank=True, null=True)
    hgh_Rotational3 = models.CharField(verbose_name='Rotational Squat Jump', max_length=40, blank=True, null=True)
    hgh_Kettlebell2 = models.CharField(verbose_name='Kettlebell Rotational Press', max_length=40, blank=True, null=True)
    hgh_Bentover = models.CharField(verbose_name='Bentover Kettlebell Swing', max_length=40, blank=True, null=True)
    hgh_Rotational4 = models.CharField(verbose_name='Rotational Kettlebell Swing', max_length=40, blank=True, null=True)
    hgh_Single17 = models.CharField(verbose_name='Single Leg Kettlebell Swing & Change Arm', max_length=50, blank=True,
                                    null=True)
    hgh_Windmill = models.CharField(verbose_name='Windmill', max_length=40, blank=True, null=True)
    hgh_Atlas2 = models.CharField(verbose_name='Atlas Swing', max_length=40, blank=True, null=True)
    hgh_One2 = models.CharField(verbose_name='One Arm Atlas Swing', max_length=40, blank=True, null=True)
    hgh_Side2 = models.CharField(verbose_name='Side Swing', max_length=40, blank=True, null=True)
    hgh_One3 = models.CharField(verbose_name='One Arm Side Swing', max_length=40, blank=True, null=True)
    hgh_Bent3 = models.CharField(verbose_name='Bent Over Swing', max_length=40, blank=True, null=True)
    hgh_High6 = models.CharField(verbose_name='High Rotation KB', max_length=40, blank=True, null=True)
    hgh_Horizontal1 = models.CharField(verbose_name='Horizontal Swing ', max_length=40, blank=True, null=True)
    hgh_One4 = models.CharField(verbose_name='One Arm Horizontal Swing', max_length=40, blank=True, null=True)
    hgh_Barbell4 = models.CharField(verbose_name='Barbell Deadlift w/RB', max_length=40, blank=True, null=True)
    hgh_Deadbug1 = models.CharField(verbose_name='Deadbug Chest Press', max_length=40, blank=True, null=True)
    hgh_Bird2 = models.CharField(verbose_name='Bird Dog Single Arm Row on the bench', max_length=40, blank=True,
                                 null=True)
    hgh_Step2 = models.CharField(verbose_name='Step Lunge Sholuder Press', max_length=40, blank=True, null=True)
    hgh_Step3 = models.CharField(verbose_name='Step Lunge One Arm Shoulder Press', max_length=40, blank=True, null=True)
    hgh_Step4 = models.CharField(verbose_name='Step Lunge One Arm Bottom Shoulder Press', max_length=50, blank=True,
                                 null=True)
    hgh_Dumbell4 = models.CharField(verbose_name='Dumbell Split Snatch', max_length=40, blank=True, null=True)
    hgh_Single18 = models.CharField(verbose_name='Single Arm Pallof Press', max_length=40, blank=True, null=True)
    hgh_Single19 = models.CharField(verbose_name='Single Leg pallof press', max_length=40, blank=True, null=True)
    hgh_Single20 = models.CharField(verbose_name='Single Leg & Single Arm  Pallof Press', max_length=40, blank=True,
                                    null=True)
    hgh_Overhead = models.CharField(verbose_name='Overhead Plate Carry', max_length=40, blank=True, null=True)
    hgh_Jump2 = models.CharField(verbose_name='Jump Lunge Landmine Press ', max_length=40, blank=True, null=True)
    hgh_Jump3 = models.CharField(verbose_name='Jump Lunge Landmine Press Single Arm', max_length=40, blank=True,
                                 null=True)
    hgh_Band = models.CharField(verbose_name='Band Tall Kneel Front Lift', max_length=40, blank=True, null=True)
    hgh_Deadbug2 = models.CharField(verbose_name='Deadbug To Roll and Side Plank', max_length=40, blank=True, null=True)
    hgh_Deadbug3 = models.CharField(verbose_name='Deadbug To Roll and Side PlankPlank', max_length=40, blank=True,
                                    null=True)
    hgh_Step5 = models.CharField(verbose_name='Step Jump', max_length=40, blank=True, null=True)
    hgh_Vertical2 = models.CharField(verbose_name='Vertical Jump + Burpees', max_length=40, blank=True, null=True)
    hgh_Pushup2 = models.CharField(verbose_name='Push Up + Kettlebell Row on KB', max_length=40, blank=True, null=True)
    hgh_Push3 = models.CharField(verbose_name='Push Position Shoulder Flexion (Horizontal)', max_length=50, blank=True,
                                 null=True)
    hgh_Atlas3 = models.CharField(verbose_name='Atlas Swing', max_length=40, blank=True, null=True)
    hgh_One5 = models.CharField(verbose_name='One Arm Atlas Swing', max_length=40, blank=True, null=True)
    hgh_Side3 = models.CharField(verbose_name='Side Swing KB', max_length=40, blank=True, null=True)
    hgh_One6 = models.CharField(verbose_name='One Arm Side Swing KB', max_length=40, blank=True, null=True)
    hgh_Horizontal2 = models.CharField(verbose_name='Horizontal Arms Swing', max_length=40, blank=True, null=True)
    hgh_Horizontal3 = models.CharField(verbose_name='Horizontal One Arm Swing', max_length=40, blank=True, null=True)
    hgh_Bent4 = models.CharField(verbose_name='Bent Over Swing', max_length=40, blank=True, null=True)
    hgh_One7 = models.CharField(verbose_name='One Arm Bent Over Swing', max_length=40, blank=True, null=True)
    hgh_Lunge = models.CharField(verbose_name='Lunge Kettlebell Press + Windmill', max_length=40, blank=True, null=True)
    hgh_Landmine6 = models.CharField(verbose_name='Landmine Snatch', max_length=40, blank=True, null=True)
    hgh_Kneeling = models.CharField(verbose_name='Kneeling Landmine Snatch', max_length=40, blank=True, null=True)
    hgh_KB2 = models.CharField(verbose_name='KB Overhead Press (Sit Up)', max_length=40, blank=True, null=True)
    hgh_Ball = models.CharField(verbose_name='Ball Thoracic Extension + Row w/RB', max_length=40, blank=True, null=True)
    hgh_Side4 = models.CharField(verbose_name='Side Plank Hip up w/RB Row', max_length=40, blank=True, null=True)
    hgh_Side5 = models.CharField(verbose_name='Side Plank Hip up w/RB Press', max_length=40, blank=True, null=True)
    hgh_Deadbug4 = models.CharField(verbose_name='Deadbug to Roll Side plank', max_length=40, blank=True, null=True)
    hgh_Double1 = models.CharField(verbose_name='Double Kettlebell Clean', max_length=40, blank=True, null=True)
    hgh_Double2 = models.CharField(verbose_name='Double Kettlebell Swing', max_length=40, blank=True, null=True)
    hgh_Kettlebell3 = models.CharField(verbose_name='Kettlebell Deadlift to Swing', max_length=40, blank=True,
                                       null=True)
    hgh_Forward2 = models.CharField(verbose_name='Forward Lunge Single Arm Overhead Press', max_length=50, blank=True,
                                    null=True)
    hgh_Back2 = models.CharField(verbose_name='Back lunge Single Arm Bottom Overhead Shoulder Press', max_length=60,
                                 blank=True, null=True)
    hgh_G2OH = models.CharField(verbose_name='G2OH March Complex', max_length=40, blank=True, null=True)
    hgh_Hang = models.CharField(verbose_name='Hang Snatch + Hip Flexion w/KB', max_length=40, blank=True, null=True)

    class Meta:
        verbose_name = "Metabolic Egzersiz Reçetesi"
        verbose_name_plural = 'Metabolic Egzersiz Reçetesi'




class Metabolic(models.Model):
    trainer = models.ForeignKey(to=Trainer, verbose_name="Antrenör", on_delete=models.CASCADE, blank=True, null=True)
    personal = models.ForeignKey(to=Personal, verbose_name="Danışan", on_delete=models.CASCADE, blank=True, null=True)
    metabolic2 = models.ForeignKey(to=Metabolic2, verbose_name="Metabolic Egzersiz 2", on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateField(("Date"), default=datetime.now(), blank=True)
    level_selection = models.CharField(verbose_name='Düzey Seçimi', max_length=30, blank=True, null=True)
    difficulty = models.CharField(verbose_name='Zorluk Düzeyi', max_length=30, blank=True, null=True)
    load_rate = models.CharField(verbose_name='Yüklenme:Dinlenme Oranı', max_length=30, blank=True, null=True)
    load_time = models.CharField(verbose_name='Yüklenme:Dinlenme Süreleri', max_length=30, blank=True, null=True)
    set_count = models.CharField(verbose_name='Set Sayısı', max_length=30, blank=True, null=True)
    exercise_count = models.CharField(verbose_name='Egzersiz Sayısı', max_length=30, blank=True, null=True)
    # Yeni Başlayan
    nw_Squat1 = models.CharField(verbose_name='Squat', max_length=30, blank=True, null=True)
    nw_Lateral1 = models.CharField(verbose_name='Lateral Jump', max_length=30, blank=True, null=True)
    nw_In = models.CharField(verbose_name='In out ledder', max_length=30, blank=True, null=True)
    nw_Forward1 = models.CharField(verbose_name='Forward Bunny Hop', max_length=30, blank=True, null=True)
    nw_Mountain1 = models.CharField(verbose_name='Mountain Climber', max_length=30, blank=True, null=True)
    nw_High1 = models.CharField(verbose_name='High Knee', max_length=30, blank=True, null=True)
    nw_Jumping1 = models.CharField(verbose_name='Jumping Jack', max_length=30, blank=True, null=True)
    nw_Forward2 = models.CharField(verbose_name='Forward Running', max_length=30, blank=True, null=True)
    nw_Lateral2 = models.CharField(verbose_name='Lateral Shuffle', max_length=30, blank=True, null=True)
    nw_Step1 = models.CharField(verbose_name='Step up', max_length=30, blank=True, null=True)
    nw_Heel = models.CharField(verbose_name='Heel Touch to Butt Kick', max_length=30, blank=True, null=True)
    nw_Trippling = models.CharField(verbose_name='Trippling High Knee', max_length=30, blank=True, null=True)
    nw_Burpee = models.CharField(verbose_name='Burpee', max_length=30, blank=True, null=True)
    nw_Plank = models.CharField(verbose_name='Plank w/Toe Touch', max_length=30, blank=True, null=True)
    nw_Inchworm = models.CharField(verbose_name='Inchworm Plank', max_length=30, blank=True, null=True)
    nw_Double = models.CharField(verbose_name='Double Climbers', max_length=30, blank=True, null=True)
    nw_Crossbody = models.CharField(verbose_name='Crossbody Knees', max_length=30, blank=True, null=True)
    nw_Step2 = models.CharField(verbose_name='Step Jack', max_length=30, blank=True, null=True)
    nw_Press = models.CharField(verbose_name='Press Jack', max_length=30, blank=True, null=True)
    nw_Toe = models.CharField(verbose_name='Toe Touches into Squat', max_length=30, blank=True, null=True)
    nw_Overhead1 = models.CharField(verbose_name='Overhead Hands Hold In-Out Lea', max_length=40, blank=True, null=True)
    nw_Lateral3 = models.CharField(verbose_name='Lateral Hops', max_length=40, blank=True, null=True)
    nw_Scissor = models.CharField(verbose_name='Scissor Kick', max_length=40, blank=True, null=True)
    nw_Leg = models.CharField(verbose_name='Leg Raise', max_length=40, blank=True, null=True)
    nw_Forward3 = models.CharField(verbose_name='Forward Running', max_length=40, blank=True, null=True)
    nw_Back1 = models.CharField(verbose_name='Back Running', max_length=40, blank=True, null=True)
    nw_Squat3 = models.CharField(verbose_name='Squat Press', max_length=40, blank=True, null=True)
    nw_Squat4 = models.CharField(verbose_name='Squat Press', max_length=40, blank=True, null=True)
    nw_Jumping2 = models.CharField(verbose_name='Jumping Jack', max_length=40, blank=True, null=True)
    nw_Deadlift = models.CharField(verbose_name='Deadlift w/RB Row', max_length=40, blank=True, null=True)
    nw_High2 = models.CharField(verbose_name='High Knee', max_length=40, blank=True, null=True)
    nw_TRX = models.CharField(verbose_name='TRX Row', max_length=40, blank=True, null=True)
    nw_Front1 = models.CharField(verbose_name='Front Plank', max_length=40, blank=True, null=True)
    nw_Lateral4 = models.CharField(verbose_name='Lateral Squat Jump', max_length=40, blank=True, null=True)
    nw_Split = models.CharField(verbose_name='Split Lunge', max_length=40, blank=True, null=True)
    nw_Pushup1 = models.CharField(verbose_name='Push-up', max_length=40, blank=True, null=True)
    nw_Mountain2 = models.CharField(verbose_name='Mountain Climber', max_length=40, blank=True, null=True)
    nw_Glute = models.CharField(verbose_name='Glute Bridge', max_length=40, blank=True, null=True)
    nw_Woodchopper = models.CharField(verbose_name='Woodchopper', max_length=40, blank=True, null=True)
    nw_Jump1 = models.CharField(verbose_name='Jump Rope', max_length=40, blank=True, null=True)
    nw_Jump2 = models.CharField(verbose_name='Jump Ghost Rope', max_length=40, blank=True, null=True)
    nw_Bear1 = models.CharField(verbose_name='Bear Crawl', max_length=40, blank=True, null=True)
    nw_Bear2 = models.CharField(verbose_name='Bear Crawl Lateral', max_length=40, blank=True, null=True)
    nw_Lateral5 = models.CharField(verbose_name='Lateral Hops', max_length=40, blank=True, null=True)
    nw_Squat5 = models.CharField(verbose_name='Squat Front Kick', max_length=40, blank=True, null=True)
    nw_Back2 = models.CharField(verbose_name='Back Lunge', max_length=40, blank=True, null=True)
    nw_Pushup2 = models.CharField(verbose_name='Push-Up Leg Lift', max_length=40, blank=True, null=True)
    nw_Seated1 = models.CharField(verbose_name='Seated Pull Down RB', max_length=40, blank=True, null=True)
    nw_Seated2 = models.CharField(verbose_name='Seated Row RB', max_length=40, blank=True, null=True)
    nw_Shoulder = models.CharField(verbose_name='Shoulder Press RB', max_length=40, blank=True, null=True)
    nw_Lateral = models.CharField(verbose_name='Lateral Raise RB', max_length=40, blank=True, null=True)
    nw_Chest = models.CharField(verbose_name='Chest Press RB', max_length=40, blank=True, null=True)
    nw_Superman = models.CharField(verbose_name='Superman', max_length=40, blank=True, null=True)
    nw_Thoracic = models.CharField(verbose_name='Thoracic Extension', max_length=40, blank=True, null=True)
    nw_Front2 = models.CharField(verbose_name='Front Raise RB', max_length=40, blank=True, null=True)
    nw_Biceps = models.CharField(verbose_name='Biceps Curl RB', max_length=40, blank=True, null=True)
    nw_Overhead2 = models.CharField(verbose_name='Overhead Triceps Extension RB', max_length=40, blank=True, null=True)
    nw_Lunge = models.CharField(verbose_name='Lunge w/Push Down RB', max_length=40, blank=True, null=True)
    nw_Reverse = models.CharField(verbose_name='Reverse Fly RB', max_length=40, blank=True, null=True)
    nw_Overhead = models.CharField(verbose_name='Overhead Press RB', max_length=40, blank=True, null=True)
    nw_Facepull = models.CharField(verbose_name='Facepull RB', max_length=40, blank=True, null=True)
    nw_Sumo = models.CharField(verbose_name='Sumo Squat Pulse 3x to Calf Raise', max_length=40, blank=True, null=True)
    nw_Kneeling1 = models.CharField(verbose_name='Kneeling Hip Extension w/RB Row', max_length=40, blank=True, null=True)
    nw_Kneeling2 = models.CharField(verbose_name='Kneeling Hip Extension w/Chest Press RB', max_length=40, blank=True, null=True)
    nw_Side = models.CharField(verbose_name='Side Plank Chest Press', max_length=40, blank=True, null=True)
    # Orta Seviye
    mdl_Squat1 = models.CharField(verbose_name='Squat Triple Extension', max_length=40, blank=True, null=True)
    mdl_Lateral1 = models.CharField(verbose_name='Lateral Bounding', max_length=40, blank=True, null=True)
    mdl_Spider = models.CharField(verbose_name='Spider Climber', max_length=40, blank=True, null=True)
    mdl_High1 = models.CharField(verbose_name='High Knee + Truck Jump', max_length=40, blank=True, null=True)
    mdl_Jumping1 = models.CharField(verbose_name='Jumping Jack + Squat', max_length=40, blank=True, null=True)
    mdl_Lateral2 = models.CharField(verbose_name='Lateral Shuffle + Reverse Lunge', max_length=40, blank=True, null=True)
    mdl_Step1 = models.CharField(verbose_name='Step up + Jump', max_length=40, blank=True, null=True)
    mdl_Skater1 = models.CharField(verbose_name='Skater', max_length=40, blank=True, null=True)
    mdl_Burpee1 = models.CharField(verbose_name='Burpee Jump', max_length=40, blank=True, null=True)
    mdl_Squat2 = models.CharField(verbose_name='Squat Jack', max_length=40, blank=True, null=True)
    mdl_Forward = models.CharField(verbose_name='Forward Hops', max_length=40, blank=True, null=True)
    mdl_Lateral3 = models.CharField(verbose_name='Lateral Hops', max_length=40, blank=True, null=True)
    mdl_Pushup1 = models.CharField(verbose_name='Push Up Walk Back', max_length=40, blank=True, null=True)
    mdl_Roll = models.CharField(verbose_name='Roll To Stand', max_length=40, blank=True, null=True)
    mdl_Lunge1 = models.CharField(verbose_name='Lunge Skip', max_length=40, blank=True, null=True)
    mdl_Wacky = models.CharField(verbose_name='Wacky Jack', max_length=40, blank=True, null=True)
    mdl_Lunge2 = models.CharField(verbose_name='Lunge Jack', max_length=40, blank=True, null=True)
    mdl_Froggers = models.CharField(verbose_name='Froggers', max_length=40, blank=True, null=True)
    mdl_Leg1 = models.CharField(verbose_name='Leg Raise', max_length=40, blank=True, null=True)
    mdl_Scissor = models.CharField(verbose_name='Scissor Kick', max_length=40, blank=True, null=True)
    mdl_Skipping1 = models.CharField(verbose_name='Skipping', max_length=40, blank=True, null=True)
    mdl_Skipping2 = models.CharField(verbose_name='Skipping Ghost Rope Hops', max_length=40, blank=True, null=True)
    mdl_Step2 = models.CharField(verbose_name='Step Jump', max_length=40, blank=True, null=True)
    mdl_Lateral4 = models.CharField(verbose_name='Lateral Hops w/Step board', max_length=40, blank=True, null=True)
    mdl_Squat3 = models.CharField(verbose_name='Squat Shoulder Press w/Resband', max_length=40, blank=True, null=True)
    mdl_Kneeling1 = models.CharField(verbose_name='Kneeling Pull Down w/RB', max_length=40, blank=True, null=True)
    mdl_Lateral5 = models.CharField(verbose_name='Lateral Shuffle', max_length=40, blank=True, null=True)
    mdl_Goblet = models.CharField(verbose_name='Goblet Squat', max_length=40, blank=True, null=True)
    mdl_High2 = models.CharField(verbose_name='High Knee Lateral', max_length=40, blank=True, null=True)
    mdl_Kneeling2 = models.CharField(verbose_name='Kneeling Landmine Press', max_length=40, blank=True, null=True)
    mdl_Pallof = models.CharField(verbose_name='Pallof Press', max_length=40, blank=True, null=True)
    mdl_Jumping2 = models.CharField(verbose_name='Jumping Rope', max_length=40, blank=True, null=True)
    mdl_Romanian = models.CharField(verbose_name='Romanian Dumbbell Deadlift', max_length=40, blank=True, null=True)
    mdl_Seated = models.CharField(verbose_name='Seated Shoulder Press', max_length=40, blank=True, null=True)
    mdl_Jump = models.CharField(verbose_name='Jump Squat', max_length=40, blank=True, null=True)
    mdl_Bird = models.CharField(verbose_name='Bird Dog', max_length=40, blank=True, null=True)
    mdl_Barbell = models.CharField(verbose_name='Barbell Torque', max_length=40, blank=True, null=True)
    mdl_Bear = models.CharField(verbose_name='Bear Crawl Shoulder Tap', max_length=40, blank=True, null=True)
    mdl_Hollow = models.CharField(verbose_name='Hollow Hold', max_length=40, blank=True, null=True)
    mdl_Burpee2 = models.CharField(verbose_name='Burpee', max_length=40, blank=True, null=True)
    mdl_Deadlift1 = models.CharField(verbose_name='Deadlift Dumbell', max_length=40, blank=True, null=True)
    mdl_Bench = models.CharField(verbose_name='Bench Dips', max_length=40, blank=True, null=True)
    mdl_Farmers = models.CharField(verbose_name='Farmers Walk', max_length=40, blank=True, null=True)
    mdl_Trx = models.CharField(verbose_name='Trx Row', max_length=40, blank=True, null=True)
    mdl_Side1 = models.CharField(verbose_name='Side Plank', max_length=40, blank=True, null=True)
    mdl_Side2 = models.CharField(verbose_name='Side Plank Hip Lift', max_length=40, blank=True, null=True)
    mdl_Side3 = models.CharField(verbose_name='Side Plank Row RB', max_length=40, blank=True, null=True)
    mdl_Side4 = models.CharField(verbose_name='Side Plank Reverse Fly RB', max_length=40, blank=True, null=True)
    mdl_Side5 = models.CharField(verbose_name='Side Plank Rotation', max_length=40, blank=True, null=True)
    mdl_Skater2 = models.CharField(verbose_name='Skater Jump', max_length=40, blank=True, null=True)
    mdl_Leg2 = models.CharField(verbose_name='Leg Raise', max_length=40, blank=True, null=True)
    mdl_Step3 = models.CharField(verbose_name='Step Up', max_length=40, blank=True, null=True)
    mdl_Sumo = models.CharField(verbose_name='Sumo Deadlift', max_length=40, blank=True, null=True)
    mdl_Interved = models.CharField(verbose_name='Interved Row', max_length=40, blank=True, null=True)
    mdl_Pushup2 = models.CharField(verbose_name='Push Up Shoulder Tap', max_length=40, blank=True, null=True)
    mdl_Landmine = models.CharField(verbose_name='Landmine Press Kneeling', max_length=40, blank=True, null=True)
    mdl_Kneeling3 = models.CharField(verbose_name='Kneeling Landmine Rotation', max_length=40, blank=True, null=True)
    mdl_Push1 = models.CharField(verbose_name='Push Bird Dog', max_length=40, blank=True, null=True)
    mdl_Dead = models.CharField(verbose_name='Dead Bug Chest Press', max_length=40, blank=True, null=True)
    mdl_Sandbag = models.CharField(verbose_name='Sandbag Rotational Lunge', max_length=40, blank=True, null=True)
    mdl_Right = models.CharField(verbose_name='Right Leg Forward Lunge Hops 2x', max_length=50, blank=True, null=True)
    mdl_Left = models.CharField(verbose_name='Left Leg Forward Lunge Hops 2x', max_length=50, blank=True, null=True)
    mdl_Alt = models.CharField(verbose_name='Alt. Cursty Lunge to Jump Squat', max_length=40, blank=True, null=True)
    mdl_Side6 = models.CharField(verbose_name='Side Steps', max_length=40, blank=True, null=True)
    mdl_Lunge3 = models.CharField(verbose_name='Lunge Shoulder Press', max_length=40, blank=True, null=True)
    mdl_Split1 = models.CharField(verbose_name='Split Lunge Overhead Lift', max_length=40, blank=True, null=True)
    mdl_Split2 = models.CharField(verbose_name='Split Lunge Forward Kettlebell Press', max_length=40, blank=True, null=True)
    mdl_Scapular = models.CharField(verbose_name='Scapular Push Up', max_length=40, blank=True, null=True)
    mdl_Push2 = models.CharField(verbose_name='Push & Plank', max_length=40, blank=True, null=True)
    mdl_Bentover = models.CharField(verbose_name='Bentover Banded Aparat', max_length=40, blank=True, null=True)
    mdl_Deadlift2 = models.CharField(verbose_name='Deadlift + Squat press plate', max_length=40, blank=True, null=True)
    mdl_Farmers1 = models.CharField(verbose_name='Farmers Carry KB', max_length=40, blank=True, null=True)
    mdl_Farmers2 = models.CharField(verbose_name='Farmers Carry DB', max_length=40, blank=True, null=True)
    mdl_Farmers3 = models.CharField(verbose_name='Farmers Carry Barbell', max_length=40, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('metabolic-detail', kwargs={'id': self.id})

    def get_update_url(self):
        return reverse('metabolic-update', kwargs={'id': self.id})

    def get_trainer_metabolic_exercise_delete_url(self):
        return reverse('trainer-metabolic-exercise-delete', kwargs={'id': self.id})

    def get_corporate_metabolic_exercise_delete_url(self):
        return reverse('corporate-metabolic-exercise-delete', kwargs={'id': self.id})

    def get_personal_metabolic_exercise_delete_url(self):
        return reverse('personal-metabolic-exercise-delete', kwargs={'id': self.id})

    class Meta:
        verbose_name = "Metabolic Egzersiz Reçetesi"
        verbose_name_plural = 'Metabolic Egzersiz Reçetesi'