EXERCISE = {
    'CARDIO': {
        'LEVEL': {
            '1': 'Düşük Seviye',
            '2': 'Orta Seviye',
            '3': 'Yüksek Seviye',
        },
        'PURPOSE': {
            'health': 'Genel Sağlık Gelişimi',
            'weak': 'Zayıflama İncelme',
            'metabolik': 'Metabolik Uygunluk Gelişimi',
            'performace': 'Performans Artışı',
        },
        'DAYS': {
            'monday': 'Pazartesi',
            'tuesday': 'Salı',
            'wednesday': 'Çarşamba',
            'thursday': 'Perşembe',
            'friday': 'Cuma',
            'saturday': 'Cumartesi',
            'sunday': 'Pazar',
        },
        'TRAINING': {
            '1': '%90-100',
            '2': '%80-89',
            '3': '%70-79',
            '4': '%60-69',
            '5': '%50-59',
            '6': '%40-49',
            '7': '%30-39',
        },
        'CONSTANT': {
            'treadmill': 'Koşu bandı',
            'shovel': 'Kürek',
            'bike': 'Bisikletler',
            'mixed_pattern': 'Karma Desen',
        },
        'VARIABLE': {
            '1': 'HIIT',
            '2': 'MIIT',
            '3': 'LIIT',
        },
        'TRAININGTIME': {
            '1': '10 dk',
            '2': '15 dk',
            '3': '30 dk',
            '4': '45 dk',
            '5': '60 dk',
            '6': '90 dk',
            '7': '120 dk',
        },
        'REST': {
            '1': 'Seriler Arası',
            '2': 'Hareketler Arası',
        },
        'PERIOD': {
            '1': 'Doğrusal',
            '2': 'Dalgalı',
        },
        'FILE': {
            '1': 'Günlük',
            '2': 'Haftalık',
            '3': 'Aylık',
            '4': '3 Aylık',
            '5': '6 Aylık',
            '6': 'Yıllık',
        },
    },
    'RESISTANCE': {
        'PURPOSE': {
            'health1': 'Genel Sağlık Gelişimi',
            'force': 'Genel Kuvvet Gelişimi',
            'muscular_endurance': 'Kas Dayanıklılığı',
            'muscle_mass': 'Kas Kütlesi Artışı',
            'optimal': 'Optimal Hipertrofi',
            'fonksiyonel': 'Fonksiyonel Hipertrofi',
            'explosive_force': 'Patlayıcı Kuvvet',
        },
        'DAYSANDTRAINING': {
            'DAYS': {
                'monday1': 'Pazartesi',
                'tuesday1': 'Salı',
                'wednesday1': 'Çarşamba',
                'thursday1': 'Perşembe',
                'friday1': 'Cuma',
                'saturday1': 'Cumartesi',
                'sunday1': 'Pazar',
            },
            'TRAININGTYPE': {
                '1': 'Total Vücut',
                '2': 'Delorme ',
                '3': 'Oxford ',
                '4': 'Klasik Setleme',
                '5': 'Split Rutin',
                '6': 'Piramit (Geleneksel)',
                '7': 'Çift Piramit',
                '8': 'Küt Piramit',
                '9': 'Çekme-İtme ',
                '10': 'Super Set',
                '11': 'Ağır-Hafif Gün ',
                '12': 'HIIRT ',

            },
        },
        'AKUT': {
            'TEMPO': {
                '1': '101',
                '2': '102',
                '3': '201',
                '4': '202',
                '5': '203',
                '6': '302',
                '7': '303',
                '8': '304',
                '9': '403',
                '10': '404',
            },
            'SET': {
                '1': '30 sn',
                '2': '60 sn',
                '3': '90 sn',
                '4': '120 sn',
                '5': '3 dk',
                '6': '5 dk',
            },
            'MOVEMENT': {
                '1': '1 dk',
                '2': '2 dk',
                '3': '3 dk',
                '4': '4 dk',
                '5': '5 dk',
            },
            'EXERCISE': {
                'CHEST': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'chest_kl_level1_knee': 'Knee Push-Up',
                            'chest_kl_level1_hand': 'Hand Elevated Push-Up',
                            'chest_kl_level1_reverse': 'Reverse Push-Up',
                            'chest_kl_level1_hip': 'Push-Up and Hip Abduction',
                            'chest_kl_level1_svend': 'Svend Press w/Med Ball',
                            'chest_kl_level1_decline': 'Decline Push-Up/Feet Elevated',
                            'chest_kl_level1_chest': 'Chest Pass w/ Med Ball',
                        },
                        'LEVEL2': {
                            'chest_kl_level2_pushup': 'Push-up',
                            'chest_kl_level2_archer': 'Archer Push-Up',
                            'chest_kl_level2_reverse': 'Reverse Push-Up',
                            'chest_kl_level2_hip': 'Push-Up and Hip Abduction',
                            'chest_kl_level2_depthdrop': 'Depth-drop Push-up',
                            'chest_kl_level2_diver': 'Diver Bomb Push-Up',
                            'chest_kl_level2_decline': 'Decline Push-Up/Feet Elevated',
                            'chest_kl_level2_rolling': 'Push-Up Rolling w/Med Ball',
                            'chest_kl_level2_cross': 'Cross Over Push-Up',
                            'chest_kl_level2_chest': 'Chest Pass w/ Med Ball',
                        },
                        'LEVEL3': {
                            'chest_kl_level3_jumping': 'Jumping Push-Up',
                            'chest_kl_level3_diamond': 'Diamond Push-Up',
                            'chest_kl_level3_archer': 'Archer Push-Up',
                            'chest_kl_level3_tpushup': 'T-Push-Up',
                            'chest_kl_level3_depthdrop': 'Depth-drop Push-up',
                            'chest_kl_level3_diver': 'Diver Bomb Push-Up',
                            'chest_kl_level3_dips': 'Parallel Dips',
                            'chest_kl_level3_rotational': 'Rotational Throw w/Med Bal',
                            'chest_kl_level3_rolling': 'Push-Up Rolling w/Med Ball',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'chest_wg_level1_barbell': 'Flat Bench Chest Press w/Barbell',
                            'chest_wg_level1_dumbbell': 'Flat Bench Chest Press w/Dumbbell',
                            'chest_wg_level1_bilateral': 'Flat Bench Bilateral Chest Press w/Dumbbell',
                            'chest_wg_level1_inc': 'Incline Bench Bilateral Chest Press',
                            'chest_wg_level1_decline': 'Decline Bench Chest Press w/Dumbbell',
                            'chest_wg_level1_decline_bil': 'Decline Bench Bilateral Chest Press w/Dumbbell',
                            'chest_wg_level1_flat_fly': 'Flat Bench Chest Fly w/Dumbbell & KB',
                            'chest_wg_level1_inc_fly': 'Incline Bench Chest Fly w/Dumbbell',
                            'chest_wg_level1_dc_fly': 'Decline Bench Chest Fly w/Dumbbell',
                            'chest_wg_level1_flr_ch': 'Floor Chest Press w/Dumbbell & Kettlebell',
                            'chest_wg_level1_flr_fly': 'Floor Fly w/Kettlebell & Dumbbell',
                        },
                        'LEVEL2': {
                            'chest_wg_level2_barbell': 'Flat Bench Chest Press w/Barbell',
                            'chest_wg_level2_dambbell': 'Flat Bench Bilateral Chest Press w/Dumbbell',
                            'chest_wg_level2_unilateral': 'Flat Bench Unilateral Chest Press w/Dumbbell',
                            'chest_wg_level2_incline': 'Incline Bench Chest Press w/Dumbbell',
                            'chest_wg_level2_inc_bil': 'Incline Bench Bilateral Chest Press',
                            'chest_wg_level2_inc_cntr': 'Incline Bench Contralateral Chest Press',
                            'chest_wg_level2_decline': 'Decline Bench Chest Press w/Barbell',
                            'chest_wg_level2_dc_bil': 'Decline Bench Bilateral Chest Press w/Dumbbell',
                            'chest_wg_level2_dc_cntr': 'Decline Bench Contralateral Chest Press w/Dumbbell',
                            'chest_wg_level2_inc_fly': 'Incline Bench Chest Fly w/Dumbbell',
                            'chest_wg_level2_flt_svnd': 'Flat Bench Svend Press w/Plate',
                            'chest_wg_level2_flr': 'Floor Chest Press w/Dumbbell & Kettlebell',
                            'chest_wg_level2_single': 'Single- Arm Floor Press w/Kettlebell',
                            'chest_wg_level2_oblq': 'Oblique Sling Chest Press w/Deadbug Dumbbell&Kettlebell',

                        },
                        'LEVEL3': {
                            'chest_wg_level3_unilateral': 'Flat Bench Unilateral Chest Press w/Dumbbell',
                            'chest_wg_level3_barbell': 'Incline Bench Chest Press w/Barbell',
                            'chest_wg_level3_dumbbell': 'Incline Bench Chest Press w/Dumbbell',
                            'chest_wg_level3_contr': 'Incline Bench Contralateral Chest Press',
                            'chest_wg_level3_oblique': 'Oblique Sling Chest Press w/Deadbug Dumbbell&Kettlebell',
                            'chest_wg_level3_hangig': 'Hanging Kettlebell Bench Press',
                            'chest_wg_level3_throw': 'Flat Bench Press Throw w/Barbell',
                            'chest_wg_level3_inc_landmine': 'Incline Landmine Press',
                            'chest_wg_level3_crossover': 'Landmine Crossover',
                            'chest_wg_level3_crush': 'Crush Grip Push Up',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'chest_mc_level1_seated': 'Seated Machine Chest Press',
                            'chest_mc_level1_st_fly': 'Seated Machine Chest Fly (Butterfly)',
                            'chest_mc_level1_flat': 'Flat Bench Smith Machine Chest Press',
                            'chest_mc_level1_decline': 'Decline Bench Smith Machine Chest Press',
                            'chest_mc_level1_incline': 'Incline Bench Smith Machine Chest Press',
                        },
                        'LEVEL2': {
                            'chest_mc_level2_flat': 'Flat Bench Smith Machine Chest Press',
                            'chest_mc_level2_dc_smith': 'Decline Bench Smith Machine Chest Press',
                            'chest_mc_level2_inc_smith': 'Incline Bench Smith Machine Chest Press',
                            'chest_mc_level2_flt_single': 'Flat Bench Single-Arm Chest Press w/Cable',
                            'chest_mc_level2_standing': 'Standing Stability Chest Press w/Cable',
                            'chest_mc_level2_incline': 'Incline Bench Chest Press w/Cable',
                            'chest_mc_level2_decline': 'Decline Bench Chest Press w/Cable',
                            'chest_mc_level2_high': 'High Cable Chest Fly (Cable Crossover)',
                            'chest_mc_level2_low': 'Low Cable Chest Fly',
                            'chest_mc_level2_middle': 'Middle Cable Chest Fly',
                            'chest_mc_level2_inc_fly': 'Incline Bench Chest Fly w/Cable',
                            'chest_mc_level2_dc_fly': 'Decline Bench Chest Fly w/Cable',
                        },
                        'LEVEL3': {
                            'chest_mc_level3_machine': 'Flat Bench Smith Machine Chest Throw',
                            'chest_mc_level3_incline': 'Incline Bench Chest Press w/Cable',
                            'chest_mc_level3_decline': 'Decline Bench Chest Press w/Cable',
                            'chest_mc_level3_push': 'Push Position Cable Chest Fly w/Cable',
                            'chest_mc_level3_single': 'Single Leg Chest Fly w/Cable',
                            'chest_mc_level3_bird': 'Bird Dog Chest Fly w/Cable',
                            'chest_mc_level3_dead': 'Dead Bug Chest Fly w/Cable',
                            'chest_mc_level3_inc_fly': 'Incline Bench Chest Fly w/Cable',
                            'chest_mc_level3_dc_fly': 'Decline Full Range Fly w/Cable',
                            'chest_mc_level3_dc_chop': 'Decline Chop, Tall Kneeling',
                            'chest_mc_level3_cable': 'Cable Tall Kneeling Single Arm Chest Fly w/Cable',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'chest_rc_level1_pushup': 'Push-Up w/RB',
                            'chest_rc_level1_dynamic': 'Dynamic Hug w/RB',
                            'chest_rc_level1_serratus': 'Serratus Punch w/RB',
                            'chest_rc_level1_diagonal': 'Diagonal Cross w/RB',
                            'chest_rc_level1_chest': 'Chest Fly',
                            'chest_rc_level1_psh_plus': 'Push-Up Plus w/Strap',
                            'chest_rc_level1_single': 'Single Arm Chest Press w/Straps',
                            'chest_rc_level1_ch_fly': 'Chest Fly Offset Stance w/Straps',
                        },
                        'LEVEL2': {
                            'chest_rc_level2_pushup': 'Push-Up w/RB',
                            'chest_rc_level2_flat': 'Flat Bench Press w/RB',
                            'chest_rc_level2_wrap': 'Wrap Around Press w/RB',
                            'chest_rc_level2_incline': 'Incline Chest Press w/RB',
                            'chest_rc_level2_decline': 'Decline Chest Press w/RB',
                            'chest_rc_level2_dc_fly': 'Decline Standing Chest Fly w/RB',
                            'chest_rc_level2_prone': 'Prone Punchouts w/RB',
                            'chest_rc_level2_rotational': 'Rotational Lunge with one-arm Chest Press w/RB',
                            'chest_rc_level2_chest': 'Chest Fly',
                            'chest_rc_level2_sngl_leg': 'Single Leg Flexed Chest Fly w/Straps',
                            'chest_rc_level2_sndl_arm': 'Single Arm Chest Press w/Straps',
                            'chest_rc_level2_drop': 'Drop Push-Up w/Strap',
                            'chest_rc_level2_ch_press': 'Chest Press, Inside Grip w/Strap',
                        },
                        'LEVEL3': {
                            'chest_rc_level3_pushup': 'Push Up and Chest Fly w/RB',
                            'chest_rc_level3_wrap': 'Wrap Around Press w/RB',
                            'chest_rc_level3_incline': 'Incline Chest Press w/RB',
                            'chest_rc_level3_decline': 'Decline Chest Press w/RB',
                            'chest_rc_level3_st_standing': 'Decline Standing Chest Fly w/RB',
                            'chest_rc_level3_plank': 'Plank & Push Punchouts w/RB',
                            'chest_rc_level3_sngl_fly': 'Single-Arm Chest Fly w/Strap',
                            'chest_rc_level3_sngl_ex': 'Single Leg Extended Chest Press w/Straps',
                            'chest_rc_level3_sngl_arm': 'Single Leg Chest Press Single Arm w/RB',
                            'chest_rc_level3_inc_pushup': 'Incline Push-Up w/Strap',
                            'chest_rc_level3_suspended': 'Suspended Push-Up w/Strap',
                            'chest_rc_level3_prone': 'Prone Iron Cross w/Strap',
                            'chest_rc_level3_crunch': 'Push-Up w/Reverse Crunch',
                            'chest_rc_level3_oblique': 'Suspended Oblique Atomic Push Up w/Strap',
                            'chest_rc_level3_drop': 'Drop Push-Up w/Strap',
                            'chest_rc_level3_explosive': 'Explosive Push-Up',
                        },
                    },
                },
                'SHOULDER': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'shld_kl_level1_rotator': 'Shoulder Rotator Cuff Rotation 90 Degree',
                            'shld_kl_level1_shoulder': 'Shoulder W at Wall',
                            'shld_kl_level1_sphinx': 'Sphinx Pose with Shoulder Forward Reach',
                            'shld_kl_level1_pushup': 'Push-Up Squat to Press w/Medicine Ball',
                            'shld_kl_level1_overhead': 'Overhead Reach w/Medicine Ball',
                            'shld_kl_level1_ys': 'Dumbbell Shoulder Y’s',
                            'shld_kl_level1_as': 'Dumbbell Shoulder A’s',
                            'shld_kl_level1_ts': 'Dumbbell Shoulder T’s',
                        },
                        'LEVEL2': {
                            'shld_kl_level2_inverted': 'Inverted Shoulder Press',
                            'shld_kl_level2_wall': 'Wall Ball w/Medicine Ball',
                            'shld_kl_level2_pushup': 'Push-Up Squat to Press w/Medicine Ball',
                            'shld_kl_level2_diagonal': 'Diagonal Chop and Lift w/Medicine Ball',
                            'shld_kl_level2_reverse': 'Reverse Scoop Throw w/Medicine Ball',
                        },
                        'LEVEL3': {
                            'shld_kl_level3_wall': 'Wall Walk',
                            'shld_kl_level3_handstand': 'Handstand Push-Up ',
                            'shld_kl_level3_reverse': 'Reverse Scoop Throw w/Medicine Ball',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'shld_wg_level1_std_dumbbell': 'Seated Dumbbell Shoulder Press',
                            'shld_wg_level1_sd_shoulder': 'Standing Dumbbell Shoulder Press w/Dumbbell &KB',
                            'shld_wg_level1_tl_dumbbell': 'Tall Kneeling Dumbbell Shoulder Press w/Dumbbell & KB',
                            'shld_wg_level1_barbell': 'Barbell Overhead Push Press',
                            'shld_wg_level1_lseated': 'Dumbbell L-Seated Shoulder Z Press',
                            'shld_wg_level1_alternating': 'Alternating Shoulder Press w/Dumbbell',
                            'shld_wg_level1_onearm': 'One-Arm Shoulder Press w/Dumbbell',
                            'shld_wg_level1_side': 'Dumbbell Side Lying Lateral Raise',
                            'shld_wg_level1_sd_lateral': 'Standing Dumbbell Lateral Raise',
                            'shld_wg_level1_std_lateral': 'Seated Dumbbell Lateral Raise',
                            'shld_wg_level1_shl_bench': 'Shoulder Reverse on Bench Fly w/Dumbbell',
                            'shld_wg_level1_shl_front': 'Shoulder Front Raise w/Dumbbell',
                            'shld_wg_level1_shl_raise': 'Shoulder Front Raise w/Plate',
                            'shld_wg_level1_tl_knee': 'Tall Kneeling Shoulder Front Raise w/Dumbbell & Plate',
                            'shld_wg_level1_up_dumbbell': 'Upright Row w/Dumbbell',
                            'shld_wg_level1_up_barbell': 'Upright Row w/BarBell',
                            'shld_wg_level1_wide_arm': 'Dumbbell Wide-Arm Upright Row',
                            'shld_wg_level1_power': 'Power Jerk w/Dumbbell',
                        },
                        'LEVEL2': {
                            'shld_wg_level2_flat': 'Flat Barbell Standing Shoulder Press',
                            'shld_wg_level2_barbell': 'Barbell Overhead Push Press',
                            'shld_wg_level2_shl_bottom': 'Shoulder Bottom-Up Pres w/KB',
                            'shld_wg_level2_seated': 'Seated Barbell Shoulder Press',
                            'shld_wg_level2_lseated': 'Dumbbell L-Seated Shoulder Z Press',
                            'shld_wg_level2_kettlebell': 'One Arm Kettlebell Push Press',
                            'shld_wg_level2_alternating': 'Alternating Shoulder Press w/Dumbbell',
                            'shld_wg_level2_onearm': 'One-Arm Shoulder Press w/Dumbbell',
                            'shld_wg_level2_side': 'Dumbbell Side Lying Lateral Raise',
                            'shld_wg_level2_reverse': 'Shoulder Reverse on Bench Fly w/Dumbbell',
                            'shld_wg_level2_bent': 'Bent Over Dumbbell Reverse Fly w/Dumbbell / KB',
                            'shld_wg_level2_overhead': 'Kettlebell Overhead Swing',
                            'shld_wg_level2_front': 'Shoulder Front Raise w/Plate',
                            'shld_wg_level2_bentover': 'Bent-Over Dumbbell Shoulder Fly',
                            'shld_wg_level2_up_dumbbell': 'Upright Row w/Dumbbell',
                            'shld_wg_level2_up_barbell': 'Upright Row w/BarBell',
                            'shld_wg_level2_widearm': 'Dumbbell Wide-Arm Upright Row',
                            'shld_wg_level2_thruster': 'Dumbbell Thruster',
                            'shld_wg_level2_lunge': 'Front Lunge with Lateral Raise w/Dumbbell',
                            'shld_wg_level2_pw_dumbbell': 'Power Jerk w/Dumbbell',
                            'shld_wg_level2_pw_barbell': 'Power Jerk w/Barbell',
                            'shld_wg_level2_alt_power': 'Alternating Power Jerk w/Dumbbell',
                            'shld_wg_level2_sp_jerk': 'Split Alternating-Feet Jerk',
                            'shld_wg_level2_sp_feet': 'Split Alternating-Feet Alternating-Arm Jerk',
                        },
                        'LEVEL3': {
                            'shld_wg_level3_shoulder': 'Shoulder Bottom-Up Pres w/KB',
                            'shld_wg_level3_std_barbell': 'Seated Barbell Shoulder Press',
                            'shld_wg_level3_rotational': 'One-Arm Dumbbell Rotational Push Press',
                            'shld_wg_level3_unilateral': 'Standing Unilateral Dumbbell Press',
                            'shld_wg_level3_angled': 'Angled Barbell Press (Landmine)',
                            'shld_wg_level3_side': 'Side Bridge and Lateral Raise w/Dumbbell',
                            'shld_wg_level3_snatch': 'Dumbbell Snatch',
                            'shld_wg_level3_ropes': 'Battle Ropes, Double Wave',
                            'shld_wg_level3_kettlebell': 'Kettlebell Overhead Swing',
                            'shld_wg_level3_upright': 'Upright Row with Triple Extension Barbell',
                            'shld_wg_level3_brb_thruster': 'Barbell Thruster',
                            'shld_wg_level3_dmb_thruster': 'Dumbbell Thruster',
                            'shld_wg_level3_push': 'Push Ups with Shoulder Abduction w/Dumbbell ',
                            'shld_wg_level3_onearm_ket': 'One Arm Kettlebell Push and Jerk',
                            'shld_wg_level3_lunge': 'Front Lunge with Lateral Raise w/Dumbbell',
                            'shld_wg_level3_pw_jerk': 'Power Jerk w/Barbell',
                            'shld_wg_level3_split': 'Split Alternating-Feet Alternating-Arm Jerk',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'shld_mc_level1_cb_onearm': 'Cable One-Arm Shoulder Press',
                            'shld_mc_level1_rear': 'Rear Deltoid High Row (Machine)',
                            'shld_mc_level1_shl_reverse': 'Shoulder Reverse Fly (Cable)',
                            'shld_mc_level1_upright': 'Upright Rows (Low Pulley) w/Cable',
                            'shld_mc_level1_onearm_lateral': 'One-arm Cable Lateral Raise',
                            'shld_mc_level1_onearm_front': 'One-arm Cable Front Raise',
                            'shld_mc_level1_shl_front': 'Shoulder Front Raise w/Cable',
                            'shld_mc_level1_cb_reverse': 'Cable Reverse Shoulder Fly',
                        },
                        'LEVEL2': {
                            'shld_mc_level2_behind': 'Behind The Neck Press (Flat Barbell or Smith Machine)',
                            'shld_mc_level2_cb_onearm': 'Cable One-Arm Shoulder Press',
                            'shld_mc_level2_stability': 'Stability Cable Shoulder Press Progression',
                            'shld_mc_level2_reverse': 'Reverse Stepping Chop (Rip Trainer)',
                            'shld_mc_level2_rear': 'Rear Deltoid High Row (Machine)',
                            'shld_mc_level2_bentavor': 'Bentover Reverse Fly (Cable)',
                            'shld_mc_level2_onearm': 'One-arm Cable Lateral Raise',
                            'shld_mc_level2_shoulder': 'Shoulder Front Raise w/Cable',
                            'shld_mc_level2_rope': 'Rope Face Pull',
                            'shld_mc_level2_cb_reverse': 'Cable Reverse Shoulder Fly',
                        },
                        'LEVEL3': {
                            'shld_mc_level3_shoulder': 'Shoulder Barbell Throw w Smite Machine',
                            'shld_mc_level3_stability': 'Stability Cable Shoulder Press Progression',
                            'shld_mc_level3_reverse': 'Reverse Stepping Chop (Rip Trainer)',
                            'shld_mc_level3_rope': 'Rope Face Pull',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'shld_rc_level1_Ideltoid': 'I Deltoid Fly w/Straps',
                            'shld_rc_level1_Ydeltoid': 'Y Deltoid Fly w/Straps',
                            'shld_rc_level1_dualarm': 'Dual-Arm External Rotation w/Strap',
                            'shld_rc_level1_field': 'Field Goal w/Strap',
                            'shld_rc_level1_press': 'Shoulder Press w/Resistance Band',
                            'shld_rc_level1_front': 'Shoulder Front Raise w/RB ',
                            'shld_rc_level1_rear': 'Rear Deltoid Row w/RB',
                            'shld_rc_level1_upright': 'Upright Row w/RB',
                            'shld_rc_level1_kneeling': 'Kneeling Front Raise w/RB',
                        },
                        'LEVEL2': {
                            'shld_rc_level2_high': 'High Back Row w/Straps',
                            'shld_rc_level2_Ideltoid': 'I Deltoid Fly w/Straps',
                            'shld_rc_level2_Ydeltoid': 'Y Deltoid Fly w/Straps',
                            'shld_rc_level2_dualarm': 'Dual-Arm External Rotation w/Strap ',
                            'shld_rc_level2_field': 'Field Goal w/Strap',
                            'shld_rc_level2_shl_internal': 'Shoulder Internal Rotation at 0 degrees w/RB',
                            'shld_rc_level2_shl_external': 'Shoulder External Rotation at 0 degrees w/RB',
                            'shld_rc_level2_shl_press': 'Shoulder Press w/Resistance Band',
                            'shld_rc_level2_bridhe': 'Bridge with Lateral Raise w/Resistance Band',
                            'shld_rc_level2_shl_front': 'Shoulder Front Raise w/RB',
                            'shld_rc_level2_diagonal': 'Diagonal Flexion w/RB',
                            'shld_rc_level2_rear': 'Rear Deltoid Row w/RB',
                            'shld_rc_level2_upright': 'Upright Row w/RB',
                            'shld_rc_level2_kneeling': 'Kneeling Front Raise w/RB',
                        },
                        'LEVEL3': {
                            'shld_rc_level3_high': 'High Back Row w/Straps',
                            'shld_rc_level3_clock': 'Clock Press w/Strap',
                            'shld_rc_level3_shl_internal': 'Shoulder Internal Rotation at 0 degrees w/RB',
                            'shld_rc_level3_shl_external': 'Shoulder External Rotation at 0 degrees w/RB',
                            'shld_rc_level3_bridge': 'Bridge with Lateral Raise w/Resistance Band',
                        },
                    },
                },
                'BACK': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'back_kl_level1_chinup': 'Chin-Up',
                            'back_kl_level1_assisted': 'Assisted Pull-Up (Bodyweight)',
                            'back_kl_level1_scapular': 'Scapular Pull-Up',
                            'back_kl_level1_inverted': 'Inverted Row with Bar',
                            'back_kl_level1_cobra': 'Cobra',
                            'back_kl_level1_superman': 'Superman',
                            'back_kl_level1_pulldown': 'Alternating Scapular Pull-Down',
                            'back_kl_level1_plank': 'Alternating Plank Row (Renegade)',
                        },
                        'LEVEL2': {
                            'back_kl_level2_pullup': 'Pull-Up (Bodyweight)',
                            'back_kl_level2_chinup': 'Chin-Up',
                            'back_kl_level2_with': 'Pull-Up with Legs Help',
                            'back_kl_level2_assisted': 'Assisted Pull-Up (Bodyweight)',
                            'back_kl_level2_scapular': 'Scapular Pull-Up ',
                            'back_kl_level2_inverted': 'Inverted Row with Bar',
                            'back_kl_level2_lsit': 'L-Sit Pull-Up (Bodyweight)',
                            'back_kl_level2_asymmetric': 'Asymmetric Pull-Up (Bodyweight)',
                            'back_kl_level2_pulldown': 'Alternating Scapular Pull-Down',
                            'back_kl_level2_plank': 'Alternating Plank Row (Renegade)',
                        },
                        'LEVEL3': {
                            'back_kl_level3_pullup': 'Pull-Up (Bodyweight)',
                            'back_kl_level3_jumping': 'Jumping Pull-Up',
                            'back_kl_level3_resisted': 'Resisted Pull Up',
                            'back_kl_level3_scapular': 'Scapular Pull-Up',
                            'back_kl_level3_muscle': 'Muscle-Up',
                            'back_kl_level3_lsit': 'L-Sit Pull-Up (Bodyweight)',
                            'back_kl_level3_asymmetric': 'Asymmetric Pull-Up (Bodyweight)',
                            'back_kl_level3_alternating': 'Alternating Plank Row (Renegade)',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'back_wg_level1_bent': 'Bent Over Row w/Dumbbell',
                            'back_wg_level1_amrbent': 'Single Arm Bent Over Row w/Dumbbell',
                            'back_wg_level1_pullover': 'Pullover w/Dumbbell',
                            'back_wg_level1_bag': 'Single-Arm Bag Row on Bench w/Dumbbell',
                            'back_wg_level1_bench': 'Bench Lying Row w/Barbell & Dumbbell',
                            'back_wg_level1_onearm': 'One-Arm Free Standing Row w/Dumbbell & KB',
                        },
                        'LEVEL2': {
                            'back_wg_level2_barbell': 'Bent Over Row w/Barbell & Kettlebell',
                            'back_wg_level2_dumbbell': 'Bent Over Row w/Dumbbell',
                            'back_wg_level2_pullover': 'Pullover w/Dumbbell',
                            'back_wg_level2_single': 'Single-Arm Bag Row on Bench w/Dumbbell',
                            'back_wg_level2_bench': 'Bench Lying Row w/Barbell & Dumbbell',
                            'back_wg_level2_tbar': 'T-Bar Row',
                            'back_wg_level2_renegade': 'Renegade Row w/Dumbbell & KB',
                            'back_wg_level2_one_sty_up': 'One-Stays-Up Row w/KB',
                            'back_wg_level2_landmine': 'One-Arm Landmine Row',
                            'back_wg_level2_free': 'One-Arm Free Standing Row w/Dumbbell & KB',
                        },
                        'LEVEL3': {
                            'back_wg_level3_bent': 'Bent Over Row w/Barbell & Kettlebell',
                            'back_wg_level3_single': 'Single Leg Bent Over Barbell Row',
                            'back_wg_level3_tbar': 'T-Bar Row',
                            'back_wg_level3_renegade': 'Renegade Row w/Dumbbell & KB',
                            'back_wg_level3_landmine': 'One-Arm Landmine Row',
                            'back_wg_level3_sinle': 'Single Leg One-Arm Landmine Row',
                            'back_wg_level3_bench': 'One-Arm One-Leg Bench Row w/Dumbbell & KB',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'back_mc_level1_std_wide': 'Seated Wide Grip Row w/Cable',
                            'back_mc_level1_lat': 'Lat. Pull-Down w/Machine',
                            'back_mc_level1_close': 'Close Grip Lat. Pull Down w/Cable',
                            'back_mc_level1_reverse': 'Reverse Grip Lat. Pull-Down',
                            'back_mc_level1_mc_pullover': 'Machine Pullover',
                            'back_mc_level1_st_onearm': 'Standing One-Arm Row w/Cable',
                            'back_mc_level1_mc_row': 'Machine Row',
                        },
                        'LEVEL2': {
                            'back_mc_level2_std_wide': 'Seated Wide Grip Row w/Cable',
                            'back_mc_level2_lat': 'Lat. Pull Down w/Cable',
                            'back_mc_level2_leaning': 'Leaning Lat Pull-Down',
                            'back_mc_level2_close': 'Close Grip Lat. Pull Down w/Cable',
                            'back_mc_level2_reverse': 'Reverse Grip Lat. Pull-Down',
                            'back_mc_level2_straight': 'Straight-Arm Lat. Pull-Down w/Cable',
                            'back_mc_level2_standing': 'Standing One-Arm Row w/Cable',
                            'back_mc_level2_onearm': 'One-Arm Cable Row With Hip Rotation',
                            'back_mc_level2_bent': 'Bent-Over One-Arm Cable Row',
                            'back_mc_level2_cable': 'Cable-Rope Tug-of-War Row',
                        },
                        'LEVEL3': {
                            'back_mc_level3_leaning': 'Leaning Lat Pull-Down ',
                            'back_mc_level3_fighter': 'Fighter’s Cable Lat Pull-Down',
                            'back_mc_level3_Straight': 'Straight-Arm Lat. Pull-Down w/Cable',
                            'back_mc_level3_Lunge': 'Lunge Position One-Arm Row w/Cable',
                            'back_mc_level3_Cb_Row': 'One-Arm Cable Row With Hip Rotation',
                            'back_mc_level3_Bent': 'Bent-Over One-Arm Cable Row',
                            'back_mc_level3_Cb_Rope': 'Cable-Rope Tug-of-War Row',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'back_rc_level1_Row': 'Seated Row w/RB',
                            'back_rc_level1_Linton': 'Linton External Rotation w/RB',
                            'back_rc_level1_Bilateral': 'Bilateral Extension With Retraction w/RB',
                            'back_rc_level1_Upright': 'Upright Row w/RB',
                            'back_rc_level1_Supine': 'Supine Pullover w/RB',
                            'back_rc_level1_Shrug': 'Shrug w/RB',
                            'back_rc_level1_Lying': 'Lying Close-Grip Lat Pulldown w/Resistance Band',
                            'back_rc_level1_Single': 'Single Arm Row, on Bench w/Resistance Band',
                            'back_rc_level1_Resistance': 'Seated Row /Resistance Band',
                            'back_rc_level1_Back': 'Back Row w/Resistance Band & Straps',
                            'back_rc_level1_Low': 'Low Row w/Strap',
                            'back_rc_level1_Split': 'Split Fly w/Strap',
                        },
                        'LEVEL2': {
                            'back_rc_level2_Pullup': 'Pull-Up w/Band',
                            'back_rc_level2_Row': 'Seated Row w/RB',
                            'back_rc_level2_Bent': 'Bent-Over Row w/RB',
                            'back_rc_level2_Linton': 'Linton External Rotation w/RB',
                            'back_rc_level2_Bilateral': 'Bilateral Extension With Retraction w/RB',
                            'back_rc_level2_Upright': 'Upright Row w/RB',
                            'back_rc_level2_Supine': 'Supine Pullover w/RB',
                            'back_rc_level2_Standing': 'Standing Reverse Fly w/RB',
                            'back_rc_level2_Close': 'Lying Close-Grip Lat Pulldown w/Resistance Band',
                            'back_rc_level2_Wide': 'Wide-Grip Lat Pulldown w/Resistance Band',
                            'back_rc_level2_Pullover': 'Lying Pullover w/Resistance Band',
                            'back_rc_level2_Sng_Row': 'Single Arm Row, on Bench w/Resistance Band',
                            'back_rc_level2_Resistance': 'Seated Row /Resistance Band',
                            'back_rc_level2_Back': 'Back Row w/Resistance Band & Straps',
                            'back_rc_level2_Single': 'Single Arm, Back Row w/Resistance Band & Straps',
                            'back_rc_level2_Inverted': 'Inverted Row w/Ring ',
                            'back_rc_level2_Battle': 'Battle Ropes, Double Wave',
                            'back_rc_level2_Low': 'Low Row w/Strap',
                            'back_rc_level2_Split': 'Split Fly w/Strap',
                        },
                        'LEVEL3': {
                            'back_rc_level3_Pullup': 'Pull-Up w/Band',
                            'back_rc_level3_Bent': 'Bent-Over Row w/RB',
                            'back_rc_level3_Standing': 'Standing Reverse Fly w/RB',
                            'back_rc_level3_Wide': 'Wide-Grip Lat Pulldown w/Resistance Band',
                            'back_rc_level3_Lying': 'Lying Pullover w/Resistance Band',
                            'back_rc_level3_Single': 'Single Arm, Back Row w/Resistance Band & Straps',
                            'back_rc_level3_Inverted': 'Inverted Row w/Ring ',
                            'back_rc_level3_Battle': 'Battle Ropes, Double Wave',
                        },
                    }, },
                'BISEPS': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'biseps_kl_level1_Curls': 'Biceps Curls (Bodyweight, Chin)',
                            'biseps_kl_level1_With': 'Bridge with Biceps Curls Stability Ball',
                        },
                        'LEVEL2': {
                            'biseps_kl_level2_Curls': 'Biceps Curls (Bodyweight, Chin)',
                            'biseps_kl_level2_With': 'Bridge with Biceps Curls Stability Ball',

                        },
                        'LEVEL3': {
                            'biseps_kl_level3_Curls': 'Biceps Curls (Bodyweight, Chin)',
                            'biseps_kl_level3_With': 'Bridge with Biceps Curls Stability Ball',

                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'biseps_wg_level1_Preacher': 'Preacher Curl w/Dumbbell',
                            'biseps_wg_level1_Dumbbells': 'Dumbbells Concentration Curls',
                            'biseps_wg_level1_Standing': 'Standing Dumbbell Biceps Curl',
                            'biseps_wg_level1_Seated': 'Seated Dumbbell Biceps Curl',
                            'biseps_wg_level1_Hammer': 'Hammer Curls (Dumbbells)',
                            'biseps_wg_level1_Reverse': 'Reverse Curl w/Dumbbell',

                        },
                        'LEVEL2': {
                            'biseps_wg_level2_Preacher': 'Preacher Curl w/Dumbbell',
                            'biseps_wg_level2_Barbell': 'Barbell Wide Grip Biceps Curl',
                            'biseps_wg_level2_Dumbbells': 'Dumbbells Concentration Curls',
                            'biseps_wg_level2_Seated': 'Seated Dumbbell Biceps Curl',
                            'biseps_wg_level2_Incline': 'Incline Bench Biceps Curl w/Dumbells',
                            'biseps_wg_level2_Hammer': 'Hammer Curls (Dumbbells)',
                            'biseps_wg_level2_Wide': 'Wide Grip Biceps Curls w/Flat Barbell & Z Barbell',
                            'biseps_wg_level2_Reverse': 'Reverse Curl w/Dumbbell',
                            'biseps_wg_level2_Biceps': 'Biceps Curl w/KB',
                            'biseps_wg_level2_Close': 'Close Grip Biceps Curl w/Barbell',
                        },
                        'LEVEL3': {
                            'biseps_wg_level3_Barbell': 'Barbell Wide Grip Biceps Curl',
                            'biseps_wg_level3_Incline': 'Incline Bench Biceps Curl w/Dumbbells',
                            'biseps_wg_level3_Hammer': 'Hammer Curls (Dumbbells)',
                            'biseps_wg_level3_Wide': 'Wide Grip Biceps Curls w/Flat Barbell & Z Barbell',
                            'biseps_wg_level3_Reverse': 'Reverse Curl w/Dumbbell',
                            'biseps_wg_level3_Biceps': 'Biceps Curl w/KB',
                            'biseps_wg_level3_Close': 'Close Grip Biceps Curl w/Barbell',

                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'biseps_mc_level1_Preacher': 'Preacher Biceps Curls (Machine)',
                            'biseps_mc_level1_Low': 'Low Pulley Biceps Curl',
                            'biseps_mc_level1_Onearm': 'One-Arm Biceps Curl w/Cable',
                            'biseps_mc_level1_Biceps': 'Biceps Curls(Machine)',
                        },
                        'LEVEL2': {
                            'biseps_mc_level2_Low': 'Low Pulley Biceps Curl',
                            'biseps_mc_level2_Lying': 'Lying Biceps Curl w/Cable',
                            'biseps_mc_level2_Hercules': 'Hercules Biceps Curl w/Cable',
                            'biseps_mc_level2_Onearm': 'One-Arm Biceps Curl w/Cable',
                        },
                        'LEVEL3': {
                            'biseps_mc_level3_Lying': 'Lying Biceps Curl w/Cable',
                            'biseps_mc_level3_Hercules': 'Hercules Biceps Curl w/Cable',
                            'biseps_mc_level3_Cable': 'Cable Biceps Curl w/Rope',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'biseps_rc_level1_Standing': 'Standing Biceps Curl w/Resistance Band',
                            'biseps_rc_level1_High': 'Biceps Curl, High w/Resistance Band',
                            'biseps_rc_level1_Lunge': 'Biceps Curl, Lunge Stance w/ Resistance Band',
                            'biseps_rc_level1_Biceps': 'Biceps Curls w/Straps',
                        },
                        'LEVEL2': {
                            'biseps_rc_level2_Standing': 'Standing Biceps Curl w/Resistance Band',
                            'biseps_rc_level2_High': 'Biceps Curl, High w/ Resistance Band',
                            'biseps_rc_level2_Concentration': 'Concentration Curl w/Resistance Band',
                            'biseps_rc_level2_Lunge': 'Biceps Curl, Lunge Stance w/ Resistance Band',
                            'biseps_rc_level2_Biceps': 'Biceps Curls w/Straps',
                            'biseps_rc_level2_Onearm': 'One-Arm Biceps Curl w/Strap',
                        },
                        'LEVEL3': {
                            'biseps_rc_level3_Biceps': 'Biceps Curl, High w/ Resistance Band',
                            'biseps_rc_level3_Concentration': 'Concentration Curl w/Resistance Band',
                            'biseps_rc_level3_Onearm': 'One-Arm Biceps Curl w/Strap',
                            'biseps_rc_level3_Plank': 'Plank & Push Position Biceps Curl w/RB',
                        },
                    },
                },
                'TRISEPS': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'triseps_kl_level1_Triceps': 'Triceps Dips (Bodyweight)',
                        },
                        'LEVEL2': {
                            'triseps_kl_level2_Kneeling': 'Kneeling Preacher Triceps Extension w/Stability Ball',
                            'triseps_kl_level2_Dips': 'Triceps Dips (Bodyweight)',
                            'triseps_kl_level2_Extension': 'Triceps Extension (Bodyweight)',
                            'triseps_kl_level2_Diamond': 'Diamond Push Up',
                        },
                        'LEVEL3': {
                            'triseps_kl_level3_Kneeling': 'Kneeling Preacher Triceps Extension w/Stability Ball',
                            'triseps_kl_level3_Extension': 'Triceps Extension (Bodyweight)',
                            'triseps_kl_level3_Diamond': 'Diamond Push Up',
                            'triseps_kl_level3_Triceps': 'Triceps Extension Push Up',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'triseps_wg_level1_Dumbbell': 'Dumbbell Triceps Kickback',
                            'triseps_wg_level1_Onearm': 'One-Arm Skull Crusher w/Dumbbell',
                            'triseps_wg_level1_Overhead': 'Overhead Triceps Extension w/Dumbbell',
                        },
                        'LEVEL2': {
                            'triseps_wg_level2_Dumbbell': 'Dumbbell Triceps Kickback',
                            'triseps_wg_level2_ly_Dumbbell': 'Lying Triceps Extension w/Dumbbell',
                            'triseps_wg_level2_ly_Barbell': 'Lying Triceps Extension w/Barbell',
                            'triseps_wg_level2_Skull': 'Skull Crusher w/Zbar',
                            'triseps_wg_level2_Onearm': 'One-Arm Skull Crusher w/Dumbbell',
                            'triseps_wg_level2_Overhead': 'Overhead Triceps Extension w/Dumbbell',
                            'triseps_wg_level2_Barbell': 'Barbell Close Grip Bench Press',
                        },
                        'LEVEL3': {
                            'triseps_wg_level3_ly_Dumbbell': 'Lying Triceps Extension w/Dumbbell',
                            'triseps_wg_level3_ly_Barbell': 'Lying Triceps Extension w/Barbell',
                            'triseps_wg_level3_Skull': 'Skull Crusher w/Zbar',
                            'triseps_wg_level3_Barbell': 'Barbell Close Grip Bench Press',
                            'triseps_wg_level3_Bent': 'Bent Over Triceps Kickback w/Dumbbell',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'triseps_mc_level1_Pushdowns': 'Triceps Pushdowns w/Cable',
                            'triseps_mc_level1_Triceps': 'Triceps Push-Down w/Rope',
                            'triseps_mc_level1_Reverse': 'Reverse Grip Triceps Push Down w/Cable',
                            'triseps_mc_level1_Onearm': 'One-Arm Triceps Push-Down w/Cable',
                            'triseps_mc_level1_Cable': 'Cable Triceps Kickback',
                            'triseps_mc_level1_Machine': 'Triceps Pushdowns w/Machine',
                            'triseps_mc_level1_Press': 'Triceps Press w/Machine',
                        },
                        'LEVEL2': {
                            'triseps_mc_level2_Pushdowns': 'Triceps Push-downs w/Cable',
                            'triseps_mc_level2_Triceps': 'Triceps Push-Down w/Rope',
                            'triseps_mc_level2_Reverse': 'Reverse Grip Triceps Push-Down w/Cable',
                            'triseps_mc_level2_Overhead': 'Overhead Triceps Push-Down w/Rope',
                            'triseps_mc_level2_Onearm': 'One-Arm Triceps Push-Down w/Cable',
                            'triseps_mc_level2_Grip': 'Reverse Grip One-Arm Triceps Push-Down w/Cable',
                            'triseps_mc_level2_Cable': 'Cable Triceps Kickback',
                            'triseps_mc_level2_Dips': 'Dips Triceps w/Machine',
                            'triseps_mc_level2_tr_Pushdowns': 'Triceps Push-Downs w/Machine',
                            'triseps_mc_level2_tr_Press': 'Triceps Press w/Machine',
                        },
                        'LEVEL3': {
                            'triseps_mc_level3_Overhead': 'Overhead Triceps Push-Down W/Rope',
                            'triseps_mc_level3_Reverse': 'Reverse Grip One-Arm Triceps Push-Down w/Cable',
                            'triseps_mc_level3_Dips': 'Dips Triceps w/Machine',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'triseps_rc_level1_ex_Overhead': 'Triceps Extension-Overhead w/Resistance Band',
                            'triseps_rc_level1_Lying': 'Lying Triceps Extension w/Resistance Band',
                            'triseps_rc_level1_ex': 'Triceps Extension w/Resistance Band',
                            'triseps_rc_level1_Standing': 'Standing Skull Crusher w/Strap',
                        },
                        'LEVEL2': {
                            'triseps_rc_level2_ex_Overhead': 'Triceps Extension-Overhead w/Resistance Band',
                            'triseps_rc_level2_Lying': 'Lying Triceps Extension w/Resistance Band',
                            'triseps_rc_level2_ex': 'Triceps Extension w/Resistance Band',
                            'triseps_rc_level2_Kickback': 'Triceps Kickback w/Resistance Band',
                            'triseps_rc_level2_sd_Overhead': 'Standing Overhead Triceps Extension',
                            'triseps_rc_level2_sd_Skull': 'Standing Skull Crusher w/Strap',
                            'triseps_rc_level2_kn_Skull': 'Kneeling Skull Crusher w/Strap',
                            'triseps_rc_level2_kn_Overhead': 'Kneeling Overhead Triceps Extension w/Strap',
                            'triseps_rc_level2_Dips': 'Dips w/RB',
                        },
                        'LEVEL3': {
                            'triseps_rc_level3_Kickback': 'Triceps Kickback w/Resistance Band',
                            'triseps_rc_level3_sd_Overhead': 'Standing Overhead Triceps Extension',
                            'triseps_rc_level3_kn_Skull': 'Kneeling Skull Crusher w/Strap',
                            'triseps_rc_level3_kn_Overhead': 'Kneeling Overhead Triceps Extension w/Strap',
                            'triseps_rc_level3_Dips': 'Dips w/RB',
                        },
                    },
                },
                'GLUTEAL': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'gluteal_kl_level1_Side': 'Side Lunge',
                            'gluteal_kl_level1_Hip': 'Hip Thrust w/Bosu Ball',
                            'gluteal_kl_level1_Roman': 'Roman Chair Hip Extension',
                            'gluteal_kl_level1_Glute': 'Glute Bridge',
                        },
                        'LEVEL2': {
                            'gluteal_kl_level2_Full': 'Full Squat w/Bodyweight',
                            'gluteal_kl_level2_Side': 'Side Lunge',
                            'gluteal_kl_level2_Hip': 'Hip Thrust w/Bosu Ball',
                            'gluteal_kl_level2_sngl_Hip': 'Single Leg Hip Thrust',
                            'gluteal_kl_level2_Split': 'Split Squat',
                            'gluteal_kl_level2_Bulgarian': 'Bulgarian Squat',
                            'gluteal_kl_level2_Hack': 'Hack Squat ',
                            'gluteal_kl_level2_Roman': 'Roman Chair Hip Extension',
                            'gluteal_kl_level2_sngl_Leg': 'Single Leg Glute Bridge',
                        },
                        'LEVEL3': {
                            'gluteal_kl_level3_Single': 'Single Leg Hip Thrust',
                            'gluteal_kl_level3_Split': 'Split Squat',
                            'gluteal_kl_level3_Bulgarian': 'Bulgarian Squat',
                            'gluteal_kl_level3_Hack': 'Hack Squat ',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'gluteal_wg_level1_Hip': 'Hip Thrust on Bench w/Barbell',
                            'gluteal_wg_level1_Glute': 'Glute Bridge w/Barbell',
                            'gluteal_wg_level1_db_Squat': 'Dumbbell Squat',
                            'gluteal_wg_level1_Goblet': 'Goblet Squat w/Dumbbell & KB',
                            'gluteal_wg_level1_Narrow': 'Narrow Squat w/Dumbbell',
                            'gluteal_wg_level1_db_Single': 'Dumbbell Single Arm Overhead Squat',
                            'gluteal_wg_level1_Wide': 'Wide Squat (Smith Machine)',
                            'gluteal_wg_level1_Sumo': 'Sumo Squat (Dumbbell & Barbell)',
                        },
                        'LEVEL2': {
                            'gluteal_wg_level2_Hip': 'Hip Thrust on Bench w/Barbell',
                            'gluteal_wg_level2_Glute': 'Glute Bridge w/Barbell',
                            'gluteal_wg_level2_Squat': 'Squat-Side, Split w/Barbell',
                            'gluteal_wg_level2_db_Squat': 'Dumbbell Squat',
                            'gluteal_wg_level2_Full': 'Full Squat w/Barbell',
                            'gluteal_wg_level2_Front': 'Front Squat w/Barbell',
                            'gluteal_wg_level2_Goblet': 'Goblet Squat w/Dumbbell & KB',
                            'gluteal_wg_level2_Narrow': 'Narrow Squat w/Dumbbell',
                            'gluteal_wg_level2_br_Squat': 'Barbell Squat Jump',
                            'gluteal_wg_level2_br_Overhead': 'Barbell Overhead Squat',
                            'gluteal_wg_level2_br_Single': 'Dumbbell Single Arm Overhead Squat',
                            'gluteal_wg_level2_Wide': 'Wide Squat (Smith Machine)',
                            'gluteal_wg_level2_on_Squat': 'One-Leg Squat (Bulgarian) w/Dumbbell',
                            'gluteal_wg_level2_on_Jump': 'One-Leg Jump Squat (Dumbbell)',
                            'gluteal_wg_level2_Close': 'Close Squat w/Barbell & Dumbbell',
                            'gluteal_wg_level2_Sumo': 'Sumo Squat (Dumbbell & Barbell)',
                            'gluteal_wg_level2_Barbell': 'Barbell Jump Lunge',
                        },
                        'LEVEL3': {
                            'gluteal_wg_level3_Squat': 'Squat-Side, Split w/Barbell',
                            'gluteal_wg_level3_Full': 'Full Squat w/Barbell',
                            'gluteal_wg_level3_Front': 'Front Squat w/Barbell',
                            'gluteal_wg_level3_br_Squat': 'Barbell Squat Jump',
                            'gluteal_wg_level3_br_Overhead': 'Barbell Overhead Squat',
                            'gluteal_wg_level3_Jump': 'One-Leg Jump Squat (Dumbbell)',
                            'gluteal_wg_level3_Close': 'Close Squat w/Barbell & Dumbbell',
                            'gluteal_wg_level3_Barbell': 'Barbell Jump Lunge',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'gluteal_mc_level1_Machine': 'Machine Hip Extension',
                            'gluteal_mc_level1_Squat': 'Squat w/Smith Machine',
                        },
                        'LEVEL2': {
                            'gluteal_mc_level2_Machine': 'Machine Hip Extension',
                            'gluteal_mc_level2_Squat': 'Squat w/Smith Machine',
                        },
                        'LEVEL3': {
                            'gluteal_mc_level3_Machine': 'Machine Hip Extension',
                            'gluteal_mc_level3_Squat': 'Squat w/Smith Machine',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'gluteal_rc_level1_Internal': 'Hip Internal Rotation w/RB',
                            'gluteal_rc_level1_External': 'Hip External Rotation w/RB',
                            'gluteal_rc_level1_Fleksiyon': 'Hip Flexion w/RB',
                            'gluteal_rc_level1_Ekstension': 'Hip Extension w/RB',
                            'gluteal_rc_level1_Abduction': 'Hip Abduction w/RB',
                            'gluteal_rc_level1_Adduction': 'Hip Adduction w/RB',
                            'gluteal_rc_level1_Half': 'Half Squat w/RB',
                            'gluteal_rc_level1_Bridge': 'Bridge w/RB',
                            'gluteal_rc_level1_Barbell': 'Barbell Squat w/RB',
                            'gluteal_rc_level1_Monster': 'Monster Walk w/RB',
                        },
                        'LEVEL2': {
                            'gluteal_rc_level2_Half': 'Half Squat w/RB',
                            'gluteal_rc_level2_Side': 'Side-Lying Hip Lift w/RB',
                            'gluteal_rc_level2_Bridge': 'Bridge w/RB',
                            'gluteal_rc_level2_Hip': 'Hip Extension (Donkey Kick) w/RB',
                            'gluteal_rc_level2_gd_Morning': 'Good Morning w/RB',
                            'gluteal_rc_level2_Supine': 'Supine Hip-Bridge March With Mini Band',
                            'gluteal_rc_level2_Lunge': 'Lunge w/RB',
                            'gluteal_rc_level2_lt_Lunge': 'Lateral Lunge w/RB',
                            'gluteal_rc_level2_Barbell': 'Barbell Squat w/RB',
                            'gluteal_rc_level2_Monster': 'Monster Walk w/RB',
                            'gluteal_rc_level2_lt_Squat': 'Lateral Squat w/Strap',
                            'gluteal_rc_level2_Bulgarian': 'Bulgarian Squat w/Strap',
                            'gluteal_rc_level2_Triangle': 'Triangle Squat w/Strap',
                            'gluteal_rc_level2_Full': 'Full Squat w/Strap',
                            'gluteal_rc_level2_Overhead': 'Overhead Squat w/Strap',
                        },
                        'LEVEL3': {
                            'gluteal_rc_level3_gd_Morning': 'Good Morning w/RB',
                            'gluteal_rc_level3_Supine': 'Supine Hip-Bridge March With Mini Band',
                            'gluteal_rc_level3_lt_Lunge': 'Lateral Lunge w/RB',
                            'gluteal_rc_level3_lt_Squat': 'Lateral Squat w/Strap',
                            'gluteal_rc_level3_Barbell': 'Barbell Squat w/RB',
                            'gluteal_rc_level3_Bulgarian': 'Bulgarian Squat w/Strap',
                            'gluteal_rc_level3_Triangle': 'Triangle Squat w/Strap',
                            'gluteal_rc_level3_Figure': 'Figure Four Squat w/Strap',
                            'gluteal_rc_level3_Squat': 'Squat Jump w/Strap',
                            'gluteal_rc_level3_Full': 'Full Squat w/Strap',
                            'gluteal_rc_level3_Overhead': 'Overhead Squat w/Strap',
                        },
                    },
                },
                'KUADRISEPS': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'kdrsps_kl_level1_Sissy': 'Sissy Squat',
                            'kdrsps_kl_level1_Hell': 'Hell Elevated Squat',
                            'kdrsps_kl_level1_Narrow': 'Narrow Squat',
                        },
                        'LEVEL2': {
                            'kdrsps_kl_level2_Elevated': 'Elevated Front Foot Split Squat',
                            'kdrsps_kl_level2_Sissy': 'Sissy Squat',
                            'kdrsps_kl_level2_Hell': 'Hell Elevated Squat',
                            'kdrsps_kl_level2_Narrow': 'Narrow Squat',
                        },
                        'LEVEL3': {
                            'kdrsps_kl_level3_Pistol': 'Pistol Squat',
                            'kdrsps_kl_level3_Elevated': 'Elevated Front Foot Split Squat',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'kdrsps_wg_level1_Goblet': 'Goblet Squat w/Dumbbell & KB',
                            'kdrsps_wg_level1_Stand': 'Stand-Up (From Knees)',
                            'kdrsps_wg_level1_Squat': 'Squat Plie w/Dumbbell',
                            'kdrsps_wg_level1_Narrow': 'Narrow Squat w/Barbell & Dumbbell',
                            'kdrsps_wg_level1_Front': 'Front Lunge w/Barbell & Dumbbell',
                            'kdrsps_wg_level1_Hell': 'Hell Elevated Squat w/Dumbbell',
                        },
                        'LEVEL2': {
                            'kdrsps_wg_level2_stp_Dumbbell': 'Step-Up w/Dumbbell',
                            'kdrsps_wg_level2_frnt_Squat': 'Front Squat w/Barbell',
                            'kdrsps_wg_level2_Goblet': 'Goblet Squat w/Dumbbell & KB',
                            'kdrsps_wg_level2_stp_Barbell': 'Step-up w/Barbell',
                            'kdrsps_wg_level2_Stand': 'Stand-Up (From Knees)',
                            'kdrsps_wg_level2_Squat': 'Squat Plie w/Dumbbell',
                            'kdrsps_wg_level2_Double': 'Double Squat w/Dumbbell',
                            'kdrsps_wg_level2_Narrow': 'Narrow Squat w/Barbell & Dumbbell',
                            'kdrsps_wg_level2_frnt_Lunge': 'Front Lunge w/Barbell & Dumbbell',
                            'kdrsps_wg_level2_Hell': 'Hell Elevated Squat w/Dumbbell',
                            'kdrsps_wg_level2_Elevated': 'Elevated Front Foot Split Squat w/Dumbbell',
                        },
                        'LEVEL3': {
                            'kdrsps_wg_level3_stp_Dumbbell': 'Step-Up w/Dumbbell',
                            'kdrsps_wg_level3_Front': 'Front Squat w/Barbell',
                            'kdrsps_wg_level3_stp_Barbell': 'Step-up w/Barbell',
                            'kdrsps_wg_level3_Sissy': 'Sissy Squat w/Plate',
                            'kdrsps_wg_level3_Double': 'Double Squat w/Dumbbell',
                            'kdrsps_wg_level3_Narrow': 'Narrow Squat w/Barbell & Dumbbell',
                            'kdrsps_wg_level3_Elevated': 'Elevated Front Foot Split Squat w/Dumbbell',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'kdrsps_mc_level1_Extension': 'Leg Extension w/Machine',
                            'kdrsps_mc_level1_Press': 'Leg Press w/Machine',
                            'kdrsps_mc_level1_Smith': 'Smith Machine Duck Stance',
                        },
                        'LEVEL2': {
                            'kdrsps_mc_level2_Leg': 'Leg Extension w/Machine',
                            'kdrsps_mc_level2_onlg_Extension': 'One-Leg Extension w/Machine',
                            'kdrsps_mc_level2_Press': 'Leg Press w/Machine',
                            'kdrsps_mc_level2_onlg_Press': 'One-Leg Press w/Machine',
                            'kdrsps_mc_level2_Smith': 'Smith Machine Duck Stance',
                        },
                        'LEVEL3': {
                            'kdrsps_mc_level3_onlg_Extension': 'One-Leg Extension w/Machine',
                            'kdrsps_mc_level3_onlg_Press': 'One-Leg Press w/Machine',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'kdrsps_rc_level1_Strap': 'Knee Extension w/Strap ',
                            'kdrsps_rc_level1_RB': 'Knee Extension w/RB',
                            'kdrsps_rc_level1_Leg': 'Leg Press w/RB',
                        },
                        'LEVEL2': {
                            'kdrsps_rc_level2_Pistol': 'Pistol Squat w/Strap',
                            'kdrsps_rc_level2_Hack': 'Hack Squat w/RB',
                            'kdrsps_rc_level2_Strap': 'Knee Extension w/Strap ',
                            'kdrsps_rc_level2_Single': 'Single-Leg Suspended Knee Extension w/Strap',
                            'kdrsps_rc_level2_RB': 'Knee Extension w/RB',
                            'kdrsps_rc_level2_Leg': 'Leg Press w/RB',
                        },
                        'LEVEL3': {
                            'kdrsps_rc_level3_Pistol': 'Pistol Squat w/Strap',
                            'kdrsps_rc_level3_Single': 'Single-Leg Suspended Knee Extension w/Strap',
                            'kdrsps_rc_level3_Leg': 'Leg Press w/RB',
                        },
                    },
                },
                'HAMSTRING': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'hmstrng_kl_level1_Hinge': 'Hip-Hinge',
                            'hmstrng_kl_level1_Thrust': 'Hip Thrust on Heel w/Bosu-Ball',
                            'hmstrng_kl_level1_Stability': 'Stability-Ball Leg Curl',
                            'hmstrng_kl_level1_Glute': 'Glute-Ham Roller Leg Curl',
                        },
                        'LEVEL2': {
                            'hmstrng_kl_level2_Single': 'Single Leg Deadlift',
                            'hmstrng_kl_level2_Hip': 'Hip Thrust on Heel w/Bosu-Ball',
                            'hmstrng_kl_level2_Nordic': 'Nordic Hamstring Curl',
                            'hmstrng_kl_level2_Stability': 'Stability-Ball Leg Curl',
                            'hmstrng_kl_level2_Oneleg': 'One-Leg Stability-Ball Leg Curl',
                            'hmstrng_kl_level2_Glute': 'Glute-Ham Roller Leg Curl',
                        },
                        'LEVEL3': {
                            'hmstrng_kl_level3_Single': 'Single Leg Deadlift',
                            'hmstrng_kl_level3_Nordic': 'Nordic Hamstring Curl',
                            'hmstrng_kl_level3_Stability': 'Stability-Ball Leg Curl',
                            'hmstrng_kl_level3_Oneleg': 'One-Leg Stability-Ball Leg Curl',
                            'hmstrng_kl_level3_Glute': 'Glute-Ham Roller Leg Curl',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'hmstrng_wg_level1_Rear': 'Rear Lunge w/Dumbbell & KB',
                            'hmstrng_wg_level1_Hip': 'Hip Thrust on Heel w/Dumbbell & KB',
                            'hmstrng_wg_level1_Dumbbell': 'Dumbbell Rotational Lunge',
                            'hmstrng_wg_level1_Side': 'Side Lunge w/Dumbbell',
                            'hmstrng_wg_level1_Pivot': 'Pivot Lunge w/Dumbbell',
                        },
                        'LEVEL2': {
                            'hmstrng_wg_level2_Rear': 'Rear Lunge w/Dumbbell & KB',
                            'hmstrng_wg_level2_Hip': 'Hip Thrust on Heel w/Dumbbell & KB',
                            'hmstrng_wg_level2_Good': 'Good Morning, Bent Legs w/Barbell',
                            'hmstrng_wg_level2_Romanian': 'Romanian Deadlift w/Barbell',
                            'hmstrng_wg_level2_Deadlift': 'Deadlift w/Barbell & Dumbbell',
                            'hmstrng_wg_level2_Single': 'Single Leg Deadlift w/KB',
                            'hmstrng_wg_level2_Dumbbell': 'Dumbbell Rotational Lunge',
                            'hmstrng_wg_level2_Arc': 'Arc Lunge w/Dumbbell',
                            'hmstrng_wg_level2_sd_Dumbbell': 'Side Lunge w/Dumbbell',
                            'hmstrng_wg_level2_sd_Barbell': 'Side Lunge w/Barbell',
                            'hmstrng_wg_level2_Pivot': 'Pivot Lunge w/Dumbbell',
                            'hmstrng_wg_level2_Straight': 'Straight-Leg Deadlift w/Dumbbell',
                            'hmstrng_wg_level2_Oneleg': 'One-Leg One-Arm Angled Barbell Romanian Deadlift',
                            'hmstrng_wg_level2_Angled': 'Angled Barbell Cross-Shoulder Reverse Lunge',
                        },
                        'LEVEL3': {
                            'hmstrng_wg_level3_Good': 'Good Morning, Bent Legs w/Barbell',
                            'hmstrng_wg_level3_Romanian': 'Romanian Deadlift w/Barbell',
                            'hmstrng_wg_level3_Deadlift': 'Deadlift w/Barbell & Dumbbell',
                            'hmstrng_wg_level3_Single': 'Single Leg Deadlift w/KB',
                            'hmstrng_wg_level3_Arc': 'Arc Lunge w/Dumbbell',
                            'hmstrng_wg_level3_Side': 'Side Lunge w/Barbell',
                            'hmstrng_wg_level3_Straight': 'Straight-Leg Deadlift w/Dumbbell',
                            'hmstrng_wg_level3_Oneleg': 'One-Leg One-Arm Angled Barbell Romanian Deadlift',
                            'hmstrng_wg_level3_Angled': 'Angled Barbell Cross-Shoulder Reverse Lunge',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'hmstrng_mc_level1_Leg': 'Leg Curl w/Machine',
                        },
                        'LEVEL2': {
                            'hmstrng_mc_level2_Reverse': 'Reverse Lunge w/Smith Machine',
                            'hmstrng_mc_level2_Leg': 'Leg Curl w/Machine',
                        },
                        'LEVEL3': {
                            'hmstrng_mc_level3_Reverse': 'Reverse Lunge w/Smith Machine',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'hmstrng_rc_level1_Hip': 'Hip Thrust on Heel w/RB',
                            'hmstrng_rc_level1_Reverse': 'Reverse Lunge w/Strap',
                            'hmstrng_rc_level1_Lying': 'Lying Leg Curl w/Strap',
                            'hmstrng_rc_level1_Knee': 'Knee Flexion w/RB',
                            'hmstrng_rc_level1_Bird': 'Bird Dog Leg Curl w/RB',
                        },
                        'LEVEL2': {
                            'hmstrng_rc_level2_hp_Strap': 'Hip Thrust on Heel w/Strap',
                            'hmstrng_rc_level2_hp_RB': 'Hip Thrust on Heel w/RB',
                            'hmstrng_rc_level2_sngl_Reaching': 'Single-Leg Reaching Romanian Deadlift w/Strap',
                            'hmstrng_rc_level2_Reverse': 'Reverse Lunge With Knee Drive w/Strap',
                            'hmstrng_rc_level2_Lying': 'Lying Leg Curl w/Strap',
                            'hmstrng_rc_level2_sngl_Lying': 'Single-Leg Lying Leg Curl w/Strap',
                            'hmstrng_rc_level2_Knee': 'Knee Flexion w/RB',
                            'hmstrng_rc_level2_Bird': 'Bird Dog Leg Curl w/RB',

                        },
                        'LEVEL3': {
                            'hmstrng_rc_level3_Hip': 'Hip Thrust on Heel w/Strap',
                            'hmstrng_rc_level3_sngl_Reaching': 'Single-Leg Reaching Romanian Deadlift w/Strap',
                            'hmstrng_rc_level3_Reverse': 'Reverse Lunge With Knee Drive w/Strap',
                            'hmstrng_rc_level3_sngl_Lying': 'Single-Leg Lying Leg Curl w/Strap',
                            'hmstrng_rc_level3_Push': 'Push Position Leg Curl w/RB',

                        },
                    },
                },
                'GASTROCNEMIUS': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'gstr_kl_level1_Seated': 'Seated Calf Raise',
                            'gstr_kl_level1_Standing': 'Standing Calf Raise',
                        },
                        'LEVEL2': {
                            'gstr_kl_level2_Seated': 'Seated Calf Raise',
                            'gstr_kl_level2_Standing': 'Standing Calf Raise',
                            'gstr_kl_level2_Donkey': 'Donkey Raise',
                        },
                        'LEVEL3': {
                            'gstr_kl_level3_Seated': 'Seated Calf Raise',
                            'gstr_kl_level3_Standing': 'Standing Calf Raise',
                            'gstr_kl_level3_Donkey': 'Donkey Raise',
                        },
                    },
                    'WEIGHT': {
                        'LEVEL1': {
                            'gstr_wg_level1_Seated': 'Seated Calf Raise w/Dumbbell & KB',
                            'gstr_wg_level1_Toe': 'Toe Raise w/Dumbbell',
                            'gstr_wg_level1_Dumbbell': 'Dumbbell Heel Raise w/Dumbbell',
                        },
                        'LEVEL2': {
                            'gstr_wg_level2_Barbell': 'Barbell Calf Raise',
                            'gstr_wg_level2_Toe': 'Toe Raise w/Dumbbell',
                            'gstr_wg_level2_Dumbbell': 'Dumbbell Heel Raise w/Dumbbell',
                        },
                        'LEVEL3': {
                            'gstr_wg_level3_Barbell': 'Barbell Calf Raise',
                            'gstr_wg_level3_Toe': 'Toe Raise w/Dumbbell',
                            'gstr_wg_level3_Dumbbell': 'Dumbbell Heel Raise w/Dumbbell',
                        },
                    },
                    'MACHINE': {
                        'LEVEL1': {
                            'gstr_mc_level1_Calf': 'Calf Raise (Machine)',
                        },
                        'LEVEL2': {
                            'gstr_mc_level2_Standing': 'Standing Calf Raise (Smith Machine)',
                        },
                        'LEVEL3': {
                            'gstr_mc_level3_Standing': 'Standing Calf Raise (Smith Machine)',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'gstr_rc_level1_Standing': 'Standing Calf Raise w/Strap',
                            'gstr_rc_level1_Dorsiflexion': 'Seated Dorsiflexion w/RB',
                            'gstr_rc_level1_Plantar': 'Seated Plantar Flexion w/RB',
                            'gstr_rc_level1_Inversion': 'Ankle Inversion w/RB',
                            'gstr_rc_level1_Eversion': 'Ankle Eversion w/RB',
                        },
                        'LEVEL2': {
                            'gstr_rc_level2_Single': 'Single Leg Calf Raise w/Strap',
                            'gstr_rc_level2_Dorsiflexion': 'Seated Dorsiflexion w/RB',
                            'gstr_rc_level2_Plantar': 'Seated Plantar Flexion w/RB',
                            'gstr_rc_level2_Inversion': 'Ankle Inversion w/RB',
                            'gstr_rc_level2_Eversion': 'Ankle Eversion w/RB',
                        },
                        'LEVEL3': {
                            'gstr_rc_level3_Dorsiflexion': 'Seated Dorsiflexion w/RB',
                            'gstr_rc_level3_Plantar': 'Seated Plantar Flexion w/RB',
                            'gstr_rc_level3_Inversion': 'Ankle Inversion w/RB',
                            'gstr_rc_level3_Single': 'Single Leg Calf Raise w/Strap',
                            'gstr_rc_level3_Eversion': 'Ankle Eversion w/RB',
                        },
                    },
                },
                'CORE': {
                    'KALISTENIK': {
                        'LEVEL1': {
                            'core_kl_level1_Reverse': 'Reverse Crunch ',
                            'core_kl_level1_Bird': 'Bird Dog',
                            'core_kl_level1_Stability': 'Stability Ball Crunch',
                            'core_kl_level1_Russian': 'Russian Twist',
                            'core_kl_level1_Dumbbell': 'Dumbbell Side Bend',
                            'core_kl_level1_Swimmer': 'Swimmer',
                            'core_kl_level1_Superman': 'Superman',
                            'core_kl_level1_Leg': 'Leg Lower',
                            'core_kl_level1_Dead': 'Dead Bug',
                            'core_kl_level1_Back': 'Back Extension/Hyperextension',
                            'core_kl_level1_Sit': 'Sit-Up',
                            'core_kl_level1_Bully': 'Bully w/Medicine Ball',
                            'core_kl_level1_Flutter': 'Flutter Kick',
                            'core_kl_level1_Scissor': 'Scissor Flutter Kick',
                            'core_kl_level1_Medicine': 'Medicine Ball Seated Twist',
                            'core_kl_level1_Kneeling': 'Cable Kneeling Rope Crunch',
                            'core_kl_level1_Side': 'Cable Side Bend ',
                            'core_kl_level1_Torso': 'Cable Torso Rotation',
                            'core_kl_level1_Diagonal': 'Diagonal Plate Chop',
                            'core_kl_level1_Plate': 'Plate V-Up',

                        },
                        'LEVEL2': {
                            'core_kl_level2_Bicycle': 'Bicycle Crunch',
                            'core_kl_level2_Crunch': 'Reverse Crunch ',
                            'core_kl_level2_Pendulum': 'Reverse Pendulum ',
                            'core_kl_level2_Plank': 'Prone Plank',
                            'core_kl_level2_Prone': 'Prone Plank With Hip Extension',
                            'core_kl_level2_Hyperextension': 'Stability Ball Hyperextension',
                            'core_kl_level2_std_Ball': 'Stability Ball Crunch',
                            'core_kl_level2_Side': 'Stability Ball Side Crunch',
                            'core_kl_level2_Rotating': 'Stability Ball Rotating Crunch',
                            'core_kl_level2_Supine': 'Stability Ball Supine Bridge',
                            'core_kl_level2_sd_Double': 'Side Double-Leg Lift',
                            'core_kl_level2_Leg': 'Leg Lower',
                            'core_kl_level2_Dead': 'Dead Bug',
                            'core_kl_level2_Back': 'Back Extension/Hyperextension',
                            'core_kl_level2_Sit': 'Sit-Up',
                            'core_kl_level2_Angled': 'Angled Barbell Rotation',
                            'core_kl_level2_Bully': 'Bully w/Medicine Ball',
                            'core_kl_level2_Flutter': 'Flutter Kick',
                            'core_kl_level2_Hanging': 'Hanging Knee Raise',
                            'core_kl_level2_Three': 'Three-Way Hanging Knee Raise',
                            'core_kl_level2_Scissor': 'Scissor Flutter Kick',
                            'core_kl_level2_Mountain': 'Mountain Climber',
                            'core_kl_level2_Pullover': 'Medicine Ball Pullover Pass',
                            'core_kl_level2_Rotational': 'Medicine Ball Rotational Throw',
                            'core_kl_level2_Twist': 'Medicine Ball Seated Twist',
                            'core_kl_level2_Resistance': 'Resistance Band Forward, Backward, or Sideward Walkout',
                            'core_kl_level2_Rope': 'Cable Kneeling Rope Crunch',
                            'core_kl_level2_Twisting': 'Cable Kneeling Twisting Rope Crunch',
                            'core_kl_level2_Bend': 'Cable Side Bend ',
                            'core_kl_level2_LH': 'Cable Low/High Woodchop',
                            'core_kl_level2_HL': 'Cable High/Low Woodchop',
                            'core_kl_level2_Torso': 'Cable Torso Rotation',
                            'core_kl_level2_Double': 'Side Double-Leg Lift',
                            'core_kl_level2_Diagonal': 'Diagonal Plate Chop',
                            'core_kl_level2_Plate': 'Plate V-Up',
                        },
                        'LEVEL3': {
                            'core_kl_level3_Bicycle': 'Bicycle Crunch',
                            'core_kl_level3_Reverse': 'Reverse Pendulum ',
                            'core_kl_level3_pr_Plank': 'Prone Plank',
                            'core_kl_level3_st_Plank': 'Stability Ball Plank to Pike-Up',
                            'core_kl_level3_Prone': 'Prone Plank With Hip Extension',
                            'core_kl_level3_Bridge': 'Side Bridge/Side Plank',
                            'core_kl_level3_Hyperextension': 'Stability Ball Hyperextension',
                            'core_kl_level3_Crunch': 'Stability Ball Side Crunch',
                            'core_kl_level3_Rotating': 'Stability Ball Rotating Crunch',
                            'core_kl_level3_Supine': 'Stability Ball Supine Bridge',
                            'core_kl_level3_Barbell': 'Barbell Rollout',
                            'core_kl_level3_Lift': 'Side Double-Leg Lift',
                            'core_kl_level3_Jackknife': 'Jackknife',
                            'core_kl_level3_Rotation': 'Angled Barbell Rotation',
                            'core_kl_level3_Hanging': 'Hanging Knee Raise',
                            'core_kl_level3_Three': 'Three-Way Hanging Knee Raise',
                            'core_kl_level3_Mountain': 'Mountain Climber',
                            'core_kl_level3_Medicine': 'Medicine Ball Rotational Throw',
                            'core_kl_level3_Rollout': 'Rollout',
                            'core_kl_level3_Kneeling': 'Cable Kneeling Twisting Rope Crunch',
                            'core_kl_level3_Lh': 'Cable Low/High Woodchop',
                            'core_kl_level3_HL': 'Cable High/Low Woodchop',
                        },
                    },
                    'STRAP': {
                        'LEVEL1': {
                            'core_st_level1_Glute': 'Glute Bridge w/Strap',
                            'core_st_level1_Extended': 'Extended-Arm Plank w/Strap',
                            'core_st_level1_Bicycle': 'Bicycle Crunch w/Strap',
                            'core_st_level1_Kneeling': 'Kneeling Rollout w/Strap',
                            'core_st_level1_Lateral': 'Standing Lateral Twist w/Strap',
                            'core_st_level1_Oblique': 'Standing Oblique Crunch w/Strap',
                            'core_st_level1_Rollout': 'Standing Rollout w/Strap ',
                        },
                        'LEVEL2': {
                            'core_st_level2_Glute': 'Glute Bridge w/Strap',
                            'core_st_level2_Elbow': 'Elbow Plank w/Strap',
                            'core_st_level2_Supine': 'Supine Plank w/Strap',
                            'core_st_level2_Single': 'Single-Leg Plank w/Strap',
                            'core_st_level2_ex_Plank': 'Extended-Arm Plank w/Strap',
                            'core_st_level2_Side': 'Side Plank w/Strap',
                            'core_st_level2_Rotational': 'Rotational Side Plank w/Strap',
                            'core_st_level2_Palov': 'Pallof Press w/Strap',
                            'core_st_level2_Bicycle': 'Bicycle Crunch w/Strap',
                            'core_st_level2_Kneeling': 'Kneeling Rollout w/Strap',
                            'core_st_level2_st_Lateral': 'Standing Lateral Twist w/Strap',
                            'core_st_level2_Power': 'Power Pull w/Strap',
                            'core_st_level2_st_Oblique': 'Standing Oblique Crunch w/Strap',
                            'core_st_level2_ex_Side': 'Extended-Arm Side Plank w/Strap',
                        },
                        'LEVEL3': {
                            'core_st_level3_Elbow': 'Elbow Plank w/Strap',
                            'core_st_level3_Supine': 'Supine Plank w/Strap',
                            'core_st_level3_Single': 'Single-Leg Plank w/Strap',
                            'core_st_level3_Side': 'Side Plank w/Strap',
                            'core_st_level3_Rotational': 'Rotational Side Plank w/Strap',
                            'core_st_level3_Palov': 'Pallof Press w/Strap',
                            'core_st_level3_Power': 'Power Pull w/Strap',
                            'core_st_level3_Extended': 'Extended-Arm Side Plank w/Strap',
                            'core_st_level3_Standing': 'Standing Rollout w/Strap ',
                        },
                    },
                    'RESISTANCE': {
                        'LEVEL1': {
                            'core_rc_level1_Abdominal': 'Abdominal Crunch w/RB',
                            'core_rc_level1_Oblique': 'Oblique Curl-Up w/RB',
                            'core_rc_level1_Lower': 'Lower Abdominal Crunch w/RB',
                            'core_rc_level1_Kneeling': 'Kneeling Crunch w/RB',
                            'core_rc_level1_Standing': 'Standing Back Extension w/RB',
                        },
                        'LEVEL2': {
                            'core_rc_level2_Abdominal': 'Abdominal Crunch w/RB',
                            'core_rc_level2_Oblique': 'Oblique Curl-Up w/RB',
                            'core_rc_level2_Lower': 'Lower Abdominal Crunch w/RB',
                            'core_rc_level2_Kneeling': 'Kneeling Crunch w/RB',
                            'core_rc_level2_Trunk': 'Trunk Rotation w/RB',
                            'core_rc_level2_Side': 'Side Bend w/RB',
                            'core_rc_level2_Seated': 'Seated Back Extension w/RB',
                            'core_rc_level2_Standing': 'Standing Back Extension w/RB',
                            'core_rc_level2_Quadruped': 'Quadruped Stabilization w/RB',
                        },
                        'LEVEL3': {
                            'core_rc_level3_Trunk': 'Trunk Rotation w/RB',
                            'core_rc_level3_Side': 'Side Bend w/RB',
                            'core_rc_level3_Seated': 'Seated Back Extension w/RB',
                        },
                    },
                },
            }
        },
    },
}
