MEDICAL = {
    'MUSCULOSKELETAL': {
        'FOOTBASE': {
            'sole1': 'Normal',
            'Pes_Planus': 'Pes-Planus/Over-pronasyon (İçe basma)',
            'Pes_Cavus': 'Pes-Cavus/Over-supinasyon (Dışa basma)',
            'flat_feet': 'Flat Feet (Düz taban)',
            'dorsi_fleksiyon': 'Dorsi-fleksiyon Kaybı',
            'plantar': 'Plantar Fasya Ağrısı',
            'gastrocnemius_sensitive': 'Gastrocnemius Hassasiyeti',
            'ankle_sprain': 'Ayak Bileği Burkulması',
            'achilles_tendonopathy': 'Aşil Tendonopati',
            'achilles_tendonopathy_tear': 'Aşil Tendonu Yırtığı',
            'plantar_fasiitis': 'Plantar Fasiitis',
        },
        'KNEEANDLEG': {
            'normal_leg_knee': 'Normal',
            'genu_recurvatum': ' Genu Recurvatum (Hiperekstensiyonda diz)',
            'flexed_knee': 'Flexed Knee (Bükülü diz)',
            'genu': ' Genu Varum (Parantez bacak)',
            'genu_valgus': 'Genu Valgus (X bacak)',
            'knee_pain': 'Diz Ağrısı',
            'kripitasyon': 'Kripitasyon (Çıtlama) Varlığı',
            'acl_tear': 'ACL Yırtığı',
            'pcl_tear': 'PCL Yırtığı',
            'medial_tear': 'Medial Menisküs Yırtığı',
            'lateral_tear': 'Lateral Menisküs Yırtığı',
            'patello_sendrom': 'Patello-Femoral Sendrom',
            'it_sendrom': 'IT Band Sendrom',
            'kuadriseps': 'Kuadriseps Gerginliği',
            'hamstring_g': 'Hamstring Gerginliği',
            'hamstring_tear': 'Hamstring Yırtığı',
            'groin_tear': 'Kasık Yırtığı',
            'shin': 'Shin Splints (Medial Tibia Stres Kırığı) Sendromu',
            'kneecap_pains': 'Diz Kapağı Ağrıları',
            'patellar_dislokasiyon': 'Patellar Dislokasyon',
        },
        'LUMBOPELVIK': {
            'normal_lumbo_hip': 'Normal',
            'lomber': 'Lomber Lordoz Artışı',
            'anterior': 'Anterior Pelvik Tilt',
            'posterior': 'Posterior Pelvic Tilt',
            'unleveling': 'Unleveling Pelvis Sendromu',
            'gluteal_amnezi': 'Gluteal Amnezi (Ölü Popo) Sendromu',
            'hip_pain': 'Kalça Ağrısı',
            'lower_back_pain': 'Alt Sırt Ağrısı',
            'siyatik': 'Siyatik Sinir Hassasiyeti',
            'piriformis': 'Piriformis Sendromu Yırtığı',
            'medial_meniskus_tear': 'Medial Menisküs Sendromu',
            'hip_surgeon': 'Kalça Cerrahisi',
            'hip_labrum': 'Kalça Labrum Sendromu',
            'spinal_fuzyon': 'Spinal Füzyon',
            'waist': 'Bel Fıtığı',
            'waist_surgeon': 'Bel Fıtığı Cerrahisi',
            'ankilozan': 'Ankilozan Spondilit',
            'spondoliztesiz': 'Spondoliztesiz',
            'waist_artrit': 'Kalça Artriti – Bursiti',
            'sakro': 'Sakro-İliak Eklem Ağrısı',
            'disk_hernia': 'Disk Hernia - Bulge',
            'spinal_pain': 'Omurilik Ağrıları',
        },
        'TORAKAL': {
            'normal_torakal': 'Normal',
            'torakal_kifoz': 'Torakal Kifoz Artışı',
            'sway_back': 'Sway Back  (Düz Sırt)',
            'fonksiyonel_skolyoz': 'Fonksiyonel Skolyoz',
            'wing_skapula': 'Wing Skapula',
            'torasik': 'Torasik Outlet  Sendromu',
            'torakal_g': 'Torakal Gerginlik  ve Ağrı',
        },
        'SKAPULA': {
            'normal_skapula': 'Normal',
            'protracted_skapula': 'Protracted Skapul (Yukarı Öne Açılmış Skapula)',
            'scapula_control': 'Skapular Kontrol Problemleri',
            'shoulder_instabilty': 'Omuz İnstabiltes',
            'internal_rotasyon': 'İnternal Rotasyon (Kol) Varlığı',
            'round_shoulder': 'Round Shoulder (Dönmüş Omuz)',
            'elevated_shoulder': 'Elevated Shoulder Blade (Yükselmiş Skapula)',
            'shoulder_disloksiyon': 'Omuz Eklemi Dislokasyonu',
            'kapsul_sendrom': 'Yapışkan Kapsül Sendromu',
            'rotator_cuff': 'Rotator Cuff (Manşet) Sendromu',
            'shoulder_impingment': ' Omuz Impingment (Sıkışma) Sendromu',
            'frozen_shoulder': 'Frozen  (Donuk) Shoulder',
            'tenis': 'Tenisçi Dirseği',
            'golf': 'Golfçü Dirseği',
            'kubitel': 'Kübitel Tünel Sendromu',
            'karpal': 'Karpal Tünel Sendromu',
            'wrist_pain': 'El Bileği Ağrıları',
            'brakial': 'Brakial Pleksus Gerginliği',
        },
        'HEAD': {
            'normal_head': 'Normal',
            'forward_head': 'Forward Head (İleri Baş) Sendromu',
            'servikal': 'Servikal Lordoz Artışı',
            'neck_straightening': 'Boyun Düzleşmesi',
            'neck_hernia': 'Boyun Fıtığı',
            'neck_surgeon': 'Boyun Omurları Cerrahisi',
            'temporo_mandibular': 'Temporo-mandibular Eklem Ağrıları',
            'head_pain': 'Baş Ağrısı',
        },
    },
    'MANUAL': {
        'FOOT': {
            '1': 'Güçlü',
            '2': 'Normal',
            '3': 'Zayıf (Diğer Kaslardan Destek Alma)',
            '4': 'Aktivite Yok',
        },
    },
    'GONIOMETRIK': {
        'FOOD': {
            'dorsi1': 'Dorsi-Fleksiyon',
            'plantar1': 'Plantar-Fleksiyon',
            'inversiyon': 'Inversiyon',
            'eversiyon': 'Eversiyon',
        },
        'KNEE': {
            'ekstansiyon': 'Ekstansiyon (Kalça Bükülü)',
            'fleksiyon1': 'Fleksiyon',
        },
        'HIP': {
            'fleksiyon2': 'Fleksiyon (Diz Bükülü)',
            'abduksiyon': 'Abdüksiyon',
            'internal1': 'İnternal Rotasyon',
            'eksternal1': 'Eksternal Rotasyon',
            'ekstansiyon1': 'Ekstansiyon',
        },
        'SHOULDER': {
            'fleksiyon3': 'Fleksiyon',
            'ekstansiyon2': 'Ekstansiyon',
            'abduksiyon1': 'Abdüksiyon',
            'internal2': 'İnternal Rotasyon',
            'eksternal2': 'Eksternal Rotasyon',
        },
        'ELBOW': {
            'fleksiyon4': 'Fleksiyon',
            'ekstansiyon3': 'Ekstansiyon',
        },
        'WRIST': {
            'fleksiyon5': 'Fleksiyon',
            'ekstansiyon4': 'Ekstansiyon',
            'radial': 'Radial Deviasyon',
            'ulnar': 'Ulnar Deviasyon',
        },
    },
    'METABOLIC': {
        'GLUCOSE': {
            'a_suger': 'Açlık Kan Şekeri',
            't_suger': 'Tokluk Kan Şekeri',
            'insulin': ' Açlık Insülin',
            'hb1ac': 'HB1AC ',
            'fruktozamin': 'Fruktozamin',
        },
        'IMMUNITY': {
            'hs_crp': 'Hs-CRP)',
            'sedimantasyon': 'Sedimantasyon (ESR)',
        },
        'LIPID': {
            'ldl': 'LDL',
            'hdl': 'HDL',
            'trigliserit': 'Trigliserit',
            'total_kolesterol': 'Total Kolesterol',
        },
        'PRESSURE': {
            'sistolik': 'Sistolik Kan Basıncı',
            'diastolik': 'Diastolik Kan Basıncı',
        },
        'BLOODFUNCTIONS': {
            'hemoglobin': 'Hemoglobin',
            'hemotokrit': 'Hemotokrit',
        },
        'LIVER': {
            'ast': 'AST',
            'alt': 'ALT',
            'ggt': 'GGT',
        },
        'HORMONE': {
            'leptin': 'Leptin',
            'ghrelin': 'Ghrelin',
            'insulin1': 'İnsülin',
            'kortizol': 'Kortizol',
            'testosteron': 'Testosteron',
            'ostrojen': 'Östrojen',
            'growth_hormone': 'Büyüme Hormonu',
            'tsh': 'TSH (Tiroit Stimule Edici Horrmon)',
            'triiyodotrinin': 'Triiyodotrinin (T3)',
            'total_tiroksin': 'Total Tiroksin (T4)',
        },
        'VITAMIN': {
            'c_vit': 'C Vitamini',
            'e_vit': 'E Vitamini',
            'a_vit': 'A Vitamini',
            'folik': 'Folik Asit',
            'b6': 'B6',
            'b12': 'B12',
            'd3_vit': 'Vitamin D3',
        },
        'MINERAL': {
            'kalsiyum': 'Kalsiyum',
            'demir': 'Demir',
            'magnezyum': 'Magnezyum',
            'bakir': 'Bakır',
            'cinko': 'Çinko',
            'selenyum': 'Selenyum',
            'potasyum': 'Potasyum',
            'koenzim': 'Koenzim Q10',
        },
        'AMINOACID': {
            'lizin': 'Lizin',
            'metiyonin': 'Metiyonin',
            'triptofan': 'Triptofan',
            'losin': 'Lösin',
            'izolosin': 'Izolösin',
            'valin': 'Valin',
            'treonin': 'Treonin',
            'fenilalanin': 'Fenilalanin',
            'histidin': 'Histidin',
            'arjinin': 'Arjinin',
            'glutamin': 'Glutamin',
            'serin': 'Serin',
            'tirozin': 'Tirozin',
            'prolin': 'Prolin',
            'sistein': 'Sistein',
            'alanin': 'Alanin',
            'aspartik': 'Aspartik Asit',
            'glutamik': 'Glutamik Asit',
            'asparajin': 'Asparajin',
        },
        'BONE': {
            'z_Skoru': 'Z-Skoru',
            't_Skoru': 'T-Skoru',
        },
    },
    'MOVEMENT': {
        'OVERHEAD': {
            'overhead_normal': 'Normal',
            'overhead_glenohumeral': 'Glenohumeral İmmobilite',
            'overhead_torakal': 'Torakal İmmobilite',
            'overhead_body': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'overhead_foot': 'Ayak Bileği İmmobilitesi',
            'overhead_knee': 'Diz İnstabilitesi',
            'overhead_hip': 'Kalça İmmobilitesi',
            'overhead_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'overhead_pain': 'Ağrı Varlığı',
        },
        'SQUAT': {
            'squat_normal': 'Normal',
            'squat_torakal': 'Torakal İmmobilite',
            'squat_body': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'squat_foot': 'Ayak Bileği İmmobilitesi',
            'squat_knee': 'Diz İnstabilitesi',
            'squat_hip': 'Kalça İmmobilitesi',
            'squat_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'squat_pain': ' Ağrı Varlığı',
        },
        'BRIDGE': {
            'bridge_normal': 'Normal',
            'bridge_hip_fleksiyon': 'Kalça Fleksiyon Artışı',
            'bridge_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'bridge_body': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'bridge_knee': 'Diz İnstabilitesi',
            'bridge_hip_imo': 'Kalça İmmobilitesi',
            'bridge_hamstring': 'Hamstring Gerginliği',
            'bridge_Kuadriseps': 'Kuadriseps Gerginliği',
            'bridge_pain': 'Ağrı Varlığı',
        },
        'LUNGE': {
            'lunge_normal': 'Normal',
            'lunge_patello': 'Patello-Femoral Kayma',
            'lunge_over': 'Over-pronasyon',
            'lunge_body_fleksiyon': 'Gövde Fleksiyon Artışı',
            'lunge_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'lunge_body': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'lunge_foot': 'Ayak Bileği İmmobilitesi',
            'lunge_knee': 'Diz İnstabilitesi',
            'lunge_hip': ' Kalça İmmobilitesi',
            'lunge_pain': 'Ağrı Varlığı',
        },
        'TRUNK': {
            'trunk_normal': 'Normal',
            'trunk_core': 'Core Stabilizasyon Kaybı',
            'trunk_skapula': 'Skapula İnstabilizasyon',
            'trunk_hip': 'Kalça İmmobilitesi',
            'trunk_lomber': 'Lomber Lordoz Artışı',
            'trunk_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'trunk_pain': 'Ağrı Varlığı',
        },
        'SHOULDER': {
            'shoulder_normal': 'Normal',
            'shoulder_core': 'Core Stabilizasyon Kaybı',
            'shoulder_skapula': 'Skapulo-Torasik İnstabilite - İmmobilite',
            'shoulder_gleno': 'Gleno-Humeral Disfonksiyon',
            'shoulder_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'shoulder_pain': 'Ağrı Varlığı',
        },
        'ACTIVE': {
            'active_normal': 'Normal',
            'active_pelvik': 'Pelvik Kontrol Kaybı',
            'active_hip': 'Kalça İmmobilitesi (Karşı taraf)',
            'active_ekstansiyon': 'Kalça Ekstansiyon Disfonksiyonu',
            'active_hamstring': 'Hamstring Gerginliği',
            'active_lomber': 'Lomber Lordoz Artışı',
            'active_rotasyon': 'Artmış Gövde Rotasyon (kaldırılan bacak yönüne)',
            'active_pain': 'Ağrı Varlığı (Sakro-iliak eklem)',
        },
        'ROTARY': {
            'rotary_normal': 'Normal',
            'rotary_core': 'Core İnstabilitesi',
            'rotary_body': 'Gövde İnstabilitesi',
            'rotary_hip': ' Kalça-Diz-Omuz İmmobilitesi',
            'rotary_balance': 'Denge Kayıpları (zayıf motor kontrol)',
            'rotary_pain': 'Ağrı Varlığı',
        },
        'FRONT': {
            'front_normal': 'Normal',
            'front_pelvisin': ' Pelvisin Aşağı Çökmes',
            'front_core': 'Coreİnstabilitesi',
            'front_body': 'Gövde Hizalama Sorunları',
            'front_arm': 'Kol-Omuz İnstabilitesi',
            'front_pain': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'SIDE': {
            'side_normal': 'Normal',
            'side_pelvisin': ' Pelvisin Aşağı Çökmesi',
            'side_core': 'Core İnstabilitesi',
            'side_body': 'Gövde Hizalama Sorunları',
            'side_foot': 'Ayak İnstabilitesi',
            'side_arm': 'Kol-Omuz İnstabilitesi',
            'side_pain': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'FLEKSOR': {
            'fleksor_normal': 'Normal',
            'fleksor_body': 'Gövdenin Geriye Kayması',
            'fleksor_core': 'Core İnstabilitesi',
            'fleksor_problem': 'Gövde Hizalama Sorunları',
            'fleksor_hamstring': 'Hamstring Gerginliği',
            'fleksor_kuadriseps': 'Kuadriseps Gerginliği',
            'fleksor_foot': 'Ayak İnstabilitesi',
            'fleksor_pain': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'EKSTANSOR': {
            'extansor_normal': 'Normal',
            'extansor_body_shift': 'Gövdenin Öne Kayması',
            'extansor_core': ' Core İnstabilitesi',
            'extansor_problems': 'Gövde Hizalama Sorunları',
            'extansor_lomber': 'Lomber Lordoz Artışı',
            'extansor_hamstring': 'Hamstring Gerginliği',
            'extansor_kuadriseps': 'Kuadriseps Gerginliği',
            'extansor_pain': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'BALANCE': {
            'OPEN': {
                'open_time1': 'Süre 1',
                'open_time2': 'Süre 2',
                'open_time3': 'Süre 3',
            },
            'CLOSE': {
                'close_time1': 'Süre 1',
                'close_time2': 'Süre 2',
                'close_time3': 'Süre 3',
            },
        },
        'STAR': {
            'THREEDIRECT': {
                'treedirect_anterior': 'Anterior (cm)',
                'treedirect_medial': 'Postero-medial (cm)',
                'treedirect_lateral': 'Postero-lateral (cm)',
            },
            'SEVENDIRECT': {
                'all_anterior': 'Anterior (cm)',
                'all_antero_lateral': 'Antero-lateral (cm)',
                'all_antero_media': 'Antero-media (cm)',
                'all_lateral': 'Lateral (cm)',
                'all_medial': 'Medial (cm)',
                'all_posterior': 'Posterior-medial (cm)',
                'all_postero_medial': 'Postero-lateral (cm)',
                'all_postero_lateral': 'Postero-lateral (cm)',
            },
        },
        'ERROR': {
            'two_leg': 'Sabit Zemin Çift Ayak(Hata Sayısı)',
            'non_dominant': 'Sabit Zemin Non-Dominant Bacak(Hata Sayısı)',
            'tandem': 'Sabit Zemin Tandem(Hata Sayısı)',
            'two_leg1': 'Hareketli Zemin Çift Ayak(Hata Sayısı)',
            'non_dominant1': 'Hareketli Zemin Non-Dominant Bacak(Hata Sayısı)',
            'tandem1': 'Hareketli Zemin Tandem(Hata Sayısı)',
        },
        'MODIFIED': {
            'skor1': 'Skor 1',
            'skor2': 'Skor 2',
            'skor3': 'Skor 3',
        },
    },
}
