FORM = {
    # Ön görüşme Formu
    'INTERVIEWFORM': {
        'CONSULTANCY': {
            'pt': 'Personal Training',
            'py': 'Pilates - Yoga',
            'de': 'Düzeltici Egzersiz',
            'ap': 'Atletik Performans',
            'he': 'Hamilelik Egzersiz',
            'ce': 'Çocuklarda Egzersiz',
            'me': 'Medikal Egzersiz',
            'syd': 'Sağlıklı Yaşam Danışmanlığı',
        },
        'EXERCISEDAY': {
            '2day': '2 Gün/Hafta',
            '3day': '3 Gün/Hafta',
            '4day': '4 Gün/Hafta',
            '5day': '5 Gün/Hafta',
            '6day': '6 Gün/Hafta',
            '7day': '7 Gün/Hafta',
        },
        'EXERCISEDURATION': {
            '1month': '1 Ay',
            '3month': '3 Ay',
            '6month': '6 Ay',
            '12month': '12 Ay',
        },
        'EXERCISEPREFERENCE': {
            'monday': 'Pazartesi',
            'tuesday': 'Salı',
            'wednesday': 'Çarşamba',
            'thursday': 'Perşembe',
            'friday': 'Cuma',
            'saturday': 'Cumartesi',
            'sunday': 'Pazar',
        },
        'EXERCISEHOUR': {
            'morning': 'Sabah (08:00 – 12:00)',
            'noon': 'Öğle (12:00 – 16:00)',
            'evening': 'Akşam (17:00 – 21:00)',
        },
        'FITNESSPURPOSE': {
            'force': 'Kuvvet Gelişimi',
            'durability': 'Dayanıklılık Gelişimi',
            'sporty': 'Sportif Performans Artışı',
            'PhysicalAppearance': 'Fiziksel Görünüm Kazanımı ',
            'postural': 'Postürel Bozulma Önleme/Kontrol',
            'diabetes': 'Diyabet Önleme/Kontrol ',
            'osteoporosis': 'Osteoporoz Önleme/Kontrol',
            'parkinson': 'Parkinson Önleme/Kontrol ',
            'spine': 'Omurga Problemleri Önleme/Kontrol ',
            'neck': 'Boyun Fıtığı Önleme/Kontrol ',
            'obesity': 'Obezite Başa Çıkma',
            'stress': 'Stress Yönetimi',
            'bodyWeight2': 'Vücut Ağırlığı Yönetimi',
            'wellness': 'Zindelik ve Canlılık',
            'skolyoz': 'Skolyoz Önleme/Kontrol',
            'hypertension': 'Hipertansiyon Önleme/Kontrol',
            'alzheimer': 'Alzheimer Önleme/Kontrol',
            'cancer': 'Kanser Önleme/Kontrol',
            'kneeInjuries': 'Diz Yaralanmaları Önleme/Kontrol',
            'herniatedDisc': 'Bel Fıtığı Önleme/Kontrol',
        },
        'EXERCISETIME': {
            '1': '30 dk',
            '2': '60 dk',
            '3': '90 dk',
        }
    },

    # Teklif ve Sözleşme Formu
    'CONTRACTFORM': {
        'TESTMEASUREMENT': {
            'bodyComposition': 'Vücut Kompozisyonu',
            'cardiovascular': 'Kardiyovasküler Uygunluk',
            'metabolic': 'Metabolik Uygunluk',
            'posture': 'Postür ve Hareket Kalitesi',
            'muscleStrength': 'Kas Kuvveti ve Dayanıklılığı',
            'flexibility': 'Esneklik ve Mobilite',
            'stability': 'Stabilite ve Denge',
            'Report': 'Sonuçların Yorumlanması ve Raporlaştırılması ',
            'manuel': 'Manuel Kas Testleri',  # Model kayıtlarını oluştur
            'atletic': 'Atletik Performans Testleri',
        },

    },

    # Aile Öyküsü ve Hastalık Geçmişi
    'FAMILY': {
        'BIYOMETRIK': {
            'ANNE': {
                'anneAgirlik': 'Vucut Ağırlığı (kg)',
                'anneBoy': 'Boy Uzunluğu (cm)',
                'anneBki': 'BKI (kg/boy*boy)',
            },
            'BABA': {
                'babaAgirlik': 'Vucut Ağırlığı (kg)',
                'babaBoy': 'Boy Uzunluğu (cm)',
                'babaBki': 'BKI (kg/boy*boy)',
            },

        },
        'METABOLİK': {
            'ANNE': {
                'anneDinlenim': 'Dinlenim Kalp Atım Hızı (atım)',
                'anneSistolik': 'Sistolik Kan Basıncı (mmHg)',
                'anneKanSekeri': 'Kan Şekeri (mg/dl)',
                'anneKolesterol': 'Total Kolesterol (mg/dl)',
                'anneTrigliserit': 'Trigliserit (mg/dl)',
            },
            'BABA': {
                'babaDinlenim': 'Dinlenim Kalp Atım Hızı (atım)',
                'babaSistolik': 'Sistolik Kan Basıncı (mmHg)',
                'babaKanSekeri': 'Kan Şekeri (mg/dl)',
                'babaKolesterol': 'Total Kolesterol (mg/dl)',
                'babaTrigliserit': 'Trigliserit (mg/dl)',
            },
        },
        'DISEASE': {
            'kalpKrizi': 'Kalp krizi',
            'kalpAmeliyati': 'Kalp ameliyatı',
            'kalpKateterizasyonu': 'Kalp kateterizasyonu',
            'anjiyoplasti': 'Koroner anjiyoplasti (ptca)',
            'kalpPili': 'Kalp pili / implante edilebilir kalp',
            'defibrilator': 'Defibrilatör / ritim bozukluğu',
            'kalpKapagi': 'Kalp kapağı hastalığı',
            'kalpYetmezligi': 'Kalp yetmezliği',
            'kalpNakli': 'Kalp nakli',
            'konjenital': 'Konjenital kalp hastalığı',
        },
        'SYMPTOM': {
            'efor': 'Eforla birlikte göğüs rahatsızlığı yaşama',
            'shortnessBreath': 'Mantıksız nefes darlığı görülmesi',
            'dizziness': 'Baş dönmesi, bayılma veya göz kararması',
            'ankle': 'Ayak bileği şişmesi',
            'heartBeat': 'Güçlü veya hızlı bir kalp atış hızı hakkında hoş olmayan bir deneyim',
            'heartMedicine': 'Kalp ilacı kullanma',
        },
        'CARDİOVASCULAR': {
            'man': '45 yaş erkek',
            'woman': '55 yaş kadın',
            'cigaret': 'Önceki 6 ay içinde sigara içme veya sigarayı bırakmış olma',
            'bloodPressure': 'Tansiyon 140/90 mm Hg veya daha yukarısı',
            'blood': 'Kan basıncının bilinmemesi',
            'pressureMedication': 'Tansiyon ilaçı kullanma',
            'bloodKolesterol': 'Kan kolesterol seviyesi 200 mg/dl ve üzerinde',
            'kolesterol': 'Kolesterol seviyesinin bilinmemesi',
            'fiftyfiveage': '55 yaş (baba - erkek kardeş) öncesi kalp krizi veya kalp ameliyatı',
            'sixtyfiveage  ': '65 yaş (anne - kız kardeş) öncesi kalp krizi veya kalp ameliyatı',
            'physical': 'Fiziksel olarak aktif değil (Sedanter olmak)',
            'bodyIndex': 'Vücut kütle indeksi 30 ve üzerinde',
            'prediyabetStatus': 'Prediyabet durumu',
            'prediyabetInformation': 'Prediyabet bilgisi olmama',

        }
    },

    # Egzersiz Geçmişi ve Yönelimi
    'EXERCISEHISTORY': {
        'WALK': {
            '1': '2500 adım ve altı',
            '2': '2501-5000 adım',
            '3': '5001-7500 adım',
            '4': '7501-10 bin adım',
            '5': '10 bin adım ve üzeri',
            'no': 'Hayır',
        },
        'REGULAREXERCISE': {
            '1': 'Haftada 1 gün',
            '2': 'Haftada 2 gün',
            '3': 'Haftada 3 gün',
            '4': 'Haftada 4-5 gün',
            '5': 'Her gün',
            'no': 'Hayır'
        },
        'SPORT1': {
            '1': 'Hala yapıyorum',
            'no': 'Hayır',
        },
        'EXERCISEOBJECTIVES': {
            'weakening': 'Zayıflama',
            'generalHealth': 'Genel Sağlığı Geliştirmek ve Sürdürmek',
            'muscularity': 'Kaslanma-Hipertrofi',
            'gettingFat': 'Kilo Alma',
            'functionality': 'Fonksiyonellik Kazanımı',
            'performans': 'Performans Gelişimi',
            'metabolicIllness': 'Metabolik Hastalık Önleme (Obezite, Diyabet, Kalp Hastalıkları vb.)',
            'musculoskeletal': 'Kas İskelet Problemlerini Önlemek ve Restore Etmek',
            'aesthetic': 'Estetik ve Görünüş',
            'mentalRelaxation': 'Mental Rahatlama',
            'socializing': 'Sosyalleşme',
        },
        # Daha önce bir egzersiz profesyoneli ile çalıştınız mı(dahil)
        'FITNESSREGISTRATION': {
            '1': ' 1 - 3 ay',
            '2': ' 4 - 6 ay',
            '3': '7 - 9 ay',
            '4': '10 - 12 ay',
            '5': '1 - 2 yıl',
            '6': '2 - 4 yıl',
            '7': '5 + yıl',
            'no': 'Hayır',
        },
        'EXERCISEPARTICIPATION': {
            '1': 'Baş-Boyun Bölgesi',
            '2': 'Omuz',
            '3': 'Kollar – Dirsek – El Bölgesi',
            '4': 'Kalça',
            '5': 'Omurga',
            '6': 'Alt Sırt',
            '7': 'Diz',
            '8': 'Ayak - Ayak Bileği',
            'no': 'Hayır',
        },
        'SAFE': {
            '1': 'Genellikle',
            '2': 'Bazen',
            '3': 'Hayır',
        }
    },

    # 7.PAR-Q Formu
    'PARQ': {
        'yes': 'Evet',
        'no': 'Hayır',
    },

    # Duygu Durumu – Sosyalite – İş Koşulları
    'MOOD': {
        'HAPPY': {
            '1': 'Genellikle',
            '2': 'Bazen',
            '3': 'Hayır',
        },
        'DEFINITION': {  # Tanımlama
            '1': 'Mutlu',
            '2': 'Normal',
            '3': 'Mutsuz',
        },
        'FRIENDS': {
            '1': 'Genellikle',
            '2': 'Bazen',
            '3': 'Hiç',
        },
        # Çevrenizde yaşanan olumsuz durumlar sizi etkiler mi?
        'POSITION': {
            '1': 'Evet',
            '2': 'Kısmen',
            '3': 'Hayır',
        },
        'SUCCESS': {
            '1': 'Genellikle',
            '2': 'Bazen',
            '3': 'Hayır',
        },
        'ALONE': {
            '1': 'Genellikle',
            '2': 'Bazen',
            '3': 'Hiç',
        },
        'SOCIALMEDIA': {
            '1': '10+',
            '2': '7-9',
            '3': '4-6',
            '4': '1-3',
            '5': 'Hiç',
        },
        # Ekran karşısı
        'SITTING': {
            '1': '0-2 saat',
            '2': '2-4 saat',
            '3': '4-6 saat',
            '4': '6-8 saat',
            '5': '8-10 saat',
            '7': '10 ve üzeri',
        },
        'NOON': {
            '1': 'Yemek arası',
            '2': 'Kahve ve çay arası',
            '3': 'Yürüyüş',
            '4': 'Çalışmaya devam ederim',
        },
    },

    # Uyku Kalitesi – Zindelik – Ağrı Durumu Formu
    'SLEEPQUALITY': {
        'TIME': {
            '1': '24.00+',
            '2': '22.00-24.00',
            '3': '20.00-22.00',
        },
        'AVERAGESLEEP': {
            '1': '4-6',
            '2': '7-9',
            '3': ' 10+',
        },
        'ROOMDARK': {
            '1': 'Evet',
            '2': 'Kısmen',
            '3': 'Hayır',
        },
        'SLEEPPOZITION': {
            '1': 'Sırt-üstü ',
            '2': 'Yüz-üstü',
            '3': 'Sağ veya sol yana dönük',
            '4': 'Bilmiyorum',
        },
        'MORNING': {
            '1': 'Zinde ve Enerjik',
            '2': 'Normal ',
            '3': 'Yorgun',
            '4': 'Çok Yorgun',
        },
        'FOCUSING': {
            '1': 'Genellikle',
            '2': 'Bazen',
            '3': 'Hayır',
        },
    },

    # Beslenme ve Tüketim Alışkanlıkları Formu
    'NUTRITIONFORM': {
        'BREAKFAST': {
            '1': 'Her Zaman/Sürekli',
            '2': 'Sık Sık',
            '3': 'Ara Sıra',
            '4': 'Çok Seyrek',
            '5': 'Hiç',
        },
        'MEAL': {
            '1': '3+',
            '2': '3',
            '3': '2',
            '4': '1',
        },
        # Ara Öğün
        'MEAL2': {
            '1': '3+',
            '2': '3',
            '3': '2',
            '4': '1',
            '5': 'Hiç'
        },
        'PROTEIN': {
            '1': 'Kırmızı Et',
            '2': 'Beyaz Et',
            '3': 'Süt-Süt Ürünleri',
            '4': 'Bitkisel Kaynaklar',
        },
        'PROTEINCONSUMPTION': {
            '1': '10+ porsiyon',
            '2': '7-9 porsiyon',
            '3': '4-6 porsiyon',
            '4': '1-3 porsiyon',
            '5': 'Hiç',
        },
        'VEGETARIAN': {
            '1': 'Lacto Vejetaryen',
            '2': 'Ovo Vejetaryen',
            '3': 'Ovo-Lacto Vejetaryen',
            '4': 'Pesketaryan',
            '5': 'Vegan',
        },
        'VEGETARYTIME': {
            '1': '0-6 ay',
            '2': '7-12 ay',
            '3': '1-3 yıl',
            '4': '4-6 yıl',
            '5': '7-9 yıl',
            '6': '10+ yıl',
            '7': 'Hayır'
        },
        'WATERCONSUMPTION': {
            '1': '4+ Lt',
            '2': '2-3 Lt',
            '3': '1-2 Lt',
            '4': '1 Lt’den az',
            '5': 'Dikkat etmem',
        },
        'DINNER': {
            '1': '24.00+',
            '2': '22.00-24.00',
            '3': '20.00-22.00',
            '4': '18.00-20.00',
            '5': '18.00 öncesi',
        },
        'TABLESALT': {
            '1': 'Sofra tuzu',
            '2': 'Kaya tuzu',
            '3': 'Deniz tuzu',
        },
        'OILCONSUMPTION': {
            '1': 'Sıvı (zeytinyağı)',
            '2': 'Sıvı (ayçicek-mısır)',
            '3': 'Katı (tereyağı) ',
            '4': 'Katı (diğer)',

        },
        'NUTSCONSUMPTION': {
            '1': 'Tuzlu kavrulmuş',
            '2': 'Tuzsuz kavrulmamış',
            '3': 'Dikkat etmem',
        },
        'COFFEECONSUMPTION': {
            '1': '1-3 fincan',
            '2': '4-6 fincan',
            '3': '7-9 fincan',
            '4': '10+ fincan',
        },
        'COFFEEPREFERENCE': {
            'turkishCoffee1': 'Türk Kahvesi',
            'espresso1': 'Espresso',
            'filtrCoffee1': 'Filtre kahve',
            'americano1': 'Americano',
            'latte1': 'Latte',
            'macchiato1': 'Macchiato',
            'mocha1': 'Mocha',
            'cappuccino1': 'Cappuccino',
            'flatWhite1': 'Flat White',
            'cortado1': 'Cortado',
            'frappe1': 'Frappe',
        },
        'COFFEECHOİCE': {
            '1': 'Sade ve şekersiz',
            '2': 'Şeker ilaveli',
            '3': 'Süt ilaveli',
            '4': 'Şeker ve Süt ilaveli',
            '5': 'Tatlandırıcı ve Aroma ilaveli',
        },
        'DIET': {
            'ketojenik': 'Ketojenik Diyet',
            'dukan': 'Dukan Diyeti',
            'intermittent': 'Intermittent Fasting (Aralıklı Oruç) Diyeti',
            'akdeniz': 'Akdeniz Diyeti',
            'paleo': 'Paleo Diyeti',
            'atkins': 'Atkins Diyet',
            'zone': 'Zone Diyeti',
            'dash': 'DASH Diyeti',
            'flexitarian': 'Esnek+Vejeteryan (Flexitarian) Diyeti',
            'whole500': 'Whole30 Diyeti',
            'no': 'Yapmıyorum'
        },
        'REASONDIET': {
            'health1': 'Sağlığı korumak ve sürdürmek için',
            'weaken': 'Zayıflamak için',
            'diseases': 'Hastalıklardan korumak için',
            'trend': 'Trend bir davranış olduğu için',
            'try_request': 'Denemek istediğim için',
            'doctor': 'Doktor söylediği için',
            'nutritionist': 'Diyetisyen tavsiye ettiği için',
            'sport2': 'Spor hocam tavsiye ettiği için',
            'advice': 'Arkadaşlarım tavsiye ettiği için',
            'celebrityadvice': 'Ünlüler tavsiye ettiği için',
        },
        'LONGDIET': {
            '1': '0-1 hafta',
            '2': '2-3 hafta',
            '3': '1 ay',
            '4': '2-3 ay',
            '5': '4-6 ay',
            '6': '7-12 ay',
            '7': '1-3 yıl',
        },
        'VITAMINS': {
            'd': 'D Vitamini',
            'c': 'C Vitamini',
            'b': 'B Vitamini',
            'multiVitamin': 'Multi-vitamin',
            'immunity': 'Bağışıklık güçlendiriciler',
            'iron': 'Demir',
            'zinc': 'Çinko',
            'calcium': 'Kalsiyum',
            'kollajen': 'Kollajen',
            'glucosamin': 'Glucosamin türevleri',
            'aminoasit': 'Aminoasit türevleri',
            'l': 'L-Carnitin,',
            'cla': 'CLA',
            'chromium': 'Chromium Pikolinat',
            'omega': 'Omega-3',
            'q': 'Q-Enzim 10',
            'protein_powder': 'Protein tozları',
            'bcaa': 'BCAA',
            'glutamin': 'Glutamin',
            'weight4': 'Kilo aldırıcılar',
            'kreatin': 'Kreatinler',
        },
        'FOODTIME': {
            '1': '0-6 ay',
            '2': '7-12 ay',
            '3': '1-3 yıl',
            '4': '4-6 yıl',
            '5': '7-9 yıl',
            '6': '10+ yıl',
        },
    },

    # İzlence Formu
    'MAIN': {
        'MEAL': {
            '1': 'Kendim Hazırladım',
            '2': 'Dışarıdan Sipariş Verdim',
            '3': 'Restoran, Cafe vb. Yerlerde Yedim',
        },
        'FRUIT': {
            'muz': 'Muz',
            'elma': 'Elma',
            'incir': 'İncir',
            'portakal': 'Portakal',
            'mandalin': 'Mandalin',
            'karpuz': 'Karpuz',
            'kavun': 'Kavun',
            'uzum': 'Üzüm',
            'bogurtlen': 'Böğürtlen – Ahududu',
            'cilek': 'Çilek',
            'kivi': 'Kivi',
            'seftali': 'Şeftali',
            'ayva': 'Ayva',
            'armut': 'Armut',
            'ananas': 'Ananas',
            'kiraz': 'Kiraz',
            'visne': 'Vişne',
            'avakado': 'Avakado',
        },
        'FRUIT_NOON': {
            'muz_noon': 'Muz',
            'elma_noon': 'Elma',
            'incir_noon': 'İncir',
            'portakal_noon': 'Portakal',
            'mandalin_noon': 'Mandalin',
            'karpuz_noon': 'Karpuz',
            'kavun_noon': 'Kavun',
            'uzum_noon': 'Üzüm',
            'bogurtlen_noon': 'Böğürtlen – Ahududu',
            'cilek_noon': 'Çilek',
            'kivi_noon': 'Kivi',
            'seftali_noon': 'Şeftali',
            'ayva_noon': 'Ayva',
            'armut_noon': 'Armut',
            'ananas_noon': 'Ananas',
            'kiraz_noon': 'Kiraz',
            'visne_noon': 'Vişne',
            'avakado_noon': 'Avakado',
        },
        'FRUIT_EVENING': {
            'muz_evening': 'Muz',
            'elma_evening': 'Elma',
            'incir_evening': 'İncir',
            'portakal_evening': 'Portakal',
            'mandalin_evening': 'Mandalin',
            'karpuz_evening': 'Karpuz',
            'kavun_evening': 'Kavun',
            'uzum_evening': 'Üzüm',
            'bogurtlen_evening': 'Böğürtlen – Ahududu',
            'cilek_evening': 'Çilek',
            'kivi_evening': 'Kivi',
            'seftali_evening': 'Şeftali',
            'ayva_evening': 'Ayva',
            'armut_evening': 'Armut',
            'ananas_evening': 'Ananas',
            'kiraz_evening': 'Kiraz',
            'visne_evening': 'Vişne',
            'avakado_evening': 'Avakado',
        },
        'FRUIT_SNACK': {
            'muz_snack': 'Muz',
            'elma_snack': 'Elma',
            'incir_snack': 'İncir',
            'portakal_snack': 'Portakal',
            'mandalin_snack': 'Mandalin',
            'karpuz_snack': 'Karpuz',
            'kavun_snack': 'Kavun',
            'uzum_snack': 'Üzüm',
            'bogurtlen_snack': 'Böğürtlen – Ahududu',
            'cilek_snack': 'Çilek',
            'kivi_snack': 'Kivi',
            'seftali_snack': 'Şeftali',
            'ayva_snack': 'Ayva',
            'armut_snack': 'Armut',
            'ananas_snack': 'Ananas',
            'kiraz_snack': 'Kiraz',
            'visne_snack': 'Vişne',
            'avakado_snack': 'Avakado',
        },
        'FRUIT_PORSION': {
            '1': 'Adet',
            '2': 'Kase',
        },
        'VEGETABLES': {
            'salata': 'Salata',
            'yesil': 'Yeşil Yapraklı Sebzeler',
            'ispanak': 'Ispanak',
            'lahana': 'Lahana',
            'mor': 'Mor Lahana',
            'bruksel': 'Brüksel Lahanası',
            'patlican': 'Patlıcan',
            'kabak': 'Kabak',
            'havuc': 'Havuç',
            'marul': 'Marul',
            'brokoli': 'Brokoli',
            'karnabahar': 'Karnabahar',
            'domates': 'Domates',
            'salatalik': 'Salatalık',
            'pirasa': 'Pırasa',
            'yesilFasulye': 'Yeşil Fasulye',
            'kuruSogan': 'Kuru Soğan',
            'sarimsak': 'Sarımsak',
            'turp': 'Turp',
            'biber': 'Biber',
            'mantar': 'Mantar',
            'limon': 'Limon',
            'patates': 'Patates',
            'bamya': 'Bamya',
            'kereviz': 'Kereviz',
            'enginar': 'Enginar',
        },
        'VEGETABLES_NOON': {
            'salata_noon': 'Salata',
            'yesil_noon': 'Yeşil Yapraklı Sebzeler',
            'ispanak_noon': 'Ispanak',
            'lahana_noon': 'Lahana',
            'mor_noon': 'Mor Lahana',
            'bruksel_noon': 'Brüksel Lahanası',
            'patlican_noon': 'Patlıcan',
            'kabak_noon': 'Kabak',
            'havuc_noon': 'Havuç',
            'marul_noon': 'Marul',
            'brokoli_noon': 'Brokoli',
            'karnabahar_noon': 'Karnabahar',
            'domates_noon': 'Domates',
            'salatalik_noon': 'Salatalık',
            'pirasa_noon': 'Pırasa',
            'yesilFasulye_noon': 'Yeşil Fasulye',
            'kuruSogan_noon': 'Kuru Soğan',
            'sarimsak_noon': 'Sarımsak',
            'turp_noon': 'Turp',
            'biber_noon': 'Biber',
            'mantar_noon': 'Mantar',
            'limon_noon': 'Limon',
            'patates_noon': 'Patates',
            'bamya_noon': 'Bamya',
            'kereviz_noon': 'Kereviz',
            'enginar_noon': 'Enginar',
        },
        'VEGETABLES_EVENING': {
            'salata_evening': 'Salata',
            'yesil_evening': 'Yeşil Yapraklı Sebzeler',
            'ispanak_evening': 'Ispanak',
            'lahana_evening': 'Lahana',
            'mor_evening': 'Mor Lahana',
            'bruksel_evening': 'Brüksel Lahanası',
            'patlican_evening': 'Patlıcan',
            'kabak_evening': 'Kabak',
            'havuc_evening': 'Havuç',
            'marul_evening': 'Marul',
            'brokoli_evening': 'Brokoli',
            'karnabahar_evening': 'Karnabahar',
            'domates_evening': 'Domates',
            'salatalik_evening': 'Salatalık',
            'pirasa_evening': 'Pırasa',
            'yesilFasulye_evening': 'Yeşil Fasulye',
            'kuruSogan_evening': 'Kuru Soğan',
            'sarimsak_evening': 'Sarımsak',
            'turp_evening': 'Turp',
            'biber_evening': 'Biber',
            'mantar_evening': 'Mantar',
            'limon_evening': 'Limon',
            'patates_evening': 'Patates',
            'bamya_evening': 'Bamya',
            'kereviz_evening': 'Kereviz',
            'enginar_evening': 'Enginar',
        },
        'VEGETABLES_SNACK': {
            'salata_snack': 'Salata',
            'yesil_snack': 'Yeşil Yapraklı Sebzeler',
            'ispanak_snack': 'Ispanak',
            'lahana_snack': 'Lahana',
            'mor_snack': 'Mor Lahana',
            'bruksel_snack': 'Brüksel Lahanası',
            'patlican_snack': 'Patlıcan',
            'kabak_snack': 'Kabak',
            'havuc_snack': 'Havuç',
            'marul_snack': 'Marul',
            'brokoli_snack': 'Brokoli',
            'karnabahar_snack': 'Karnabahar',
            'domates_snack': 'Domates',
            'salatalik_snack': 'Salatalık',
            'pirasa_snack': 'Pırasa',
            'yesilFasulye_snack': 'Yeşil Fasulye',
            'kuruSogan_snack': 'Kuru Soğan',
            'sarimsak_snack': 'Sarımsak',
            'turp_snack': 'Turp',
            'biber_snack': 'Biber',
            'mantar_snack': 'Mantar',
            'limon_snack': 'Limon',
            'patates_snack': 'Patates',
            'bamya_snack': 'Bamya',
            'kereviz_snack': 'Kereviz',
            'enginar_snack': 'Enginar',
        },
        'VEGETABLES_PORSION': {
            '1': 'Küçük Boy',
            '2': 'Orta Boy',
            '3': 'Büyük Boy',
        },
        'CHEESE': {
            '1': '25 gr',
            '2': '50 gr',
            '3': '75 gr',
            '4': '100 gr',
            '5': '100+ gr',
        },
        'EGG': {
            '1': 'Küçük',
            '2': 'Orta',
            '3': 'Büyük',
        },
        'BREAD': {
            '1': '1 Dilim',
            '2': '2 Dilim',
            '3': '3 Dilim',
            '4': '1/2 Ekmek',
            '5': '1 Ekmek',
        },
        'GRAIN': {
            'bugday': 'Buğday (bulgur)',
            'arpa': 'Arpa',
            'pirinc': 'Pirinç',
            'kinoa': 'Kinoa',
            'yulaf': 'Yulaf',
            'cavdar': 'Çavdar',
            'misir': 'Mısır',
            'tritikale': 'Tritikale'
        },
        'GRAIN_NOON': {
            'bugday_noon': 'Buğday (bulgur)',
            'arpa_noon': 'Arpa',
            'pirinc_noon': 'Pirinç',
            'kinoa_noon': 'Kinoa',
            'yulaf_noon': 'Yulaf',
            'cavdar_noon': 'Çavdar',
            'misir_noon': 'Mısır',
            'tritikale_noon': 'Tritikale'
        },
        'GRAIN_EVENING': {
            'bugday_evening': 'Buğday (bulgur)',
            'arpa_evening': 'Arpa',
            'pirinc_evening': 'Pirinç',
            'kinoa_evening': 'Kinoa',
            'yulaf_evening': 'Yulaf',
            'cavdar_evening': 'Çavdar',
            'misir_evening': 'Mısır',
            'tritikale_evening': 'Tritikale'
        },
        'GRAIN_SNACK': {
            'bugday_snack': 'Buğday (bulgur)',
            'arpa_snack': 'Arpa',
            'pirinc_snack': 'Pirinç',
            'kinoa_snack': 'Kinoa',
            'yulaf_snack': 'Yulaf',
            'cavdar_snack': 'Çavdar',
            'misir_snack': 'Mısır',
            'tritikale_snack': 'Tritikale'
        },
        'GRAIN_PORSION': {
            '1': 'Tatlı tabağı',
            '2': 'Küçük Yemek Tabağı',
            '3': 'Normal Yemek Tabağı',
            '4': 'Büyük Yemek Tabağı',
        },
        'BROADBEAN': {
            'kuruFasulye': 'Kuru Fasulye',
            'bezelye': 'Bezelye',
            'nohut': 'Nohut',
            'kirmiziMercimek': 'Kırmızı Mercimek',
            'borulce': 'Börülce',
            'barbunya': 'Barbunya',
            'soyaFasulyesi': 'Soya Fasulyesi',
            'bakla': 'Bakla',
        },
        'BROADBEAN_NOON': {
            'kuruFasulye_noon': 'Kuru Fasulye',
            'bezelye_noon': 'Bezelye',
            'nohut_noon': 'Nohut',
            'kirmiziMercimek_noon': 'Kırmızı Mercimek',
            'borulce_noon': 'Börülce',
            'barbunya_noon': 'Barbunya',
            'soyaFasulyesi_noon': 'Soya Fasulyesi',
            'bakla_noon': 'Bakla',
        },
        'BROADBEAN_EVENING': {
            'kuruFasulye_evening': 'Kuru Fasulye',
            'bezelye_evening': 'Bezelye',
            'nohut_evening': 'Nohut',
            'kirmiziMercimek_evening': 'Kırmızı Mercimek',
            'borulce_evening': 'Börülce',
            'barbunya_evening': 'Barbunya',
            'soyaFasulyesi_evening': 'Soya Fasulyesi',
            'bakla_evening': 'Bakla',
        },
        'BROADBEAN_SNACK': {
            'kuruFasulye_snack': 'Kuru Fasulye',
            'bezelye_snack': 'Bezelye',
            'nohut_snack': 'Nohut',
            'kirmiziMercimek_snack': 'Kırmızı Mercimek',
            'borulce_snack': 'Börülce',
            'barbunya_snack': 'Barbunya',
            'soyaFasulyesi_snack': 'Soya Fasulyesi',
            'bakla_snack': 'Bakla',
        },
        'BROADBEAN_PORSION': {
            '1': 'Tatlı tabağı',
            '2': 'Yemek Tabağı Normal',
            '3': 'Yemek Tabağı Büyük',
        },
        'OIL': {
            'zeytinAvakado': 'Zeytin yağı ve Avakado yağı',
            'aycicekDiger': 'Ayçiçek ve diğer bitki yağları',
            'hindistan': 'Hindistan cevizi yağı',
            'tereyagi': 'Tereyağı',
            'margarin': 'Margarin',
        },
        'OIL_NOON': {
            'zeytinAvakado_noon': 'Zeytin yağı ve Avakado yağı',
            'aycicekDiger_noon': 'Ayçiçek ve diğer bitki yağları',
            'hindistan_noon': 'Hindistan cevizi yağı',
            'tereyagi_noon': 'Tereyağı',
            'margarin_noon': 'Margarin',
        },
        'OIL_EVENING': {
            'zeytinAvakado_evening': 'Zeytin yağı ve Avakado yağı',
            'aycicekDiger_evening': 'Ayçiçek ve diğer bitki yağları',
            'hindistan_evening': 'Hindistan cevizi yağı',
            'tereyagi_evening': 'Tereyağı',
            'margarin_evening': 'Margarin',
        },
        'OIL_SNACK': {
            'zeytinAvakado_snack': 'Zeytin yağı ve Avakado yağı',
            'aycicekDiger_snack': 'Ayçiçek ve diğer bitki yağları',
            'hindistan_snack': 'Hindistan cevizi yağı',
            'tereyagi_snack': 'Tereyağı',
            'margarin_snack': 'Margarin',
        },
        'OIL_PORSION': {
            '1': '½ Çay Kaşığı',
            '2': '1 Çay Kaşığı',
            '3': '2 Çay Kaşığı',
            '4': '1 Tatlı Kaşığı',
            '5': '2 Tatlı Kaşığı',
            '6': '1 Yemek Kaşığı',
            '7': '2 Yemek Kaşığı',
        },
        'SPICE': {
            'tozBiber': 'Toz Biber',
            'pulBiber': 'Pul Biber',
            'kimyon': 'Kimyon',
            'yediTurlu': 'Yedi Türlü',
            'karabiber': 'Karabiber',
            'zencefil': 'Zencefil',
            'zerdecal': 'Zerdeçal',
            'biberiye': 'Biberiye',
            'sumak': 'Sumak',
            'kisnis': 'Kişniş',
            'corekotu': 'Çörekotu',
            'kekik': 'Kekik',
            'ketenTohumu': 'Keten Tohumu',
            'kori': 'Köri',
            'hashas': 'Haşhaş',
            'nane': 'Nane',
            'tarcin': 'Tarçın',
            'yenibahar': 'Yenibahar',
            'defneYapragi': 'Defne Yaprağı',
        },
        'SPICE_NOON': {
            'tozBiber_noon': 'Toz Biber',
            'pulBiber_noon': 'Pul Biber',
            'kimyon_noon': 'Kimyon',
            'yediTurlu_noon': 'Yedi Türlü',
            'karabiber_noon': 'Karabiber',
            'zencefil_noon': 'Zencefil',
            'zerdecal_noon': 'Zerdeçal',
            'biberiye_noon': 'Biberiye',
            'sumak_noon': 'Sumak',
            'kisnis_noon': 'Kişniş',
            'corekotu_noon': 'Çörekotu',
            'kekik_noon': 'Kekik',
            'ketenTohumu_noon': 'Keten Tohumu',
            'kori_noon': 'Köri',
            'hashas_noon': 'Haşhaş',
            'nane_noon': 'Nane',
            'tarcin_noon': 'Tarçın',
            'yenibahar_noon': 'Yenibahar',
            'defneYapragi_noon': 'Defne Yaprağı',
        },
        'SPICE_EVENING': {
            'tozBiber_evening': 'Toz Biber',
            'pulBiber_evening': 'Pul Biber',
            'kimyon_evening': 'Kimyon',
            'yediTurlu_evening': 'Yedi Türlü',
            'karabiber_evening': 'Karabiber',
            'zencefil_evening': 'Zencefil',
            'zerdecal_evening': 'Zerdeçal',
            'biberiye_evening': 'Biberiye',
            'sumak_evening': 'Sumak',
            'kisnis_evening': 'Kişniş',
            'corekotu_evening': 'Çörekotu',
            'kekik_evening': 'Kekik',
            'ketenTohumu_evening': 'Keten Tohumu',
            'kori_evening': 'Köri',
            'hashas_evening': 'Haşhaş',
            'nane_evening': 'Nane',
            'tarcin_evening': 'Tarçın',
            'yenibahar_evening': 'Yenibahar',
            'defneYapragi_evening': 'Defne Yaprağı',
        },
        'SPICE_SNACK': {
            'tozBiber_snack': 'Toz Biber',
            'pulBiber_snack': 'Pul Biber',
            'kimyon_snack': 'Kimyon',
            'yediTurlu_snack': 'Yedi Türlü',
            'karabiber_snack': 'Karabiber',
            'zencefil_snack': 'Zencefil',
            'zerdecal_snack': 'Zerdeçal',
            'biberiye_snack': 'Biberiye',
            'sumak_snack': 'Sumak',
            'kisnis_snack': 'Kişniş',
            'corekotu_snack': 'Çörekotu',
            'kekik_snack': 'Kekik',
            'ketenTohumu_snack': 'Keten Tohumu',
            'kori_snack': 'Köri',
            'hashas_snack': 'Haşhaş',
            'nane_snack': 'Nane',
            'tarcin_snack': 'Tarçın',
            'yenibahar_snack': 'Yenibahar',
            'defneYapragi_snack': 'Defne Yaprağı',
        },

        'SPICE_PORSION': {
            '1': '½ Çay Kaşığı',
            '2': '1 Çay Kaşığı',
            '3': '2 Çay Kaşığı',
            '4': '1 Tatlı Kaşığı',
        },
        'NUTS': {
            'ceviz': 'Ceviz',
            'badem': 'Badem',
            'findik': 'Fındık',
            'kaju': 'Kaju',
            'antepFistigi': 'Antep Fıstığı',
            'yerFistigi': 'Yer Fıstığı',
            'leblebi': 'Leblebi',
            'kabakCekirdegi': 'Kabak Çekirdeği',
            'ayCekirdek': 'Ay Çekirdek',
        },
        'NUTS_NOON': {
            'ceviz_noon': 'Ceviz',
            'badem_noon': 'Badem',
            'findik_noon': 'Fındık',
            'kaju_noon': 'Kaju',
            'antepFistigi_noon': 'Antep Fıstığı',
            'yerFistigi_noon': 'Yer Fıstığı',
            'leblebi_noon': 'Leblebi',
            'kabakCekirdegi_noon': 'Kabak Çekirdeği',
            'ayCekirdek_noon': 'Ay Çekirdek',
        },
        'NUTS_EVENING': {
            'ceviz_evening': 'Ceviz',
            'badem_evening': 'Badem',
            'findik_evening': 'Fındık',
            'kaju_evening': 'Kaju',
            'antepFistigi_evening': 'Antep Fıstığı',
            'yerFistigi_evening': 'Yer Fıstığı',
            'leblebi_evening': 'Leblebi',
            'kabakCekirdegi_evening': 'Kabak Çekirdeği',
            'ayCekirdek_evening': 'Ay Çekirdek',
        },
        'NUTS_SNACK': {
            'ceviz_snack': 'Ceviz',
            'badem_snack': 'Badem',
            'findik_snack': 'Fındık',
            'kaju_snack': 'Kaju',
            'antepFistigi_snack': 'Antep Fıstığı',
            'yerFistigi_snack': 'Yer Fıstığı',
            'leblebi_snack': 'Leblebi',
            'kabakCekirdegi_snack': 'Kabak Çekirdeği',
            'ayCekirdek_snack': 'Ay Çekirdek',
        },
        'NUTS_PROCESS': {
            '1': 'Tuzlu – Kavrulmuş (seçim kutusu)',
            '2': 'Tuzsuz - Kavrulmamış',
        },
        'NUTS_PORSION': {
            '1': '25 gr',
            '2': '50 gr',
            '3': '100 gr',
            '4': '200 gr',
        },
        'SURVED_FRUITS': {
            'kayisi_surved': 'Kuru Kayısı',
            'kudus_surved': 'Kudüs Kuru Hurma',
            'trabzon_surved': 'Trabzon Kuru Hurma',
            'incir_surved': 'Kuru İncir',
            'cilek_surved': 'Kuru Çilek',
            'erik_surved': 'Kuru Erik',
            'keci_surved': 'Keçi Boynuzu',
            'armut_surved': 'Kuru Armut',
            'elma_surved': 'Kuru Elma',
            'uzum_surved': 'Kuru Üzüm',
        },
        'SURVED_FRUITS_NOON': {
            'kayisi_surved_noon': 'Kuru Kayısı',
            'kudus_surved_noon': 'Kudüs Kuru Hurma',
            'trabzon_surved_noon': 'Trabzon Kuru Hurma',
            'incir_surved_noon': 'Kuru İncir',
            'cilek_surved_noon': 'Kuru Çilek',
            'erik_surved_noon': 'Kuru Erik',
            'keci_surved_noon': 'Keçi Boynuzu',
            'armut_surved_noon': 'Kuru Armut',
            'elma_surved_noon': 'Kuru Elma',
            'uzum_surved_noon': 'Kuru Üzüm',
        },
        'SURVED_FRUITS_EVENING': {
            'kayisi_surved_evening': 'Kuru Kayısı',
            'kudus_surved_evening': 'Kudüs Kuru Hurma',
            'trabzon_surved_evening': 'Trabzon Kuru Hurma',
            'incir_surved_evening': 'Kuru İncir',
            'cilek_surved_evening': 'Kuru Çilek',
            'erik_surved_evening': 'Kuru Erik',
            'keci_surved_evening': 'Keçi Boynuzu',
            'armut_surved_evening': 'Kuru Armut',
            'elma_surved_evening': 'Kuru Elma',
            'uzum_surved_evening': 'Kuru Üzüm',
        },
        'SURVED_FRUITS_SNACK': {
            'kayisi_surved_snack': 'Kuru Kayısı',
            'kudus_surved_snack': 'Kudüs Kuru Hurma',
            'trabzon_surved_snack': 'Trabzon Kuru Hurma',
            'incir_surved_snack': 'Kuru İncir',
            'cilek_surved_snack': 'Kuru Çilek',
            'erik_surved_snack': 'Kuru Erik',
            'keci_surved_snack': 'Keçi Boynuzu',
            'armut_surved_snack': 'Kuru Armut',
            'elma_surved_snack': 'Kuru Elma',
            'uzum_surved_snack': 'Kuru Üzüm',
        },
        # Simit, Poğaça, Börek vb. Unlu Ürünlerin Tüketimi
        'SURVED_FRUITS_PORSION': {
            '1': '25 gr',
            '2': '50 gr',
            '3': '100 gr',
            '4': '200 gr',
        },
        'PATTY': {
            '1': '1/2 Adet',
            '2': '1 Adet',
            '3': '2 Adet',
            '4': '3 Adet',
        },
        # Çikolata, Şekerleme, Pasta Tüketimi
        'CHOCOLATE': {
            '1': '1/4 Adet',
            '2': '1/2 Adet',
            '3': '1 Adet',
            '4': '2 Adet',
            '5': '3 Adet',
        },
        # Tatlı Tüketimi (baklava, şöbiyet, kadayıf vb.)
        'DESSERT': {
            '1': '1 Dilim',
            '2': '2 Dilim',
            '3': '3 Dilim',
            '4': '4 Dilim',
            '5+': '5+ Dilim',
        },
        'SALT_CHOICE': {
            '1': 'Kaya/Himalaya/Deniz',
            '2': 'Sofra Tuzu (İyotlu)',
        },
        'SALT_PORSION': {
            '1': '1/2 Çay Kaşığı',
            '2': '1 Çay Kaşığı',
            '3': '2 Çay Kaşığı',
            '4': '3+ Çay Kaşığı',
        },
        'WATER': {
            '1': '1/2  Litre',
            '2': '1 Litre',
            '3': '2 Litre',
            '4': '3 Litre',
            '5': '4 Litre',
            '7': '4+ Litre',
        },
        'COFFEE_TEA': {
            '1': '1 Fincan',
            '2': '2-3 Fincan',
            '4': '4-5 Fincan',
            '5': '6+ Fincan',
        },
        'MILK_YOGHURT': {
            '1': '1/2 Kase',
            '2': '1 Kase',
            '3': '2-3 Kase',
        },
        # Gazlı İçecek Tüketimi (Kola, Fanta, Soda vb.)
        'SOOT_DRINKS': {
            '1': '1/2 Bardak',
            '2': '1 Bardak',
            '3': '2-3 Bardak',
            '4': '4+ Bardak',
        },
        'JUICE': {
            '1': '1/2 Bardak',
            '2': '1 Bardak',
            '3': '2-3 Bardak',
        },
        'ALCOHOL': {
            '1': '1/2 Kadeh',
            '2': '1 Kadeh',
            '3': '2-3 Kadeh',
        },
        'CIGARET': {
            '1': '1-5 Adet',
            '2': '6-10 Adet',
            '3': '11-20 Adet',
            '4': '20+ Adet',
        },
        # Besin Takviyesi Tüketimi
        'FOOD': {
            'd': 'D Vitamini',
            'c': 'C Vitamini',
            'b': 'B Vitamini',
            'multi': 'Multi-vitamin',
            'bagisiklik': 'Bağışıklık güçlendiriciler',
            'demir': 'Demir',
            'cinko': 'Çinko',
            'kalsiyum': 'Kalsiyum',
            'kollajen': 'Kollajen',
            'glucosamin': 'Glucosamin türevleri',
            'aminoasit': 'Aminoasit türevleri',
            'l': 'L-Carnitin',
            'cla': 'CLA',
            'chromium': 'Chromium Pikolinat',
            'omega': 'Omega-3',
            'q': 'Q-Enzim 10',
            'protein': 'Protein tozları',
            'bcaa': 'BCAA',
            'glutamin': 'Glutamin',
            'kilo': 'Kilo aldırıcılar',
            'kilo1': 'Kilo aldırıcılar',
        },
        'FOOD_NOON': {
            'd_noon': 'D Vitamini',
            'c_noon': 'C Vitamini',
            'b_noon': 'B Vitamini',
            'multi_noon': 'Multi-vitamin',
            'bagisiklik_noon': 'Bağışıklık güçlendiriciler',
            'demir_noon': 'Demir',
            'cinko_noon': 'Çinko',
            'kalsiyum_noon': 'Kalsiyum',
            'kollajen_noon': 'Kollajen',
            'glucosamin_noon': 'Glucosamin türevleri',
            'aminoasit_noon': 'Aminoasit türevleri',
            'l_noon': 'L-Carnitin',
            'cla_noon': 'CLA',
            'chromium_noon': 'Chromium Pikolinat',
            'omega_noon': 'Omega-3',
            'q_noon': 'Q-Enzim 10',
            'protein_noon': 'Protein tozları',
            'bcaa_noon': 'BCAA',
            'glutamin_noon': 'Glutamin',
            'kilo_noon': 'Kilo aldırıcılar',
            'kilo1_noon': 'Kilo aldırıcılar',
        },
        'FOOD_EVENING': {
            'd_evening': 'D Vitamini',
            'c_evening': 'C Vitamini',
            'b_evening': 'B Vitamini',
            'multi_evening': 'Multi-vitamin',
            'bagisiklik_evening': 'Bağışıklık güçlendiriciler',
            'demir_evening': 'Demir',
            'cinko_evening': 'Çinko',
            'kalsiyum_evening': 'Kalsiyum',
            'kollajen_evening': 'Kollajen',
            'glucosamin_evening': 'Glucosamin türevleri',
            'aminoasit_evening': 'Aminoasit türevleri',
            'l_evening': 'L-Carnitin',
            'cla_evening': 'CLA',
            'chromium_evening': 'Chromium Pikolinat',
            'omega_evening': 'Omega-3',
            'q_evening': 'Q-Enzim 10',
            'protein_evening': 'Protein tozları',
            'bcaa_evening': 'BCAA',
            'glutamin_evening': 'Glutamin',
            'kilo_evening': 'Kilo aldırıcılar',
            'kilo1_evening': 'Kilo aldırıcılar',
        },
        'FOOD_SNACK': {
            'd_snack': 'D Vitamini',
            'c_snack': 'C Vitamini',
            'b_snack': 'B Vitamini',
            'multi_snack': 'Multi-vitamin',
            'bagisiklik_snack': 'Bağışıklık güçlendiriciler',
            'demir_snack': 'Demir',
            'cinko_snack': 'Çinko',
            'kalsiyum_snack': 'Kalsiyum',
            'kollajen_snack': 'Kollajen',
            'glucosamin_snack': 'Glucosamin türevleri',
            'aminoasit_snack': 'Aminoasit türevleri',
            'l_snack': 'L-Carnitin',
            'cla_snack': 'CLA',
            'chromium_snack': 'Chromium Pikolinat',
            'omega_snack': 'Omega-3',
            'q_snack': 'Q-Enzim 10',
            'protein_snack': 'Protein tozları',
            'bcaa_snack': 'BCAA',
            'glutamin_snack': 'Glutamin',
            'kilo_snack': 'Kilo aldırıcılar',
            'kilo1_snack': 'Kilo aldırıcılar',
        },
    },

    # Eudaimonia Sağlıklı Yaşam Semptom Formu
    'EUDAIMONIA': {
        'MENTAL': {
            'consciousness': 'Bilinç bulanıklığı',
            'memory': 'Hafıza sorunları',
            'decision': 'Karar verme güçlükleri',
            'talk': 'Konuşma bozuklukları',
            'learning': 'Öğrenme ve dikkat sorunları',
            'koordinatif': 'Koordinatif becerilerde zayıflık',
        },
        'SKIN': {
            'acne': 'Akne artışı',
            'drySkin': 'Kuru cilt',
            'eczema': 'Ürtiker veya egzama görülmesi',
            'akut': 'Akut ateş basması',
            'excessiveSweating': 'Aşırı terleme',
        },
        'HEAD': {
            'headache': 'Baş ağrısı',
            'migraine': 'Migren atağı',
            'fainting': 'Bayılma',
            'sleep': 'Uyku Sorunu',
        },
        'EYES': {
            'eyelids': 'Şişmiş veya kızarmış göz kapakları',
            'blackEyes': 'Siyah göz etrafı halka oluşumu',
            'swollenEyes': 'Şişmiş gözler',
            'visionProblems': 'Görme sorunları',
            'wateryEyes': 'Gözlerde sulanma ve kaşıntı',
        },
        'NOSE': {
            'nasalCongestion': 'Burun tıkanıklığı ve doluluk hissi',
            'sinus': 'Sinüs sorunları',
            'mukus': 'Aşırı mukus birikimi hissi',
            'Sneeze': 'Hapşırma sıklığında artış',
        },
        'EAR': {
            'earItching': 'Kulaklarda kaşıntı ve huzursuzluk',
            'earInfection': 'Kulak enfeksiyonu ve ağrıları',
            'earDischarge': 'Kulak akıntısı',
            'tinnitus': 'Kulak çınlaması ve işitme kaybı',
        },
        'MOUTH': {
            'chronic': 'Kronik öksürük',
            'throat': 'Boğaz temizleme isteğinde artış',
            'lip': 'Dudak şişkinliği',
            'mouthAft': 'Ağızda aft artışları',
        },
        'LUNGS': {
            'chest': 'Göğüste sıkışma hissi',
            'asthma': 'Astım – Bronşit',
            'shortnessBreath': 'Nefes Darlığı',
            'breath': 'Nefes almada güçlük',
        },
        'HEART': {
            'heartRhythm': 'Kalpte ritim bozukluğu',
            'heartPalpitations': 'Kalp çarpıntısı',
            'chestPain': 'Göğüs ağrısı',
        },
        'GASTROINTESTINE': {
            'nausea': 'Bulantı hissinde artış',
            'vomiting': 'Kusma',
            'diarrhea': 'İshal',
            'constipation': 'Kabızlık',
            'swelling': 'Şişkinlik ve hazımsızlık hissi',
            'burping': 'Geğirme ve gaz çıkarma sorunları',
            'stomach': 'Mide yanması',
            'abdominalIntestine': 'Karın – Bağırsak bölgesi ağrıları/krampları',
        },
        'JOINTS': {
            'jointPain': 'Tekrarlayan eklem ağrısı ve sızıları',
            'musclePain': 'Tekrarlayan kas ağrısı ve sızıları',
            'artrit': 'Artrit (romatizma) tanısı olmak',
            'muscleStiffness': 'Tekrarlayan kas tutulmaları',
            'muscleJoint': 'Kas-Eklem güçsüzlüğü ve yorgunluk hissi',
        },
        'BODYWEIGHT': {
            'weight': 'Kilo vermede güçlük',
            'constantlyEating': 'Sürekli yeme isteği (aşerme)',
            'weakness': 'Zayıflık (aşırı düzeyde)',
            'kompulsif': 'Kompülsif (takıntılı) yeme bozukluğu',
            'edema': 'Ödem ve şişkinlik hissi',
        },
        'ENERGY': {
            'tiredness': 'Sürekli yorgunluk hissi',
            'numbness': 'Uyuşukluk',
            'hyperactivity': 'Hiperaktivite',
            'feelingUneasy': 'Huzursuzluk hissi',
        },
        'FEELINGS': {
            'anksiyete': 'Anksiyete hissi',
            'depression': 'Depresyon hissi',
            'emotion': 'Duygu durum değişiklikleri',
            'irritability': 'Asabiyet ve tahammülsüzlük artışı',
            'susceptibility': 'Alınganlık ve hassaslık gelişimi',
        },
        'MEDICINE': {
            'steroid': 'Steroid ihtiva eden ilaçlar',
            'nonSteroid': 'Non-Steroid Anti-İnflamatuar ilaçlar',
            'antiRomatizmal': 'Anti-Romatizmal İlaçlar',
            'antiBiyotik': 'Anti-Biyotikler',
        },
        'STRORY': {

            'otoImmun': 'Anne-Baba oto-immun hastalık tanısı',
            'otoImmun1': '1.-2. Derece akrabalarda oto-immun hastalık tanısı',
            'cesareanSection': 'Sezaryen doğum ile doğmak',
            'breastMilk': 'Anne sütü almamak',
            'dairyProducts': 'Süt ve süt ürünlerini sıklıkla tüketmek',
            'earInflammation1': 'Bebeklik, çocukluk ve gençlik dönemlerinde yoğun kulak iltihaplanması',
            'birthControl': 'Doğum kontrol hapları kullanmak',

        },
        'OTHERSYMPTOMS': {
            'illness': 'Sık sık hastalanma',
            'openInfection': 'Enfeksiyona açık olma',
            'emergencyUrine': 'Sık sık acil idrara çıkma',
            'genital': 'Genital bölgede kaşıntı ve akıntı',
            'hemoroit': 'Anal bölgede kaşıntı ve hemoroit',
            'urineColor': 'Koyu idrar rengi',
            'smellUrine': 'Ağır idrar kokusu',
            'smellFeces': 'Ağır dışkı kokusu',
            'form': 'Dışkı formunun parçalı ve dağınık olması',
            'often': 'Dışkılama sıklığında dengesizlik',
        },

    }
}
