ATHLETIC = {
    'BODY': {
        'SURRONDING': {
            'shoulder': 'Omuz',
            'chest': 'Göğüs',
            'biseps': 'Biseps',
            'wrist': 'El Bileği',
            'waist': 'Bel Çevresi',
            'hip': 'Kalça Çevresi',
            'knee': 'Diz Çevresi',
            'upper_leg': 'Üst Bacak',
            'gastrocnemius': 'Gastrocnemius',
            'ankle': 'Ayak Bileği',
        },
        'BODYOIL': {
            'THREE': {
                'MAN': {
                    'man3ch': 'Chest',
                    'man3tri': 'Triceps',
                    'man3sub': 'Subscapula',
                },
                'WOMAN': {
                    'woman3tri': 'Triceps',
                    'woman3abd': 'Abdomen',
                    'woman3sub': 'Suprailiac',
                },
            },
            'SEVEN': {
                'MAN': {
                    'man7ch': 'Chest',
                    'man7tr': 'Triceps',
                    'man7sub': 'Subscapula',
                    'man7sic': 'Suprailiac',
                    'man7mid': 'Midaxillary',
                    'man7abd': 'Abdomen',
                    'man7th': 'Thigh',
                },
                'WOMAN': {
                    'woman7ch': 'Chest',
                    'woman7tri': 'Triceps',
                    'woman7sub': 'Subscapula',
                    'woman7sic': 'Suprailiac',
                    'woman7mid': 'Midaxillary',
                    'woman7abd': 'Abdomen',
                    'woman7th': 'Thigh',
                },
            },
        },
        'SOMATOTIP': {
            'humerus': 'Humerus Bikondil',
            'femur': 'Femur Bikondil',
            'corrected_biseps': 'Düzeltilmiş Biseps Çevre',
            'corrected_gastrocnemius': 'Düzeltilmiş Gastrocnemius Çevre',
        },
    },
    'AEROBIK': {
        'VOMAKS': {
            'ir1_test': 'Yo Yo IR-1 Testi  (m)',
            'ir2_test': 'Yo Yo IR-2 Testi  (m)',
            'ift_test': '30-15 IFT Testi',
            'rast_test_dist': 'RAST Test (Mesafe)',
            'rast_test_time': 'RAST Test (Zaman)',
            'bruce_protokol': 'Bruce Protokolü (dk)',
            'cooper': 'Cooper (12 dk)  Testi (m)',
            'shuttle_test': '20 m Mekik Testi (seviye)',
            'step_test': 'Basamak Testi (atım/dk)',
        },
        'LAKTAT': {
            'bla': 'BLa',
            'laktat_heart_rate': 'Kalp Atım Hızı',
            'vo2maks': 'VO2maks',
        },
        'ANEROBIK': {
            'WINGATE': {
                'maximal_power': 'Maksimal Güç (watt)',
                'average_power': 'Ortalama Güç (watt)',
                'tiredness': 'Yorgunluk İndeksi (%)',
            },
            'LEAP': {
                'VERTICAL': {
                    'vertical_leap1': 'Dikey Sıçrama(cm) 1:',
                    'vertical_leap2': 'Dikey Sıçrama(cm) 2:',
                    'vertical_leap3': 'Dikey Sıçrama(cm) 3:',
                },
                'HORIZANTAL': {
                    'horizantal_leap1': 'Yatay Sıçrama (cm) 1:',
                    'horizantal_leap2': 'Yatay Sıçrama (cm) 2:',
                    'horizantal_leap3': 'Yatay Sıçrama (cm) 3:',
                },
            },
            'HEALTH': {
                'distance1': 'Mesafe1-(cm)',
                'distance2': 'Mesafe2-(cm)',
                'distance3': 'Mesafe3-(cm)',
            },
            'LINEAR': {
                'five1': '5m (1)',
                'five2': '5m (2)',
                'five3': '5m (3)',
                'ten1': '10m (1)',
                'ten2': '10m (2)',
                'ten3': '10m (3)',
                'twenty1': '20m (1)',
                'twenty2': '20m (2)',
                'twenty3': '20m (3)',
                'thirty1': '30m (1)',
                'thirty2': '30m (2)',
                'thirty3': '30m (3)',
                'fourty1': '40m (1)',
                'fourty2': '40m (2)',
                'fourty3': '40m (3)',
            },
            'AGILITY': {
                'illinois1': 'İllinois Çeviklik Testi',
                'illinois2': 'İllinois Çeviklik Testi',
                'illinois3': 'İllinois Çeviklik Testi',
                'tLine1': '1-T Line Testi',
                'tLine2': '2-T Line Testi',
                'tLine3': '3-T Line Testi',
                'koni_test1': '3 Koni Testi',
                'koni_test2': '3 Koni Testi',
                'koni_test3': '3 Koni Testi',
                'edgren1': 'Edgren Side Testi ',
                'edgren2': 'Edgren Side Testi ',
                'edgren3': 'Edgren Side Testi ',
                'agility1': '505 Agility Testi',
                'agility2': '505 Agility Testi',
                'agility3': '505 Agility Testi',
                'pro_agility1': 'Pro-Agility Test (5-10-5)',
                'pro_agility2': 'Pro-Agility Test (5-10-5)',
                'pro_agility3': 'Pro-Agility Test (5-10-5)',
                'heksogen1': 'Heksogen Testi ',
                'heksogen2': 'Heksogen Testi ',
                'heksogen3': 'Heksogen Testi ',
            },
        },
    },
    'EYEBROW': {
        'HAND': {
            'right1': '1-Sağ(kg)',
            'right2': '2-Sağ(kg)',
            'right3': '3-Sağ(kg)',
            'left1': '1-Sol(kg)',
            'left2': '2-Sol(kg)',
            'left3': '3-Sol(kg)',
        },
        'LOKAL': {
            'pushup': 'Push-up(tekrar)',
            'curlup': 'Curl-up (tekrar)',
            'bench_press': 'Bench Press (tekrar)',
            'pullup': 'Pull-up (tekrar)',
            'modified_pullup': 'Modified Pull-up (tekrar)',
            'flexed': 'Flexed Arm Hang (süre)',
        },
        'MT': {
            'squat_mt': '6 MT (Squat - kg)',
            'lifting_squat': 'Kaldırma Hızı (Squat - sn)',
            'bench_mt': ' 6 MT (Bench press - kg)',
            'lifting_bench': 'Kaldırma Hızı (Bench press - sn)',
            'kuadriseps60': 'Kuadriseps (60°)',
            'hamstring60': 'Hamstring (60°)',
            'kuadriseps180': 'Kuadriseps (180°)',
            'hamstring180': 'Hamstring (180°)',
            'kuadriseps300': 'Kuadriseps (300°)',
            'hamstring300': 'Hamstring (300°)',
        },
    },
    'MOVEMENT': {
        'OVERHEAD': {
            'normal_overhead': 'Normal',
            'glenohumeral_overhead': 'Glenohumeral İmmobilite',
            'torakal_overhead': 'Torakal İmmobilite',
            'dinamic_overhead': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'leg_overhead': 'Ayak Bileği İmmobilitesi',
            'knee_overhead': 'Diz İnstabilitesi',
            'hip_overhead': 'Kalça İmmobilitesi',
            'balance_overhead': 'Denge Kayıpları (zayıf motor kontrol)',
            'ache_overhead': 'Ağrı Varlığı',
        },
        'SQUAT': {
            'normal_squat': 'Normal',
            'torakal_squat': 'Torakal İmmobilite',
            'dinamic_squat': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'leg_squat': 'Ayak Bileği İmmobilitesi',
            'knee_squat': 'Diz İnstabilitesi',
            'hip_squat': 'Kalça İmmobilitesi',
            'balance_squat': 'Denge Kayıpları (zayıf motor kontrol)',
            'ache_squat': ' Ağrı Varlığı',
        },
        'BRIDGE': {
            'normal_bridge': 'Normal',
            'hip_bridge': 'Kalça Fleksiyon Artışı',
            'balance_bridge': 'Denge Kayıpları (zayıf motor kontrol)',
            'dinamic_bridge': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'knee_bridge': 'Diz İnstabilitesi',
            'hip_immobilit': 'Kalça İmmobilitesi',
            'hamstring_bridge': 'Hamstring Gerginliği',
            'kuadriseps_bridge': 'Kuadriseps Gerginliği',
            'ache_bridge': 'Ağrı Varlığı',
        },
        'LUNGE': {
            'normal_lunge': 'Normal',
            'patello_lunge': 'Patello-Femoral Kayma',
            'over_lunge': 'Over-pronasyon',
            'fleksiyon_lunge': 'Gövde Fleksiyon Artışı',
            'balance_lunge': 'Denge Kayıpları (zayıf motor kontrol)',
            'dinamic_lunge': 'Tüm Vücut Dinamik İmmobilite Varlığı',
            'leg_lunge': 'Ayak Bileği İmmobilitesi',
            'knee_lunge': 'Diz İnstabilitesi',
            'hip_lunge': ' Kalça İmmobilitesi',
            'ache_lunge': 'Ağrı Varlığı',
        },
        'TRUNK': {
            'normal_trunk': 'Normal',
            'core_trunk': 'Core Stabilizasyon Kaybı',
            'skapula_trunk': 'Skapula İnstabilizasyon',
            'hip_trunk': 'Kalça İmmobilitesi',
            'lomber_trunk': 'Lomber Lordoz Artışı',
            'balance_trunk': 'Denge Kayıpları (zayıf motor kontrol)',
            'ache_trunk': 'Ağrı Varlığı',
        },
        'SHOULDER': {
            'normal_shoulder': 'Normal',
            'core_shoulder': 'Core Stabilizasyon Kaybı',
            'skapula_shoulder': 'Skapulo-Torasik İnstabilite - İmmobilite',
            'gleno_shoulder': 'Gleno-Humeral Disfonksiyon',
            'balance_shoulder': 'Denge Kayıpları (zayıf motor kontrol)',
            'ache_shoulder': 'Ağrı Varlığı',
        },
        'ACTIVE': {
            'normal_active': 'Normal',
            'pelvik_aktive': 'Pelvik Kontrol Kaybı',
            'hip_active': 'Kalça İmmobilitesi (Karşı taraf)',
            'hip_ekstansiyon_active': 'Kalça Ekstansiyon Disfonksiyonu',
            'hamstring_active': 'Hamstring Gerginliği',
            'lomber_active': 'Lomber Lordoz Artışı',
            'rotasyon_active': 'Artmış Gövde Rotasyon (kaldırılan bacak yönüne)',
            'ache_active': 'Ağrı Varlığı (Sakro-iliak eklem)',
        },
        'ROTARY': {
            'normal_rotary': 'Normal',
            'core_rotary': 'Core İnstabilitesi',
            'body_rotary': 'Gövde İnstabilitesi',
            'hip_rotary': ' Kalça-Diz-Omuz İmmobilitesi',
            'balance_rotary': 'Denge Kayıpları (zayıf motor kontrol)',
            'ache_rotary': 'Ağrı Varlığı',
        },
        'FRONT': {
            'normal_front': 'Normal',
            'pelvisin_front': ' Pelvisin Aşağı Çökmes',
            'core_front': 'Coreİnstabilitesi',
            'body_front': 'Gövde Hizalama Sorunları',
            'arm_front': 'Kol-Omuz İnstabilitesi',
            'ache_front': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'SIDE': {
            'normal_side': 'Normal',
            'pelvisin_side': ' Pelvisin Aşağı Çökmesi',
            'core_side': 'Core İnstabilitesi',
            'body_side': 'Gövde Hizalama Sorunları',
            'leg_side': 'Ayak İnstabilitesi',
            'arm_side': 'Kol-Omuz İnstabilitesi',
            'ache_side': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'FLEKSOR': {
            'normal_fleksor': 'Normal',
            'body_fleksor': 'Gövdenin Geriye Kayması',
            'core_fleksor': 'Core İnstabilitesi',
            'body_line_fleksor': 'Gövde Hizalama Sorunları',
            'hamstring_fleksor': 'Hamstring Gerginliği',
            'kuadriseps_fleksor': 'Kuadriseps Gerginliği',
            'leg_fleksor': 'Ayak İnstabilitesi',
            'ache_fleksor': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'EKSTANSOR': {
            'normal_extansor': 'Normal',
            'body_extansor': 'Gövdenin Öne Kayması',
            'core_extansor': ' Core İnstabilitesi',
            'body_line_extansor': 'Gövde Hizalama Sorunları',
            'lomber_extansor': 'Lomber Lordoz Artışı',
            'hamstring_extansor': 'Hamstring Gerginliği',
            'kuadriseps_extansor': 'Kuadriseps Gerginliği',
            'ache_extansor': 'Ağrı Varlığı (Lomber Omurga)',
        },
        'BALANCE': {
            'OPEN': {
                'open1': 'Süre 1',
                'open2': 'Süre 2',
                'open3': 'Süre 3',
            },
            'CLOSE': {
                'close1': 'Süre 1',
                'close2': 'Süre 2',
                'close3': 'Süre 3',
            },
        },
        'STAR': {
            'THREEDIRECT': {
                'anterior': 'Anterior (cm)',
                'postero': 'Postero-medial (cm)',
                'postero_lateral': 'Postero-lateral (cm)',
            },
            'SEVENDIRECT': {
                'all_anterior': 'Anterior (cm)',
                'lateral': 'Antero-lateral (cm)',
                'medial': 'Antero-media (cm)',
                'all_lateral': 'Lateral (cm)',
                'all_medial': 'Medial (cm)',
                'posterior': 'Posterior-medial (cm)',
                'postero_medial': 'Postero-lateral (cm)',
                'all_postero_lateral': 'Postero-lateral (cm)',
            },
        },
        'ERROR': {
            'two_leg': 'Sabit Zemin Çift Ayak(Hata Sayısı)',
            'non_dominant': 'Sabit Zemin Non-Dominant Bacak(Hata Sayısı)',
            'tandem': 'Sabit Zemin Tandem(Hata Sayısı)',
            'two_leg1': 'Hareketli Zemin Çift Ayak(Hata Sayısı)',
            'non_dominant1': 'Hareketli Zemin Non-Dominant Bacak(Hata Sayısı)',
            'tandem1': 'Hareketli Zemin Tandem(Hata Sayısı)',
        },
        'MODIFIED': {
            'skor1': 'Skor 1',
            'skor2': 'Skor 2',
            'skor3': 'Skor 3',
        },
    },
    'METABOLIC': {
        'GLUCOSE': {
            'blood_sugar':'Açlık Kan Şekeri',
            'insulin':'Açlık Insülin',
            'hb1ac':'HB1AC',
        },
        'LIPID': {
            'ldl':'LDL',
            'hdl':'HDL',
            'trigliserit':'Trigliserit',
            'kolesterol':'Total Kolesterol',
        },
        'PRESS': {
            'sistolik':'Sistolik Kan Basıncı',
            'diastolik':'Diastolik Kan Basıncı',
        },

    }
}
