CORRECTIVE = {
    'MAIN': {
        'LEVEL': {
            '1': 'Düşük Seviye',
            '2': 'Orta Seviye',
            '3': 'Yüksek Seviye',
        },
        'PURPOSE': {
            'forward1': 'Forward Head Posture',
            'servikal1': 'Servikal Lordoz Artışı',
            'round1': 'Round Shoulder Sendromu',
            'elevated1': 'Elevated Scapula Sendromu',
            'protracted1': 'Protracted Scapula Sendromu',
            'internal1': 'Internal Arm Sendromu',
            'torakal1': 'Torakal Kifoz Artışı',
            'lomber1': 'Lomber Lordoz Artışı',
            'anterior1': 'Anterior Pelvik Tilt Sendromu',
            'genu1': 'Genu Valgus Sendromu ',
            'dorsi1': 'Dorsi-fleksiyon Kaybı',
            'over1': 'Over-pronasyon Sendromu',
        },
        'DAYS': {
            'monday': 'Pazartesi',
            'tuesday': 'Salı',
            'wednesday': 'Çarşamba',
            'thursday': 'Perşembe',
            'friday': 'Cuma',
            'saturday': 'Cumartesi',
            'sunday': 'Pazar',
        },
        'TRAININGTIME': {
            '1': '10 dk',
            '2': '15 dk',
            '3': '30 dk',
            '4': '45 dk',
            '5': '60 dk',
            '6': '90 dk',
            '7': '120 dk',
        },
        'TEMPO': {
            '1': '101',
            '2': '102',
            '3': '201',
            '4': '202',
            '5': '203',
            '6': '302',
            '7': '303',
            '8': '304',
            '9': '403',
            '10': '404',
        },
        'SET': {
            '1': '30 sn',
            '2': '60 sn',
            '3': '90 sn',
            '4': '120 sn',
            '5': '3 dk',
            '6': '5 dk',
        },
        'MOVEMENT': {
            '1': '1 dk',
            '2': '2 dk',
            '3': '3 dk',
            '4': '4 dk',
            '5': '5 dk',
        },
        'FILE': {
            '1': 'Günlük',
            '2': 'Haftalık',
            '3': 'Aylık',
            '4': '3 Aylık',
            '5': '6 Aylık',
            '6': 'Yıllık',
        },
    },
    'STRATEGIES': {
        'OVERPRONASYON': {
            'SMR': {
                'ovr_smr_Mini': 'Bottom of Foot Glide w/Mini Ball ',
                'ovr_smr_Foam': 'Bottom of Foot Glide w/Foam Roller',
                'ovr_smr_Bottom': 'Seated Bottom of Foot Glide w/Miniball-Foam Roller',
                'ovr_smr_OneStraight': 'One-Straight Leg T.A. SMR w/Foam Roller',
                'ovr_smr_TA': 'Seated T.A. SMR w/Mini Ball',
                'ovr_smr_Alternating': 'Alternating T.A SMR w/Foam Roller',
                'ovr_smr_crs_TA': 'Cross Leg T.A. SMR w/Foam Roller',
                'ovr_smr_OneLeg': 'One-Leg Calf SMR w/Foam Roller',
                'ovr_smr_crs_Calf': 'Cross Leg Calf SMR w/Foam Roller',
                'ovr_smr_Two': 'Two Leg On Foam Roller Calf SMR',
                'ovr_smr_Calf': 'Calf SMR W/Mini',
            },
            'STRETCHING': {
                'ovr_str_Bear': 'Bear Position Big Toe Stretch',
                'ovr_str_Foot': 'Foot on Wall Calf Stretch',
                'ovr_str_Quadruped': 'Quadruped Rock Back - Big Toe Ext. Bias ',
                'ovr_str_std_Extensor1': 'Seated Toe Extensor Stretch',
                'ovr_str_std_Extensor2': 'Seated Toe Extensor and Foot Everter Stretch',
                'ovr_str_std_Extensor3': 'Seated Toe Extensor and Foot Inverter Stretch',
                'ovr_str_std_Flexor1': 'Seated Toe Flexor Stretch ',
                'ovr_str_std_Flexor2': 'Seated Toe Flexor and Foot Everter Stretch',
                'ovr_str_std_Flexor3': 'Seated Toe Flexor and Foot Inverter Stretch',
                'ovr_str_Standing': 'Standing Toe Extensor Stretch',
                'ovr_str_Single': 'Single Plantar Flexor Stretch',
            },
            'FORCE': {
                'ovr_frc_Isometric': 'Isometric March on Heel',
                'ovr_frc_dr_Taps': 'Dorsiflexor Taps',
                'ovr_frc_dr_Curl': 'Dorsiflexor Curl w/Band',
                'ovr_frc_Deep': 'Deep Squat & Ankle Mobility',
                'ovr_frc_Standing': 'Standing Unilateral Knee Extension',
                'ovr_frc_Kneeling': '½ Kneeling Dorsiflexion',
                'ovr_frc_Unilateral': 'Unilateral Heel Drops',
                'ovr_frc_Posterior': 'Posterior Bounce and Touch Down',
                'ovr_frc_Lateral': 'Lateral Bounce and Touch Down',
                'ovr_frc_OneLeg': 'One Leg Rotational Stability',
                'ovr_frc_Ankle': 'Ankle Lift and Forward Step',
                'ovr_frc_Calf': 'Calf Raise',
                'ovr_frc_elv_Calf': 'Elevated Calf Raise',
                'ovr_frc_sngl_Elevated': 'Single Leg Elevated Calf Raise',
                'ovr_frc_Active': 'Active Calf Rolling w/Foam Roller',
                'ovr_frc_sngl_Reach': 'Single Reach with Band Feedback',
                'ovr_frc_Bent': 'Bent Knee Heel Raises w/Ball',
                'ovr_frc_sngl_Passes': 'Single Leg Passes on Foam',
                'ovr_frc_Banded': 'Banded Inversion',
                'ovr_frc_Toe': 'Toe Raise',
                'ovr_frc_elv_Hallucis': 'Elevated Hallucis Flexion',
                'ovr_frc_Bear': 'Bear Position Big Toe Stretch (Mobil)',
                'ovr_frc_ft_Wall': 'Foot on Wall Calf Stretch (Mobil)',
                'ovr_frc_Quadruped': 'Quadruped Rock Back- Big Toe Ext. Bias',
                'ovr_frc_Sole': 'Sole to Sole',
                'ovr_frc_ft_ArchUp': 'Foot Arch-Up',
                'ovr_frc_sngl_ArchUp': 'Single Leg Arch-Up',
                'ovr_frc_Clam': 'Clam Shells ',
                'ovr_frc_ToeTowel': 'Toe-Towel Flexion',
                'ovr_frc_ToSpread': 'Toe Spread',
                'ovr_frc_ToeObject': 'Toe-Object Pickup',
                'ovr_frc_Self': 'Self Big Toe Mobilization',

            },
        },
        'DORSI': {
            'SMR': {
                'drs_smr_OneStraight': 'One-Straight Leg T.A. SMR w/Foam Roller',
                'drs_smr_Seated': 'Seated T.A. SMR w/Mini Ball',
                'drs_smr_Alternating': 'Alternating T.A SMR w/Foam Roller',
                'drs_smr_Cross': 'Cross Leg T.A. SMR w/Foam Roller',
            },
            'STRETCHING': {
                'drs_str_Bear': 'Bear Position Big Toe Stretch',
                'drs_str_Foot': 'Foot on Wall Calf Stretch',
                'drs_str_Quadruped': 'Quadruped Rock Back - Big Toe Ext. Bias ',
                'drs_str_std_Extensor1': 'Seated Toe Extensor Stretch',
                'drs_str_std_Extensor2': 'Seated Toe Extensor and Foot Everter Stretch',
                'drs_str_std_Extensor3': 'Seated Toe Extensor and Foot Inverter Stretch',
                'drs_str_std_Flexor1': 'Seated Toe Flexor Stretch ',
                'drs_str_std_Flexor2': 'Seated Toe Flexor and Foot Everter Stretch',
                'drs_str_std_Flexor3': 'Seated Toe Flexor and Foot Inverter Stretch',
                'drs_str_Standing': 'Standing Toe Extensor Stretch',
                'drs_str_Single': 'Single Plantar Flexor Stretch',
            },
            'FORCE': {
                'drs_frc_Isometric': 'Isometric March on Heel',
                'drs_frc_dr_Taps': 'Dorsiflexor Taps',
                'drs_frc_dr_Curl': 'Dorsiflexor Curl w/Band',
                'drs_frc_Deep': 'Deep Squat & Ankle Mobility',
                'drs_frc_Standing': 'Standing Unilateral Knee Extension',
                'drs_frc_Kneeling': '½ Kneeling Dorsiflexion',
                'drs_frc_Unilateral': 'Unilateral Heel Drops',
                'drs_frc_Posterior': 'Posterior Bounce and Touch Down',
                'drs_frc_Lateral': 'Lateral Bounce and Touch Down',
                'drs_frc_OneLeg': 'One Leg Rotational Stability',
                'drs_frc_Ankle': 'Ankle Lift and Forward Step',
                'drs_frc_Calf': 'Calf Raise',
                'drs_frc_elv_Calf': 'Elevated Calf Raise',
                'drs_frc_sngl_Elevated': 'Single Leg Elevated Calf Raise',
                'drs_frc_Active': 'Active Calf Rolling w/Foam Roller',
                'drs_frc_sngl_Reach': 'Single Reach with Band Feedback',
                'drs_frc_Bent': 'Bent Knee Heel Raises w/Ball',
                'drs_frc_sngl_Passes': 'Single Leg Passes on Foam',
                'drs_frc_Banded': 'Banded Inversion',
                'drs_frc_Toe': 'Toe Raise',
                'drs_frc_elv_Hallucis': 'Elevated Hallucis Flexion',
                'drs_frc_Bear': 'Bear Position Big Toe Stretch (Mobil)',
                'drs_frc_ft_Wall': 'Foot on Wall Calf Stretch (Mobil)',
                'drs_frc_Quadruped': 'Quadruped Rock Back- Big Toe Ext. Bias',
            },
        },
        'KNEE': {
            'SMR': {
                'kn_smr_Longiditunal': 'Longiditunal Foam Roller SMR for Priformis',
                'kn_smr_crs_Priformis': 'Cross Leg Priformis SMR w/Foam Roller',
                'kn_smr_Roller': 'Adductors SMR w/Foam Roller',
                'kn_smr_Miniball': 'Adductors SMR w/Miniball',
                'kn_smr_Straight': 'Straight Leg Adductors SMR w/Foam Roller',
                'kn_smr_Alternating': 'Alternating Adductors SMR',
                'kn_smr_sd_Foam': 'Side Lying IT-Band SMR W/Foam Roller',
                'kn_smr_IT': 'IT-Band SMR Alternative',
                'kn_smr_sd_Mini': 'Side Lying IT-Band SMR w/Mini Ball',
                'kn_smr_Mini': 'TFL SMR w/Minibal',
                'kn_smr_Two': 'Two Leg on Foam Roller Hamstring SMR',
                'kn_smr_OneLeg': 'One-Leg Hamstring SMR',
                'kn_smr_crs_Hamstring': 'Cross Leg Hamstring SMR w/Foam Roller',
                'kn_smr_Seated': 'Seated Hamstring SMR w/Mini Ball',
            },
            'STRETCHING': {
                'kn_str_std_Extended': 'Seated One-Leg Extended Leg Hip Stretch ',
                'kn_str_stn_External': 'Standing Hip External Rotator Stretch',
                'kn_str_Recumbent1': 'Recumbent Hip External Rotator and Hip Extensor Stretch',
                'kn_str_Recumbent2': 'Recumbent Hip External Rotator and Hip Extensor Stretch (Cross Leg)',
                'kn_str_Lsit': 'L-Sit Cross Leg- Priformis Stretch',
                'kn_str_stn_Bent': 'Standing Bent-Knee Hip Adductor Stretch',
                'kn_str_std_Hip': 'Seated Hip Adductor Stretch ',
                'kn_str_stn_Raised': 'Standing Raised-Leg Hip Adductor Stretch',
                'kn_str_stn_Knee': 'Standing Knee Flexor Stretch',
                'kn_str_std_Knee': 'Seated Knee Flexor Stretch',
                'kn_str_Raised': 'Raised- One Leg Knee Flexor Stretch',
                'kn_str_Supine': 'Supine Lying Raised One-Leg Stretch w/Band',
                'kn_str_std_Wide': 'Seated Wide Range Extended Leg Stretch',
                'kn_str_one_Kneeling': 'One-Leg ½ Kneeling Knee Extensor Stretch',
                'kn_str_one_Standing': 'One-Leg Standing Hip Flexor and Knee Extensor Stretch ',
                'kn_str_Lying': 'Lying Hip Flexor and Knee Extensor Stretch',
            },
            'FORCE': {
                'kn_frc_Star': 'Star Stability & Mobility',
                'kn_frc_Land': 'Land Mine Lateral Squat',
                'kn_frc_ltr_Tap': 'Lateral Tap',
                'kn_frc_Heel': 'Heel Elevated ¼ Squat',
                'kn_frc_Banded': 'Banded ‘’Spanish’’ Squat',
                'kn_frc_ltr_Step': 'Lateral Step Down',
                'kn_frc_Rear': 'Rear Foot Elevated Split Squat',
                'kn_frc_rvr_Nordic': 'Reverse Nordic Curl',
                'kn_frc_Bench': 'Bench Pistol Squat',
                'kn_frc_Fire': 'Fire Hydrant',
                'kn_frc_sngl_Squat': 'Single Leg Squat',
                'kn_frc_Double': 'Double Leg Drop-Jump',
                'kn_frc_sngl_Drop': 'Single Leg Drop-Jump',
                'kn_frc_Split': 'Split Stance Lunge w/Band ',
                'kn_frc_sngl_Wall': 'Sinle Leg Wall Sit w/Band',
                'kn_frc_Quadruped': 'Quadruped Rock Back',
                'kn_frc_Runner': 'Runner Lunge',
                'kn_frc_Standing': 'Standing Clam Shell',
                'kn_frc_rvr_Lunge': 'Reverse Lunge w/Band',
                'kn_frc_Goblet': 'Goblet Squat w/Band',
                'kn_frc_sp_Pose': 'Supine Pose Hip External Rotation w/Band',
                'kn_frc_sngl_Hip': 'Single Leg Hip Thrust',
                'kn_frc_Bridge': 'Bridge Leg Extension',
                'kn_frc_sngl_Thrust': 'Single Leg Hip Thrust w/Swiss Ball',
                'kn_frc_sp_Elevated': 'Supine Elevated March w/Band',
                'kn_frc_Wall': 'Wall Squat and Hold',
                'kn_frc_Step': 'Step-Up ',
                'kn_frc_Alternating': 'Alternating Kick Stand Lunge Back',
                'kn_frc_Posterior': 'Posterior Step-Down',
                'kn_frc_Lateral': 'Lateral Sliders Lunge',
                'kn_frc_Elevated': 'Elevated Curtsy Lunge',
            },
        },
        'LOMBER': {
            'SMR': {
                'lmbr_smr_Longiditunal': 'Longiditunal Foam Roller SMR for Priformis',
                'lmbr_smr_crs_Priformis': 'Cross Leg Priformis SMR w/Foam Roller',
                'lmbr_smr_add_Foam': 'Adductors SMR w/Foam Roller',
                'lmbr_smr_add_Miniball': 'Adductors SMR w/Miniball',
                'lmbr_smr_Straight': 'Straight Leg Adductors SMR w/Foam Roller',
                'lmbr_smr_Alternating': 'Alternating Adductors SMR',
                'lmbr_smr_sd_Foam': 'Side Lying IT-Band SMR W/Foam Roller',
                'lmbr_smr_IT': 'IT-Band SMR Alternative',
                'lmbr_smr_sd_Mini': 'Side Lying IT-Band SMR w/Mini Bal',
                'lmbr_smr_TFL': 'TFL SMR w/Miniball',
                'lmbr_smr_tw_Hamstring': 'Two Leg on Foam Roller Hamstring SMR',
                'lmbr_smr_one_Hamstring': 'One-Leg Hamstring SMR',
                'lmbr_smr_crs_Hamstring': 'Cross Leg Hamstring SMR w/Foam Roller',
                'lmbr_smr_Seated': 'Seated Hamstring SMR w/Mini Ball',
                'lmbr_smr_one': 'One-Leg Calf SMR w/Foam Roller',
                'lmbr_smr_crs_Calf': 'Cross Leg Calf SMR w/Foam Roller',
                'lmbr_smr_tw_Foam': 'Two Leg On Foam Roller Calf SMR',
                'lmbr_smr_Calf': 'Calf SMR W/Mini Ball',
                'lmbr_smr_Hip': 'Hip Flexors SMR w/Foam Roller',

            },
            'STRETCHING': {
                'lmbr_str_std_Extended': 'Seated One-Leg Extended Leg Hip Stretch',
                'lmbr_str_stdn_Hip': 'Standing Hip External Rotator Stretch',
                'lmbr_str_Recumbent1': 'Recumbent Hip External Rotator and Hip Extensor Stretch ',
                'lmbr_str_Recumbent': 'Recumbent Hip External Rotator and Hip Extensor Stretch (Cross Leg)',
                'lmbr_str_Lsit': 'L-Sit Cross Leg- Priformis Stretch',
                'lmbr_str_stdn_Bent': 'Standing Bent-Knee Hip Adductor Stretch',
                'lmbr_str_std_Hip': 'Seated Hip Adductor Stretch',
                'lmbr_str_stdn_Raised': 'Standing Raised-Leg Hip Adductor Stretch',
                'lmbr_str_stdn_Knee': 'Standing Knee Flexor Stretch',
                'lmbr_str_std_Knee': 'Seated Knee Flexor Stretch',
                'lmbr_str_Raised': 'Raised- One Leg Knee Flexor Stretch',
                'lmbr_str_sp_Lying': 'Supine Lying Raised One-Leg Stretch w/Band',
                'lmbr_str_std_Wide': 'Seated Wide Range Extended Leg Stretch',
                'lmbr_str_one_Kneeling': 'One-Leg ½ Kneeling Knee Extensor Stretch',
                'lmbr_str_one_Standing': 'One-Leg Standing Hip Flexor and Knee Extensor Stretch',
                'lmbr_str_Lying ': 'Lying Hip Flexor and Knee Extensor Stretch',
                'lmbr_str_sp_Pose': 'Supine Pose Lower-Trunk Flexor Stretch',
                'lmbr_str_Prone ': 'Prone Pose Lower-Trunk Flexor Stretch',
                'lmbr_str_std_Lower': 'Seated Lower-Trunk Extensor Stretch',
                'lmbr_str_stdn_Lateral': 'Standing Lower-Trunk Lateral Flexor Stretch',
                'lmbr_str_stdn_Flexor': 'Standing Lower-Trunk Flexor Stretch (Arched Back)',
                'lmbr_str_Lower': 'Lower-Trunk Lateral Flexor Stretch (Arched Back)',
                'lmbr_str_sp_Side': 'Supine Lying Side Bend (Oscar Moran-208)',
                'lmbr_str_Open ': 'Open Leg Side Bend',
            },
            'FORCE': {
                'lmbr_frc_hp_External': 'Hip External/Internal Rotation Mobility',
                'lmbr_frc_prn_Swimmers': 'Prone Swimmers',
                'lmbr_frc_qd_Thoracic': 'Quadruped Thoracic Rotation',
                'lmbr_frc_prn_Scorpion': 'Prone Scorpion Kick-Overs',
                'lmbr_frc_Side': 'Side Lying Thoracic Reach Arounds',
                'lmbr_frc_Pancake': 'Pancake Walkouts',
                'lmbr_frc_Supine': 'Supine Figure 4',
                'lmbr_frc_Shoulder': 'Shoulder Extension Crap Lifts',
                'lmbr_frc_hp_Flexor': 'Hip Flexor / Hamstring Combo',
                'lmbr_frc_Dead': 'Dead Bug Variations',
                'lmbr_frc_brd_Variations': 'Bridge Variations (özellikle bacak arasında bir cisim sıkıştırarak)',
                'lmbr_frc_br_Crawl': 'Bear Crawl Straight Leg',
                'lmbr_frc_ltr_Line': 'Lateral Line Stretch',
                'lmbr_frc_ct_Cow': 'Cat Cow Varyasyonları (özellikle resisted seçenekler)',
                'lmbr_frc_Resisted': 'Resisted Bird Dog',
                'lmbr_frc_Weighted': 'Weighted Trunk Rotations',
                'lmbr_frc_The': 'The Bretzel Stretch',
                'lmbr_frc_Anti': 'Anti-Rotation Walk Ups',
                'lmbr_frc_prn_Elbows': 'Prone Extension on Elbows',
                'lmbr_frc_prn_Hands': 'Prone Extension on Hands',
                'lmbr_frc_Straight': 'Straight Leg Raise',
                'lmbr_frc_hp_March': 'Hip Flexor March w/Band',
                'lmbr_frc_prn_Cars': 'Prone Hip Cars',
                'lmbr_frc_Shin': '90/90 to Shin Box Step Through',
                'lmbr_frc_Kneeling': '½ Kneeling Hip Flexor / Hamstring Mob',
                'lmbr_frc_Hand': 'Hand Plank w/Hip Flexion and Extension ',
                'lmbr_frc_qd_Hip': 'Quadruped Hip Extension to Abduction',
                'lmbr_frc_br_Sit': 'Bear Sit Kick Outs',
                'lmbr_frc_Worlds': 'Worlds Greated Stretch',
                'lmbr_frc_Deep': 'Deep Squat Mobility w/Strap ',
                'lmbr_frc_ct_Camel': 'Cat & Camel',
                'lmbr_frc_Rock': 'Rock Backs',
                'lmbr_frc_qd_Plank': 'Quadruped Plank',
                'lmbr_frc_Lateral': 'Lateral Reach',
                'lmbr_frc_Segmental': 'Segmental Flexion',
                'lmbr_frc_Child': 'Child Pose and Reach',
                'lmbr_frc_lw_Trunk': 'Lower Trunk Rotation',
                'lmbr_frc_prn_Elbow': 'Prone Extension on Elbow',
                'lmbr_frc_prn_Hand': 'Prone Extension on Hand',
                'lmbr_frc_dbl_Knee': 'Double Knee Supine Flexion',
                'lmbr_frc_stdn_Sidebend': 'Standing Sidebend',
                'lmbr_frc_hp_Hinge': 'Hip Hinge',
                'lmbr_frc_Thoracic': 'Thoracic-Lumbar Gapping',
                'lmbr_frc_brd_March': 'Bridge March w/RB',
                'lmbr_frc_Stability': 'Stability Ball Bird-Dog',
                'lmbr_frc_Lower': 'Lower Trunk Rotation w/Stability Ball',
                'lmbr_frc_stdn_Foot': 'Standing Foot Taps and Isometric Pallof Press',
                'lmbr_frc_sngl_Bridge': 'Single Leg Bridge',
                'lmbr_frc_Sumo': 'Sumo Hip Hinge Squat',
                'lmbr_frc_hp_Thrust': 'Hip Thrust',
                'lmbr_frc_pstr_Pelvic': 'Posterior Pelvic Tilt Glute Bridge',
                'lmbr_frc_pstr_Tilt': 'Posterior Tilt and Banded Marches',
                'lmbr_frc_Plank': 'Plank (Posterior Tilt)',
                'lmbr_frc_std_Pelvic': 'Standing Pelvic Tilt',
                'lmbr_frc_Reverse': 'Reverse Scorpion ',
                'lmbr_frc_sngl_Heel': 'Single Heel Tap ',
                'lmbr_frc_dbl_Heel': 'Double Heel Tap',
                'lmbr_frc_stdn_Pallof': 'Standing Pallof Press',
                'lmbr_frc_Pallof': '½ Kneeling Pallof Press',
            },
        },
        'TORAKAL': {
            'SMR': {
                'trkl_smr_sd_Foam': 'Side Back Glide w/Foam Roller',
                'trkl_smr_sd_Mini': 'Side Back Glide w/Mini Ball',
                'trkl_smr_Supine': 'Supine Pose T-Spine Glide w/Foam Roller',
                'trkl_smr_stdn_Mini': 'Standing T- Spine Glide w/Mini Ball',
                'trkl_smr_stdn_Foam': 'Standing T-Spine Glide w/Foam Roll',
                'trkl_smr_tsp_Glide': 'T- Spine Glide on Longitudinal Foam Roller',
                'trkl_smr_tsp_Cross': 'T-Spine Cross Friction',
            },
            'STRETCHING': {
                'trkl_str_Kneel': 'Kneel Down, Length Arms Away From The Wal',
                'trkl_str_Tspine': 'T-Spine Hold and Stretch w/Foam Roller',
                'trkl_str_Trunk': 'Trunk Rotation with Elbow Flexed',
                'trkl_str_Bench': 'Bench Overhead Stretch',
                'trkl_str_Foam': 'Foam Roller Prayer Stretch',
                'trkl_str_Swiss': 'Swiss Ball Prayer',
                'trkl_str_onearm': 'One-Arm Extended Stretch',
                'trkl_str_over': 'Over Head-Arm Vertical Extension',
                'trkl_str_Quadruped': 'Quadruped Prayer Stretch',
                'trkl_str_Wall': 'Wall Support Thoracic Flexion',
                'trkl_str_Standing': 'Standing Neck and Trunk Flexion',
                'trkl_str_Forward': 'Forward Arm Extension',
            },
            'FORCE': {
                'trkl_frc_sws_IS': 'Swissball Shoulder I’s',
                'trkl_frc_sws_YS': 'Swissball Shoulder Y’s',
                'trkl_frc_sws_TS': 'Swissball Shoulder T’s',
                'trkl_frc_Brueggers': 'Brueggers',
                'trkl_frc_thrc_Sprinklers': 'Thoracic Sprinklers',
                'trkl_frc_Standing': 'Standing Thoracic Extension w/Bar or Wall',
                'trkl_frc_Windshields': 'Windshields Wipers',
                'trkl_frc_Prayer': 'Prayer Swipers',
                'trkl_frc_Kneeling': '½ Kneeling Open Books',
                'trkl_frc_Superman': 'Superman 2.0',
                'trkl_frc_prn_YS': 'Prone Y’s',
                'trkl_frc_Tspine': 'T-Spine Windmill w/Dowel',
                'trkl_frc_Deep': 'Deep Squat Pass Through',
                'trkl_frc_Overhead': 'Overhead Squat w/Dowel',
                'trkl_frc_Good': 'Good Morning Windmill w/Dowel',
                'trkl_frc_Lat': 'Lat Pull Down w/Dowel',
                'trkl_frc_std_Windmills': 'Seated Windmills',
                'trkl_frc_Dowel': 'Dowel Thoracic Rotation',
                'trkl_frc_Child': 'Child Pose & Cat Camel',
                'trkl_frc_thrc_Extension': 'Thoracic Extension w/Foam Roller',
                'trkl_frc_ct_Camel': 'Cat & Camel',
                'trkl_frc_ct_Cow': 'Cat & Cow',
                'trkl_frc_prn_Press': 'Prone Press-Up',
                'trkl_frc_sq_Blades': 'Squeeze Shoulder Blades and Neck Extension',
                'trkl_frc_thrc_Spine': 'Thoracic Spine Extension on Bench',
                'trkl_frc_st_Back': 'Sit Back to Heels T-Spine Cat & Camel',
                'trkl_frc_Lean': 'Lean Forward and Raise Arm Up',
                'trkl_frc_st_Down': 'Sit Down İnto a Squat and Raise Arms-UP Overhead',
                'trkl_frc_Floor': 'Floor Sliders',
                'trkl_frc_Wall': 'Wall Angels',
                'trkl_frc_sq_Pull': 'Squeeze Shoulders and Pull Down on Bench',
                'trkl_frc_Hands': 'Hands Behind Neck + Blades Together',
                'trkl_frc_Thumbs': 'Thumbs Up ‘’W’’ Raise',
                'trkl_frc_Straight': 'Straight Arm ‘’Y’’ Raise on Bench',
                'trkl_frc_Open': 'Open Book- Hand Behind Head',
                'trkl_frc_Lying': 'Lying Open Book',
                'trkl_frc_Bent': 'Bent Over Open Book- Hand Behind Back',
                'trkl_frc_qd_Hand': 'Quadruped Open Book- Hand Behind Back',
                'trkl_frc_qd_Arm': 'Quadruped Open Book- Arm Behind Back',
            },
        },
        'ROUND': {
            'SMR': {
                'rnd_smr_Supine': 'Supine Pose Miniball Rotators Glide',
                'rnd_smr_Prone': 'Prone Pose Miniball Shoulder Glide',
                'rnd_smr_Wall': 'Wall Rotators Glide w/Miniball',
                'rnd_smr_Standing': 'Standing Side Pose Shoulder SMR w/Miniball',
                'rnd_smr_Side': 'Side Lying Lateral Shoulder SMR w/Miniball',
            },
            'STRETCHING': {
                'rnd_str_Bench': 'Bench Overhead Stretch ',
                'rnd_str_Foam': 'Foam Roller Prayer Stretch',
                'rnd_str_Swiss': 'Swiss Ball Prayer',
                'rnd_str_Praying': 'Praying type, Quadruped extension',
                'rnd_str_Torso': 'Torso flexion, over a support w/Wal',
                'rnd_str_OneArm': 'One-Arm Shoulder Flexor Stretch',
                'rnd_str_Horizontal': 'Horizontal Abduction of the arm',
                'rnd_str_Overhead': 'Overhead Arm Vertical Stretch',
                'rnd_str_Neck': 'Neck & Torso Flexion',
                'rnd_str_Forward': 'Forward Arm Ext',
                'rnd_str_Crossing': 'Crossing The Arms Behind The Back',
                'rnd_str_Lying': 'Lying on Bench Ext. Rotation',
                'rnd_str_Seated': 'Seated Shoulder Flexor Depressor Retractor Stretch',
            },
            'FORCE': {
                'rnd_frc_sd_Lying': 'Side Lying Bottom-Up Shoulder Rotation w/KB',
                'rnd_frc_kn_Shoulder': '½ Kneeling Bottom-Up Shoulder Ext. Rotation w/KB',
                'rnd_frc_sp_Pose': 'Supine Pose Bottom-Up Shoulder Rotation w/KB',
                'rnd_frc_kn_Press': '½ Kneeling Bottom-Up Press w/KB',
                'rnd_frc_qd_Pose': 'Quadruped Pose Around The World w/RB',
                'rnd_frc_sd_Plank': 'Side Plank External Rotation w/RB',
                'rnd_frc_qd_Row': 'Quadruped Row w/RB',
                'rnd_frc_sd_External': 'Side Lying External Rotation',
                'rnd_frc_sd_Lateral': 'Side Lying Lateral Raise',
                'rnd_frc_Eccentric': 'Eccentric Rotation to Press',
                'rnd_frc_Dynamic': 'Dynamic Stabilization',
                'rnd_frc_wl_Slides': 'Wall Slides Lift and Pulses',
                'rnd_frc_wl_Clock': 'Wall Clock w/RB',
                'rnd_frc_wl_External': 'Wall External Rotation w/RB',
                'rnd_frc_Press': 'Press and Reach w/RB',
                'rnd_frc_Elbow': 'Elbow Down Dog',
                'rnd_frc_YRaise': '‘’Y’’ Raise on Bench',
                'rnd_frc_Scaption': 'Scaption (90-180)',
                'rnd_frc_TS': 'T’s Thumbs Up',
                'rnd_frc_WA': 'W-A',
                'rnd_frc_Swissball': 'Swissball/Foamroller Prayer',
                'rnd_frc_External': 'External Ball Roll Ups',
                'rnd_frc_Lateral': 'Lateral Ball Circless',
                'rnd_frc_Walkout': 'Walkout + Uppercut with Rotation',
                'rnd_frc_High': 'High Plank Walk Ups',
                'rnd_frc_sd_Rotation': 'Side Plank Rotation w/KB',
                'rnd_frc_Pulsing': 'Pulsing Overhead Reach',
                'rnd_frc_Rollout': 'Rollout and Thoracic Rotation w/Foam Roller',
                'rnd_frc_Bench': 'Bench Overhead Stretch (Mobil)',
                'rnd_frc_Band': 'Band Pull Apart',
                'rnd_frc_stdn_Reach': 'Standing External Rotation and Reach w/RB',
                'rnd_frc_PushUp': 'Push Up Pose Lateral Tap w/RB',
                'rnd_frc_Alternating': 'Alternating Diagonal',
                'rnd_frc_Abduction': 'Abduction Arcs',
                'rnd_frc_Internal90': '90/90 İnternal Rotation',
                'rnd_frc_External90': '90/90 External Rotation',
                'rnd_frc_prn_Snow': 'Prone Snow Angel',
                'rnd_frc_OneArm': 'One Arm Overhead Lift Off w/Foam Roller',
                'rnd_frc_Shoulder': 'Shoulder Flexion- AAROM w/Dowel',
                'rnd_frc_sp_Arm': 'Supine Pose Extended Arm Shoulder Extension',
                'rnd_frc_sp_External': 'Supine Pose Shoulder External Rotation',
                'rnd_frc_sp_Internal': 'Supine Pose Shoulder Internal Rotation',
                'rnd_frc_stdn_Dowelqq': 'Standing External Rotation w/Dowel',
            },
        },
        'PROTRACTED': {
            'SMR': {
                'prt_smr_sd_Foam': 'Side Back Glide w/Foam Roller',
                'prt_smr_sd_Mini': 'Side Back Glide w/Mini Ball',
                'prt_smr_Supine': 'Supine Pose T-Spine Glide w/Foam Roller',
                'prt_smr_stn_Mini': 'Standing T- Spine Glide w/Mini Ball',
                'prt_smr_stn_Foam': 'Standing T-Spine Glide w/Foam Roll',
                'prt_smr_tsp_Glide': 'T- Spine Glide on Longitudinal Foam Roller',
                'prt_smr_tsp_Cross': 'T-Spine Cross Friction',
            },
            'STRETCHING': {
                'prt_str_Bench': 'Bench Overhead Stretch',
                'prt_str_Foam': 'Foam Roller Prayer Stretch',
                'prt_str_Swiss': 'Swiss Ball Prayer',
                'prt_str_OneArm': 'One-Arm Extended Stretch',
                'prt_str_Over': 'Over Head-Arm Vertical Extension',
                'prt_str_Quadruped': 'Quadruped Prayer Stretch',
                'prt_str_Wall': 'Wall Support Thoracic Flexion',
                'prt_str_Standing': 'Standing Neck and Trunk Flexio',
                'prt_str_Forward': 'Forward Arm Extension',
                'prt_str_Crossing': 'Crossing The Arms Behind The Back',
                'prt_str_Lying': 'Lying on Bench Ext. Rotation',
                'prt_str_Seated': 'Seated Shoulder Flexor Depressor Retractor Stretch',
            },
            'FORCE': {
                'prt_frc_shld_Walk': 'Shoulder Internal Rotation Walk Out',
                'prt_frc_shld_Band': 'Shoulder Internal Rotation w/Band',
                'prt_frc_prn_Shoulder': 'Prone Shoulder Internal Rotation',
                'prt_frc_Shoulder': 'Shoulder 90/90 Internal Rotation w/Band',
                'prt_frc_plnk_Foam': 'Plank Foam Roller Glide w/RB',
                'prt_frc_bnd_Bear': 'Banded Bear Hugs (Cover Slide)',
                'prt_frc_bnd_Punches': 'Banded Punches',
                'prt_frc_bnd_Uppercuts': 'Banded Uppercuts',
                'prt_frc_Scaption': 'Scaption Raises (to 1200 or more)',
                'prt_frc_srt_Foam': 'Serratus Foam Roll Wall Slides w/Band',
                'prt_frc_Chest': 'Chest Press Plus',
                'prt_frc_Landmine': 'Landmine Press Plus',
                'prt_frc_Dolphin': 'Dolphin Press',
                'prt_frc_PushUp': 'Push-Up Plus to Down Dog',
                'prt_frc_Single': 'Single-arm Elevated Serratus Press',
                'prt_frc_prn_Arm': 'Prone Arm Behind Neck Shoulder Ext. Rotation',
                'prt_frc_Quadruped': 'Quadruped Pose Extended Arm and Lift',
                'prt_frc_stdn_TS': 'Standing T’s w/Band',
                'prt_frc_stdn_AS': 'Standing A’s w/Band',
                'prt_frc_stdn_YS': 'Standing Y’s w/Band',
                'prt_frc_bnt_WS': 'Bent Over W’s',
                'prt_frc_bnt_YS': 'Bent Over Y’s ',
                'prt_frc_dwl_Thoracic': 'Dowel Thoracic Rotation',
                'prt_frc_dwl_Pullover': 'Dowel Pullover',
                'prt_frc_dwl_Floor': 'Dowel Floor Swipers',
                'prt_frc_qd_Scapular': 'Quad Pose Scapular Prot./Retrac',
                'prt_frc_Rock': 'Rock From Side to Side',
                'prt_frc_Wrist': 'Wrist Push-Up',
                'prt_frc_dwl_Press': 'Dowel Z Press',
                'prt_frc_Overhead': 'Overhead Shrugs',
                'prt_frc_prn_Dowel': 'Prone Dowel Press',
                'prt_frc_qd_Single': 'Quad Pose Single Arm Scapular Punch',
                'prt_frc_srt_Hops': 'Serratus Hops',
                'prt_frc_prn_Scapular': 'Prone Scapular Squeezes',
                'prt_frc_prn_Chicken': 'Prone Chicken Wings ',
                'prt_frc_prn_W': 'Prone W',
                'prt_frc_prn_T': 'Prone T',
                'prt_frc_Advanced': 'Advanced Prone T',
                'prt_frc_srt_Slider': 'Serratus Slider in Bear Position',
                'prt_frc_Weighted': 'Weighted Serratus Reach',
                'prt_frc_plnk_Walk': 'Plank Walk Overs',
                'prt_frc_prn_WRow': 'Prone W’Row w/Band',
            },
        },
        'FORWARD': {
            'SMR': {
                'frwd_smr_nck_Extensor': 'Neck Extensor Release Variation',
                'frwd_smr_nck_Rotator': 'Neck Rotator Release Variation',
                'frwd_smr_Half': 'Half Standing Shoulder Release',
                'frwd_smr_Standing': 'Standing Thoracic Release',
                'frwd_smr_Suboccipital': 'Suboccipital Release',
                'frwd_smr_thrc_Extension': 'Thoracic Extension Release',
                'frwd_smr_thrc_Lateral': 'Thoracic Lateral Extension Release',
                'frwd_smr_thrc_Kneeling': 'Thoracic Mobility Kneeling Roll Release',
                'frwd_smr_thrc_Rolling': 'Thoracic Mobility Rolling Release',
                'frwd_smr_thrc_Standing': 'Thoracic Mobility Standing Roll Release',
                'frwd_smr_thrc_Variation1': 'Thoracic Mobility Release Variation 1',
                'frwd_smr_thrc_Variation2': 'Thoracic Mobility Release Variation 2',
                'frwd_smr_thrc_Variation3': 'Thoracic Mobility Release Variation 3',
                'frwd_smr_thrc_Rotation': 'Thoracic Rotation Release',
                'frwd_smr_Posterior': 'Posterior Dynamic Release',
                'frwd_smr_Weighted': 'Weighted Thoracic Extension Release',
            },
            'STRETCHING': {
                'frwd_str_crv_Extensors': 'Cervical Extensors Stretch',
                'frwd_str_crv_Flexor': 'Cervical Flexor Stretch',
                'frwd_str_crv_Lateral': 'Cervical Lateral Flexor Stretch',
                'frwd_str_crv_Rotator1': 'Cervical Rotator (Extensor) Stretch',
                'frwd_str_crv_Rotator2': 'Cervical Rotator (Flexor) Stretch',
                'frwd_str_Levator': 'Levator Scapula Stretch',
                'frwd_str_Anchor': 'Anchor Stretch (Scalene)',
                'frwd_str_Skalen': 'Skalen Stretch',
                'frwd_str_Chest': 'Chest Stretch',
                'frwd_str_Medial': 'Medial-Ulnar Stretch',
                'frwd_str_SCM': 'SCM Stretch',
                'frwd_str_up_Stretch': 'Upper Trapezius Stretch',
                'frwd_str_up_Cervical': 'Upper Trapezius Stretch w/Cervical Rotation',
                'frwd_str_Dynamic': 'Dynamic Thoracic Extension Stretch',
            },
            'FORCE': {
                'frwd_frc_arm_H': 'Arm H Raise w/Banded',
                'frwd_frc_arm_Raise': 'Arm Raise w/Banded',
                'frwd_frc_arm_YRaise': 'Arm Y Raise',
                'frwd_frc_arm_TRaise': 'Arm Y to T Raise',
                'frwd_frc_arm_WRaise': 'Arm Y to W Raise',
                'frwd_frc_Bilateral': 'Bilateral Extension Rotation w/Banded in Plank Position',
                'frwd_frc_crv_Extension': 'Cervical Extension',
                'frwd_frc_crv_Isometric': 'Cervical Extension Isometric',
                'frwd_frc_crv_Banded': 'Cervical Extension w/Banded',
                'frwd_frc_Straight': 'Straight Arm Cervical Extension w/Banded',
                'frwd_frc_crv_Flexion': 'Cervical Flexion',
                'frwd_frc_crv_IsFlexion': 'Cervical Isometric Flexion',
                'frwd_frc_crv_flxBanded': 'Cervical Flexion w/Banded',
                'frwd_frc_crv_Arm': 'Straight Arm Cervical Lateral Flexion w/Banded',
                'frwd_frc_crv_LtrFlexion': 'Cervical Lateral Flexion',
                'frwd_frc_crv_LtrIsometric': 'Cervical Lateral Flexion Isometric',
                'frwd_frc_crv_LtrBanded': 'Cervical Lateral Flexion w/Banded',
                'frwd_frc_crv_Rotation': 'Cervical Rotation',
                'frwd_frc_crv_RtIsometric': 'Cervical Rotation Isometric',
                'frwd_frc_crv_RtBanded': 'Cervical Rotation w/Banded',
                'frwd_frc_wll_Cervical': 'Wall Cervical Rotation w/Softball',
                'frwd_frc_Chin': 'Chin Nods',
                'frwd_frc_prn_Tuck': 'Prone Chin Tuck',
                'frwd_frc_prn_Isometric': 'Prone Chin Tuck Isometric',
                'frwd_frc_prn_Banded': 'Prone Chin Tuck w/Banded',
                'frwd_frc_prn_YW': 'Prone Y – W Raise',
                'frwd_frc_qd_Tuck': 'Quadruped Chin Tuck',
                'frwd_frc_qd_Banded': 'Quadruped Chin Tuck w/Banded',
                'frwd_frc_qd_Cervical': 'Quadruped Chin Tuck w/Cervical Rotation',
                'frwd_frc_std_Isometric': 'Seated Chin Tuck Isometric',
                'frwd_frc_std_Banded': 'Seated Chin Tuck w/Banded',
                'frwd_frc_wll_Chin': 'Wall Chin Tuck',
                'frwd_frc_nck_Endurance': 'Neck Flexion Isometric Endurance',
                'frwd_frc_Supine': 'Supine Chin Tuck w/Hold',
                'frwd_frc_Middle': 'Middle Back Mobility',
                'frwd_frc_Shoulder': 'Shoulder Abduction w/Banded',
                'frwd_frc_sd_External': 'Side Lying External Rotation',
                'frwd_frc_sd_Thoracic': 'Side Lying Thoracic Rotation',
                'frwd_frc_thrc_Resisted': 'Thoracic Mobility Resisted Middle Back Mobility',
                'frwd_frc_thrc_Rolling': 'Thoracic Mobility Rolling w/Banded',
                'frwd_frc_thrc_Twist1': 'Thoracic Mobility Wall Twist w/Banded',
                'frwd_frc_thrc_Twist2': 'Thoracic Mobility Wall Twist',
                'frwd_frc_Banded': 'Banded Row',
                'frwd_frc_crvc_Extension': 'Cervical Extension on/Stability Ball',
                'frwd_frc_crvc_Flexion': 'Cervical Flexion/Extension',
                'frwd_frc_ch_Horizontal': 'Chin Tuck + Horizontal Abduction',
                'frwd_frc_ch_Prone': 'Chin Tuck + Prone W',
                'frwd_frc_ch_Towel': 'Chin Tuck on Towel',
                'frwd_frc_dghr_Breathing1': 'Diaghram Breathing w/Kettlebell-1',
                'frwd_frc_dghr_Breathing2': 'Diaghram Breathing w/Kettlebell-2',
                'frwd_frc_dghr_Breathing3': 'Diaghram Breathing-1',
                'frwd_frc_dghr_Breathing4': 'Diaghram Breathing-2',
                'frwd_frc_Dynamic': 'Dynamic Retraction',
                'frwd_frc_Elevated': 'Elevated Neck Bridge',
                'frwd_frc_Inverted': 'Inverted Row',
                'frwd_frc_Low': 'Low Trap Lift w/Chin Tuck',
                'frwd_frc_Lower': 'Lower Trap Strength + Thoracic Extension',
                'frwd_frc_Lunge': 'Lunge Reverse Woodchops',
                'frwd_frc_Modified': 'Modified Prone Swimmers',
                'frwd_frc_nck_Flexor': 'Neck Flexor Isometrics',
                'frwd_frc_nck_Retraction': 'Neck Retraction Strength',
                'frwd_frc_nck_Rotation': 'Neck Rotation w/Retraction',
                'frwd_frc_prn_Divers': 'Prone Divers',
                'frwd_frc_prn_Retraction': 'Prone Retraction w/Arm 90/90',
                'frwd_frc_prn_Scapular': 'Prone Scapular + Cervical Retraction',
                'frwd_frc_shld_Mobility1': 'Shoulder Mobility-1',
                'frwd_frc_shld_Mobility2': 'Shoulder Mobility-2',
                'frwd_frc_sd_Lateral': 'Side Lying Lateral Flexor Curl',
                'frwd_frc_sd_Rotations': 'Side Lying Rotations',
                'frwd_frc_stdn_Lateral': 'Standing Lateral Flexion Isometric',
                'frwd_frc_stdn_Row': 'Standing Row',
                'frwd_frc_stdn_Stability': 'Standing Stability Ball Isometric',
                'frwd_frc_stdn_T': 'Standing T',
                'frwd_frc_stdn_Y': 'Standing Y',
                'frwd_frc_wll_Angels': 'Wall Angels w/Chin Tuck',
            },
        },
    },
}
