PILATES = {
    'LEVEL': {
        '1': 'Düşük Seviye',
        '2': 'Orta Seviye',
        '3': 'Yüksek Seviye',
    },
    'PURPOSE': {
        'health1': 'Genel Sağlık Gelişimi',
        'force': 'Genel Kuvvet Gelişimi',
        'muscular_endurance': 'Kas Dayanıklılık Gelişimi',
        'muscle_mass': 'Kas Kütlesi Artışı',
        'mekanik': 'Mekanik Ağrıların Önlenmesi',
        'fonksiyonel': 'Fonksiyonellik Kazanımı',
    },
    'DAYS': {
        'monday': 'Pazartesi',
        'tuesday': 'Salı',
        'wednesday': 'Çarşamba',
        'thursday': 'Perşembe',
        'friday': 'Cuma',
        'saturday': 'Cumartesi',
        'sunday': 'Pazar',
    },
    'TRAININGTIME': {
        '1': '10 dk',
        '2': '15 dk',
        '3': '30 dk',
        '4': '45 dk',
        '5': '60 dk',
        '6': '90 dk',
        '7': '120 dk',
    },
    'SET': {
        '1': '30 sn',
        '2': '60 sn',
        '3': '90 sn',
        '4': '120 sn',
        '5': '3 dk',
        '6': '5 dk',
    },
    'MOVEMENT': {
        '1': '1 dk',
        '2': '2 dk',
        '3': '3 dk',
        '4': '4 dk',
        '5': '5 dk',
    },
    'EXERCISE': {
        'RESPIRATORY': {
            'Rs_Rs_Diaphragm': 'Diaphragm Breating',
            'Rs_Stability': 'Stability and Control Breath',
            'Rs_Lateral': 'Lateral Breath',
            'Rs_Crocodile': 'Crocodile Breathing',
            'Rs_Breath': '90-90 Nefes Tekniği (Soft Ball-Kettlebell)',
            'Rs_Ballon': 'Ballon Breaths',
            'Rs_Br_Exercise': '4-7-8 Breathing Exercise',
            'Rs_Notr': 'Nötr Nefes (Neutral Breath)',
            'Rs_Steps': 'Steps & Benefits (Kapalabhati)-Ateş Nefesi',
            'Rs_Bastrika': 'Körük Nefesi (Bastrika)',
            'Rs_Nadishadlana': 'Dönüşümlü Burun Nefesi (Nadishadlana)',
            'Rs_Suryonulama': 'Sağ Burun Deliği Nefesi (Suryonulama Vilama)',
            'Rs_Chandronulama': 'Sol Burun Deliği Nefesi (Chandronulama Vilama)',
            'Rs_Suryabhadana': 'Tek Burun Deliği Nefesi (Suryabhadana)',
            'Rs_Ujjoyi': 'Okyanus Nefesi (Ujjoyi)',
            'Rs_Bhromeri': 'Arı Nefesi (Bhromeri)',
            'Rs_Anoluma': '4-8 Burun Nefesi (Anoluma Viloma)',
            'Rs_Kumbhaka': '4-4-8 Burun Nefesi (Kumbhaka)',
        },
        'STRETCHING': {
            'St_Extension': 'Cervical Extension',
            'St_Flexion': 'Cervical Flexion',
            'St_Lateral': 'Cervical Lateral Flexion',
            'St_Arm': 'Arm Stretch',
            'St_Shldr_Shrug': 'Shoulder Shrug',
            'St_Scapular': 'Scapular Retraction-Protraction',
            'St_Std_Arm': 'Standing Arm Overhead Stretch w/Theraband',
            'St_Std_Side': 'Standing Side Bent Stretch w/Theraband',
            'St_Std_Thoracic': 'Standing Thoracic Stretch w/Theraband',
            'St_Pr_Oppositional': 'Prone Oppositional Stretch',
            'St_Pr_Tight': 'Prone Tight',
            'St_Pr_Single': 'Prone Single Leg Kick',
            'St_Pr_Swimming': 'Prone Swimming',
            'St_Pr_Double': 'Prone Double Kick',
            'St_Heel': 'Heel Squeeze Prone',
            'St_Pr_Swan': 'Prone Swan',
            'St_Back': 'Back Extension',
            'St_Ct_Stretch': 'Cat Stretch',
            'St_Pushup': 'Push Up Variations',
            'St_Sp_Twist': 'Supine Twist Spine',
            'St_Sp_Circle': 'Supine Leg Circle',
            'St_Sp_Pelvic': 'Supine Pelvic Peel',
            'St_Sp_Hundred': 'Supine Hundred',
            'St_Sp_RollUp': 'Supine Roll Up',
            'St_Sp_Stretch': 'Supine Leg Stretch',
            'St_Sp_Straight': 'Supine Straight Leg Stretch',
            'St_Sp_Double': 'Supine Double Straight Leg Stretch',
            'St_Sp_Crisscross': 'Supine Crisscross',
            'St_Sp_Teaser': 'Supine Teaser',
            'St_Sp_Shoulder': 'Supine Shoulder Bridge',
            'St_Sp_Bicycle': 'Supine Bicycle',
            'St_Sp_RollOver': 'Supine Roll–Over',
            'St_Sp_Corksrew': 'Supine Corksrew',
            'St_Sp_NeckPull': 'Supine Neck–Pull',
            'St_Sp_Scissors': 'Supine Scissors',
            'St_Sp_Jaknife': 'Supine Jaknife',
            'St_St_Spine': 'Seated Spine Stretch Forward and Side',
            'St_St_Mermaid': 'Seated Mermaid Variations',
            'St_Std_RollUp': 'Standing Roll Up',
            'St_Footwork': 'Footwork Series (Dorsi-Planter Flexion –Eversion –Inversion)',
            'St_Std_Calf': 'Standing Calf Stretch',
            'St_Std_Soleus': 'Standing Soleus Stretching',
            'St_Std_Planter': 'Standing Planter Flexion',
            'St_Planter': 'Planter Flexion w/Elastic',
            'St_Ank_Stabilization': 'Ankle Stabilization Walk',
            'St_Rs_Dorsiflexion': 'Resisted Dorsiflexion',
            'St_Rs_Inversion': 'Resisted Inversion',
            'St_Ank_Activate': 'Ankle Activate Range of Motion',
            'St_Rolling': 'Rolling Like a Ball',
            'St_Sd_Bend': 'Side Bend Variations',
            'St_Open': 'Open Leg Circle',
            'St_St_Twist': 'Seated Spine Twist',
            'St_Saw': 'Saw',
            'St_Seal': 'Seal',
            'St_Crab': 'Crab',
            'St_Rocking': 'Rocking',
            'St_Lg_Stretch': 'Leg Stretch',
            'St_Knee': 'Knee Stretch',
            'St_Heal': 'Heal Raise and Arms Overhead',
            'St_Child': 'Child Pose',
            'St_External': 'External Rotation W/ARM ',
            'St_Ct_Cow': 'Cat – Cow',
            'St_Tail': 'Tail Wag',
            'St_Kneeling': 'Kneeling Side Back',
            'St_Pin': 'Pin Wheel',
            'St_Std_Lunge': 'Standing Lunge',
            'St_Std_Squat': 'Standing Squat',
            'St_Std_Warm': 'Standing Warm Up',
            'St_Donkey': 'Donkey Kick',
            'St_Lg_Lift': 'Leg Lift',
            'St_Sd_Lying': 'Side-Lying –Leg Circle',
            'St_Front': 'Front Kick',
            'St_Lg_Front': 'Leg Pull Front',
            'St_Lg_Back': 'Leg Pull Back',
            'St_Lg_Tob': 'Leg Tob',
            'St_Sd_Bicycle': 'Side Lying Bicycle',
            'St_Std_Plank': 'Standing Plank Series',
            'St_Sd_Plank': 'Side Plank Series',
            'St_Bird': 'Bird Dog',
            'St_Dead': 'Dead Bag',
            'St_Neck': 'Neck Bending Pose',
            'St_Shldr_Stretching': 'Shoulder Stretching Pose',
            'St_Shldr_Rotation': 'Shoulder Rotation Pose',
            'St_Cw_Face': 'Cow Face Arms Pose',
            'St_Mountain': 'Mountain Variations ',
            'St_Tree': 'Tree Pose',
            'St_Chair': 'Chair Pose',
            'St_Hlf_Lift': 'Half Lift',
            'St_Forward': 'Forward Fold',
            'St_Ragdoll': 'Ragdoll Pose',
            'St_St_Forward': 'Seated Forward Bend',
            'St_Downward': 'Downward Facing Dog',
            'St_Puppy': 'Puppy Dog - (Band or Straight)',
            'St_Upward': 'Upward Facing Dog Pose',
            'St_Dwn_Crunch': 'Downdog Crunch Pose',
            'St_Dwn_Tuck': 'Downdog Tuck Pose',
            'St_Dwn_Knee': 'Downdog Knee Circles Pose',
            'St_Legged': 'Legged Dog Pose',
            'St_Walk': 'Walk the Dog Pose',
            'St_Four': 'Four Limbed Staff Pose',
            'St_Wrr_left': 'Warrior (left) Pose',
            'St_Wrr_right': 'Warrior (right) Pose',
            'St_Trg_left': 'Triangle (left) Pose',
            'St_Trg_right': 'Triangle (right) Pose',
            'St_Hg_left': 'Hight Lunge (left)',
            'St_Hg_right': 'Hight Lunge (right)',
            'St_Wide': 'Wide Pyramid Pose',
            'St_Hlf_Moon': 'Half Moon',
            'St_Hlf_Monkey': 'Half Monkey',
            'St_Std_Quad': 'Standing Quad Stretch',
            'St_Crescent': 'Crescent Lunge Pose',
            'St_Sd_Lunge': 'Side Lunge Pose',
            'St_Deep': 'Deep Lunge Pose',
            'St_Revolved': 'Revolved Crescent Lunge/Knee with Extended Arms',
            'St_Kn_Circles': 'Knee Circles Pose',
            'St_Riding': 'Riding Pose Variations',
            'St_Figure': 'Figure 4 Chair',
            'St_Airplane': 'Airplane',
            'St_Goddess': 'Goddess Pose',
            'St_Extended': 'Extended Wide Squat',
            'St_Std_Camel': 'Standing Camel Pose',
            'St_Garland': 'Garland Pose',
            'St_Butterfly': 'Butterfly Pose',
            'St_Frog': 'Frog Pose',
            'St_Hd_Knee': 'Head to Knee',
            'St_Pigeon': 'Pigeon Pose',
            'St_Sp_Pigeon': 'Supine Pigeon Pose',
            'St_Kns_Chest': 'Knees to Chest',
            'St_Hlf_Split': 'Half Split Pose',
            'St_Hlf_Middle': 'Half Middle Split',
            'St_Transversal': 'Transversal Split',
            'St_Rc_Middle': 'Reclined Middle Split',
            'St_Rc_Hand': 'Reclined Hand to Toe',
            'St_Mermaid': 'Mermaid Pose',
            'St_Rc_Twist': 'Reclined Twist Pose',
            'St_Rc_Cobbler': 'Reclined Cobbler',
            'St_Windshield': 'Windshield Wipers',
            'St_Thunderbolt': 'Thunderbolt Pose',
            'St_St_Easy': 'Seated Easy Twist Pose (left-right)',
            'St_St_left': 'Seated Twist (left) Pose',
            'St_St_right': 'Seated Twist (right) Pose',
            'St_Sp_Twisting': 'Supine Twisting Poses',
            'St_Marichi': 'Marichi’s Pose',
            'St_Hlf_Fish': 'The Half Fish Pose',
            'St_Fsh_Pose': 'Fish Pose Variations',
            'St_Ct_Pose': 'Cat Pose',
            'St_Cw_Pose': 'Cow Pose',
            'St_Childs': 'Childs Pose',
            'St_Happy': 'Happy Baby Pose',
            'St_Staff': 'Staff Pose',
            'St_Boot': 'Boot Pose Variations',
            'St_Bridge': 'Bridge Pose',
            'St_Lotus': 'Lotus Pose Variations',
            'St_Cbr_Pose': 'Cobra Pose',
            'St_Cbr_Twist': 'Cobra W/a Twist ',
            'St_Low': 'Low Cobra',
            'St_Locust': 'Locust Pose',
            'St_Bow': 'Bow Pose',
            'St_Plnk_Pose': 'Plank Pose',
            'St_Sd_Variations': 'Side Plank Pose Variations',
            'St_Reverse': 'Reverse Crow Crunches Pose',
            'St_Wild': 'Wild Thing Pose',
            'St_Plow': 'Plow Pose',
            'St_Ear': 'Ear Pressive Pose',
            'St_Fll_Boddy': 'Full Boddy Posture Pose',
            'St_Sd_Body': 'Side Body Stretch’s Pose',
            'St_Shldr_stand': 'Shoulder stand Lotus Pose',
            'St_Wheal': 'Wheal Pose',
            'St_Crw_Pose': 'Crow Pose Variations',
            'St_Dragonfly': 'Dragonfly Pose',
            'St_Firefly': 'Firefly Pose',
            'St_Hd_Stand': 'Head Stand Pose',
            'St_Corpse': 'Corpse Pose',
            'St_Kn_Lunge': 'Kneeling Lunge',
            'St_Fll_Lunge': 'Full Lunge',
            'St_Scooter': 'Scooter',
            'St_Kn_Round': 'Knee Stretch –Round Back',
            'St_Kn_Flatt': 'Knee Stretch-Flatt Back',
            'St_Kn_Reverse': 'Knee Stretch Reverse',
            'St_Down': 'Down Stretch',
            'St_Elephant': 'Elephant',
            'St_Up': 'Up Stretch',
            'St_Long': 'Long Stretch',
        },
        'REFORMER': {
            'Rfr_Prl_Heels': 'Parallel Heels',
            'Rfr_Prl_Toes': 'Parallel Toes',
            'Rfr_Position': 'V Position Toes',
            'Rfr_Openv': 'Open V Position Toes',
            'Rfr_Calf': 'Calf Raise',
            'Rfr_Prance': 'Prance',
            'Rfr_Prehensile': 'Prehensile',
            'Rfr_Sng_Heels': 'Single Leg Heels',
            'Rfr_Sng_Toes': 'Single Leg Toes',
            'Rfr_Sng_Foot': 'Single Leg Foot in Strap',
            'Rfr_Sd_Lying': 'Side Lying Footwork',
            'Rfr_Sd_Leg': 'Side Leg Series on Reformers',
            'Rfr_Frog': 'Frog',
            'Rfr_Hp_Down': 'Hip Circle Down',
            'Rfr_Hp_Up': 'Hip Circle Up',
            'Rfr_Opening': 'Opening',
            'Rfr_Extended': 'Extended Frog',
            'Rfr_Bt_Lift': 'Bottom Lift',
            'Rfr_Bt_Extension': 'Bottom Lift W/Extension',
            'Rfr_Semicircle': 'Semicircle',
            'Rfr_Short': 'Short and Long Spine',
            'Rfr_Kn_Side': 'Kneeling Side Split Series',
            'Rfr_Kn_Adductor': 'Kneeling Adductor Leg ',
            'Rfr_Std_Hamstring': 'Seated Hamstring Curls',
            'Rfr_Sd_Split': 'Side Split',
            'Rfr_Back': 'Back Split',
            'Rfr_Squat': 'Squat to Side Split',
            'Rfr_Scooting': 'Scooting',
            'Rfr_Hamstring': 'Hamstring Curl',
            'Rfr_Prep': 'Hundred Prep',
            'Rfr_Hundred': 'Hundred',
            'Rfr_Round': 'Round Back',
            'Rfr_Flat': 'Flat Back',
            'Rfr_Climb': 'Climb a Tree',
            'Rfr_Backstroke': 'Backstroke',
            'Rfr_Tilt': 'Tilt Variations',
            'Rfr_Plank': 'Plank Series /R',
            'Rfr_Twist': 'Twist',
            'Rfr_Sd_Twist': 'Side Twist Kneeling',
            'Rfr_Sd_Over': 'Side Over',
            'Rfr_Mermaid': 'Mermaid',
            'Rfr_Shldr_Extension': 'Shoulder Extension',
            'Rfr_Sp_Extension': 'Supine Shoulder Extension',
            'Rfr_Sp_Adduction': 'Supine Shoulders Adduction',
            'Rfr_Sp_Arm': 'Supine Arm Circle Up',
            'Rfr_Sp_Triceps': 'Supine Triceps',
            'Rfr_St_Chest': 'Seated Chest Expansion',
            'Rfr_St_Biceps': 'Seated Biceps Curl',
            'Rfr_Std_Biceps': 'Standing Biceps Curl',
            'Rfr_Bicep': 'Bicep Curls on the Long Box',
            'Rfr_St_Rhomboid': 'Seated Rhomboid',
            'Rfr_St_Hug': 'Seated Hug a Tree',
            'Rfr_St_Salute': 'Seated Salute',
            'Rfr_Horseback': 'Horseback',
            'Rfr_Kn_Chest': 'Kneeling Chest Expansion',
            'Rfr_Kn_Arm': 'Kneeling Arm Circle Up',
            'Rfr_Kn_Triceps': 'Kneeling Triceps',
            'Rfr_Rw_Front': 'Rowing Front Variations',
            'Rfr_Rw_Back': 'Rowing Back Variations',
            'Rfr_Bck_Extension': 'Back Extension',
            'Rfr_Breaststroke': 'Breaststroke',
            'Rfr_Pulling': 'Pulling Strap',
            'Rfr_Arabesque': 'Arabesque',
            'Rfr_Tendon': 'Tendon Stretch',
            'Rfr_Tight': 'Tight Stretch –No Arch',
        },
        'JUMPBOARD': {
            'Jmp_Footwork': 'Footwork Series',
            'Jmp_Leg': 'Leg Circles Jumpboard',
            'Jmp_Single': 'Single Leg Stretch',
            'Jmp_Sd_Lying': 'Side Lying Tuck Jump',
            'Jmp_Sd_Kneeling': 'Side Kneeling Single Leg Jumps',
            'Jmp_Kn_Butterfly': 'Kneeling Butterfly',
            'Jmp_Quadruped': 'Quadruped Single Leg Jumps',
            'Jmp_Frog': 'Frog Jumps –Frog Extension',
            'Jmp_Fun': 'Fun variations',
            'Jmp_Crisscross': 'Crisscross/ Jumpboard Variations',
            'Jmp_Hundred': 'Hundred /Jumpboard',
            'Jmp_Kn_Seated': 'Kneeling Seated Triceps Press/Jumpboard',
            'Jmp_Kn_Stretch': 'Knee Stretch /Long stretch',
        },
        'CADILLAC': {
            'Cd_VPosition': 'V Position Toes ',
            'Cd_Wide': 'Wide V Position Heels and Toes',
            'Cd_Prance': 'Prance',
            'Cd_Sng_Heel': 'Single Leg Heel ',
            'Cd_Sng_Toes': 'Single Leg Toes',
            'Cd_RollUp': 'Roll Up',
            'Cd_Mn_RollUp': 'Mini Roll Up',
            'Cd_Mn_Oblique': 'Mini Roll Up Oblique',
            'Cd_Rl_Arm': 'Roll Back One Arm',
            'Cd_Sitting': 'Sitting Rolling in and Out',
            'Cd_Rolling': 'Rolling Stomach Message',
            'Cd_Rl_Stretch': 'Roll Back Bar: Tight Stretch',
            'Cd_Tilt': 'Tilt Variations Cadillac Series',
            'Cd_Teaser': 'Teaser',
            'Cd_Frog': 'Frog',
            'Cd_Springs': 'Leg Springs Series: Point Frog- Airplane',
            'Cd_Hp_Circle': 'Hip Circle',
            'Cd_Walking': 'Walking',
            'Cd_Bicycle': 'Bicycle',
            'Cd_Monkey': 'Monkey',
            'Cd_Tower': 'Tower',
            'Cd_Cat': 'Cat Stretch',
            'Cd_Psh_Mermaid': 'Push Through Bar Exercise: Mermaid',
            'Cd_Psh_Long': 'Push Through Long and Short',
            'Cd_Shldr_Dow': 'Shoulder Roll Dow',
            'Cd_Std_Chest': 'Standing Chest Expansion',
            'Cd_Std_Hug': 'Standing Hug a Tree',
            'Cd_Std_Circle': 'Standing Arm Circle',
            'Cd_Std_Punch': 'Standing Arm Punch',
            'Cd_Std_Biceps': 'Standing Biceps',
            'Cd_Std_Side': 'Standing Arm Springs Series: Side Pull',
            'Cd_Std_Up': 'Standing Arm Push Up',
            'Cd_Std_Raise': 'Standing Arm Springs Series: Raise',
            'Cd_Std_Salute': 'Standing Arm Springs Series: Salute',
            'Cd_Reverse': 'Reverse Pull Up /Cadillac',
            'Cd_Squat': 'Squat Cadillac Series',
            'Cd_Butterfly': 'Butterfly',
            'Cd_Sd_Lift': 'Side Lift',
            'Cd_Sd_Leg': 'Side Leg Lift',
            'Cd_Sd_Rich': 'Side Rich',
            'Cd_Pr1': 'Prone 1',
            'Cd_Pr2': 'Prone 2',
            'Cd_Hanging': 'Hanging Back',
        },
        'WUNDA': {
            'Wnd_VPosition': 'V Position Toes',
            'Wnd_Wide': 'Wide V Position Heels and Toes',
            'Wnd_Sng_Leg': 'Single Leg Heels and Toes',
            'Wnd_Std': 'Standing Pike',
            'Wnd_Cat': 'Cat Stretch',
            'Wnd_Full': 'Full Pike',
            'Wnd_Torso': 'Torso Press Sit',
            'Wnd_St_Triceps': 'Seated Triceps',
            'Wnd_Prone': 'Prone Triceps',
            'Wnd_Backward': 'Backward Dips',
            'Wnd_Side': 'Side over',
            'Wnd_Bridge': 'Bridge – Wunda Chair',
            'Wnd_Hamstring': 'Hamstring Curl',
            'Wnd_Leg': 'Leg Press Standing',
            'Wnd_Forward': 'Forward Lunge',
            'Wnd_Basic': 'Basic Swan',
            'Wnd_Horseback': 'Horseback',
            'Wnd_Tendon': 'Tendon Stretch',
        },
        'BARREL': {
            'Br_Hamstring': 'Hamstring Stretch',
            'Br_Gluteal': 'Gluteal Stretch',
            'Br_Adductor': 'Adductor Stretch',
            'Br_Side': 'Side over',
            'Br_Back': 'Back Extension',
            'Br_Swan': 'Swan',
            'Br_Reach': 'Reach',
            'Br_Overhead': 'Overhead Stretch',
            'Br_Chest': 'Chest Lif',
            'Br_Opening': 'Opening',
            'Br_Scissors': 'Scissors',
            'Br_Helicopter': 'Helicopter',
            'Br_Bicycle': 'Bicycle',
            'Br_Roll': 'Roll over',
            'Br_Teaser': 'Teaser Prep',
            'Br_Horseback': 'Horseback',
        },
        'MAGIC': {
            'Mg_Arm_Bent': 'Arms Bent',
            'Mg_Arm_Overhead': 'Arms Overhead ',
            'Mg_Rl_up': 'Roll-up w/Circle',
            'Mg_Rl_over': 'Roll-over w/Circle',
            'Mg_Sp_Double': 'Supine Double Straight Leg Stretch w/Circle',
            'Mg_Sp_Crisscross': 'Supine Crisscross w/Circle',
            'Mg_Sp_Teaser': 'Supine Teaser Variations w/Circle',
            'Mg_Sp_Knee': 'Supine Knee Squeeze',
            'Mg_Sp_Ankle': 'Supine Ankle Squeeze',
            'Mg_Prn_Bent': 'Prone Knee Bent Press w/Circle',
            'Mg_Prn_Straight': 'Prone Knee Straight Squeeze',
            'Mg_Prn_Hamstring': 'Prone Hamstring Squeeze',
            'Mg_St_Adductor': 'Seated Knee Adductor Squeeze',
            'Mg_Sd_down': 'Side Lying Top Leg Press-down w/Circle',
            'Mg_Sd_up': 'Side Lying Top Leg Press-up w/Circle',
            'Mg_Sd_Tap': 'Side Lying Top Leg Tap w/Circle',
        },
        'STABILITY': {
            'Stbt_Crunch': 'Crunch- Side Crunch w/Exercise Ball',
            'Stbt_Ball': 'Ball Pass',
            'Stbt_Push': 'Push Up w/Exercise Ball Toe Tuck',
            'Stbt_Brd_Series': 'Bridge Series Swiss Ball',
            'Stbt_Brd_Curl': 'Bridge Curl',
            'Stbt_Single': 'Single Leg Bridge Curl on Exercise Ball',
            'Stbt_Scorpion': 'The Scorpion',
            'Stbt_Back': 'Back Extension on Exercise Ball',
            'Stbt_Bird': 'Bird Dog on Exercise Ball',
            'Stbt_Spine': 'Spine Stretch',
            'Stbt_Stability': 'Stability Ball Wall Squats',
            'Stbt_Lunge': 'Lunge Using a Stability Ball',
            'Stbt_Sws_Reverse': 'Swiss Ball Reverse Lunge',
            'Stbt_Sws_Anterior': 'Swiss Ball Anterior-Posterior Pelvic Tilts',
            'Stbt_Sws_Mermaid': 'Swiss Ball Mermaid',
            'Stbt_Mermaid': 'Strong Mermaid',
            'Stbt_Thoracic': 'Thoracic spine Stretch',
            'Stbt_stretch': 'Back stretch swiss ball',
            'Stbt_Brd_Dog': 'Bird –Dog w/Swiss Ball',
            'Stbt_Dead': 'Dead Bag w/Swiss Ball',
            'Stbt_Swiss': 'Swiss Ball Planks',
            'Stbt_Low': 'Low Back Stretch Swiss Ball',
            'Stbt_Bench': 'Bench Fly-Bench Press Swiss Ball ',
        },
        'MINIBALL': {
            'Mnb_Footwork': 'Footwork on Ball',
            'Mnb_Inc_Variations': 'Incline Leg-Drop Variations',
            'Mnb_Inc_Continued': 'Incline Leg Drop-Continued',
            'Mnb_High': 'High ‘c’ Curve Mini Ball',
            'Mnb_Lw_Mini': 'Low ‘c’ Curve Mini Ball',
            'Mnb_Lw_Oblique': 'Low ‘c’ Curve - Oblique Crunches',
            'Mnb_Coordination': 'Coordination with Ball',
            'Mnb_Mn_Ball': 'Mini Ball Pass',
            'Mnb_Plank': 'Plank Plus Mini v',
            'Mnb_Sd_Plank': 'Side Plank Mini Ball',
            'Mnb_Oblq_Crunches': 'Oblique Side Crunches',
            'Mnb_Oblq_Inner': 'Oblique & Inner Thight Squeezes',
            'Mnb_Sd_Crunch': 'Side Crunch /Inner Thight Burner',
            'Mnb_Mr_Ball': 'Mermaid with Ball',
            'Mnb_Mr_Twist': 'Mermaid with Twist',
            'Mnb_Thg_Parallel': 'Thighs –Parallel Plies Mini Ball',
            'Mnb_Thg_Dancing': 'Thighs-Thigh Dancing',
            'Mnb_Thg_Lunges': 'Thighs- Lunges',
            'Mnb_Donkey': 'Donkey Kicks & Hamstring Curl Mini Ball',
            'Mnb_In_Booty': 'Inner Thigh Booty Bridge-Pulses',
            'Mnb_In_Leg': 'Inner Thigh –Leg Circles',
            'Mnb_Lg_Lifts': 'Leg Lifts',
            'Mnb_Toe': 'Toe Taps',
            'Mnb_Frog': 'Frog Leg Press',
            'Mnb_Single': 'Single Leg Booty Bridge –Pulses (Ball Stabilization)',
            'Mnb_Booty': 'Booty Bridge –Pulses',
            'Mnb_Squats': 'Squats –Pulses',
            'Mnb_St_Pretzel': 'Seated Pretzel (Glutes) –Mini Bal',
            'Mnb_Ball': 'Ball Push Up- Arms',
            'Mnb_Chest': 'Chest Squeezes Arms-Mini Ball',
            'Mnb_Rl_Over': 'Roll Over Ball',
            'Mnb_Rl_Back': 'Roll Back and Up',
            'Mnb_Bck_Extension': 'Back Extension Ball',
            'Mnb_Extension': 'Swan on Ball',
        },
    }
}
