from django.db import models
from datetime import datetime

# Create your models here.
from django.urls import reverse

from registration.models import Personal, Trainer


class personalTrainingInput2(models.Model):
    # STRETCHING
    St_Extension = models.CharField(max_length=50, verbose_name='Cervical Extension', blank=True, null=True)
    St_Flexion = models.CharField(max_length=50, verbose_name='Cervical Flexion', blank=True, null=True)
    St_Lateral = models.CharField(max_length=50, verbose_name='Cervical Lateral Flexion', blank=True, null=True)
    St_Arm = models.CharField(max_length=50, verbose_name='Arm Stretch', blank=True, null=True)
    St_Shldr_Shrug = models.CharField(max_length=50, verbose_name='Shoulder Shrug', blank=True, null=True)
    St_Scapular = models.CharField(max_length=50, verbose_name='Scapular Retraction-Protraction', blank=True, null=True)
    St_Std_Arm = models.CharField(max_length=50, verbose_name='Standing Arm Overhead Stretch w/Theraband', blank=True,
                                  null=True)
    St_Std_Side = models.CharField(max_length=50, verbose_name='Standing Side Bent Stretch w/Theraband', blank=True,
                                   null=True)
    St_Std_Thoracic = models.CharField(max_length=50, verbose_name='Standing Thoracic Stretch w/Theraband', blank=True,
                                       null=True)
    St_Pr_Oppositional = models.CharField(max_length=50, verbose_name='Prone Oppositional Stretch', blank=True,
                                          null=True)
    St_Pr_Tight = models.CharField(max_length=40, verbose_name='Prone Tight', blank=True, null=True)
    St_Pr_Single = models.CharField(max_length=40, verbose_name='Prone Single Leg Kick', blank=True, null=True)
    St_Pr_Swimming = models.CharField(max_length=40, verbose_name='Prone Swimming', blank=True, null=True)
    St_Pr_Double = models.CharField(max_length=40, verbose_name='Prone Double Kick', blank=True, null=True)
    St_Heel = models.CharField(max_length=40, verbose_name='Heel Squeeze Prone', blank=True, null=True)
    St_Pr_Swan = models.CharField(max_length=40, verbose_name='Prone Swan', blank=True, null=True)
    St_Back = models.CharField(max_length=40, verbose_name='Back Extension', blank=True, null=True)
    St_Ct_Stretch = models.CharField(max_length=40, verbose_name='Cat Stretch', blank=True, null=True)
    St_Pushup = models.CharField(max_length=40, verbose_name='Push Up Variations', blank=True, null=True)
    St_Sp_Twist = models.CharField(max_length=40, verbose_name='Supine Twist Spine', blank=True, null=True)
    St_Sp_Circle = models.CharField(max_length=40, verbose_name='Supine Leg Circle', blank=True, null=True)
    St_Sp_Pelvic = models.CharField(max_length=40, verbose_name='Supine Pelvic Peel', blank=True, null=True)
    St_Sp_Hundred = models.CharField(max_length=40, verbose_name='Supine Hundred', blank=True, null=True)
    St_Sp_RollUp = models.CharField(max_length=40, verbose_name='Supine Roll Up', blank=True, null=True)
    St_Sp_Stretch = models.CharField(max_length=40, verbose_name='Supine Leg Stretch', blank=True, null=True)
    St_Sp_Straight = models.CharField(max_length=40, verbose_name='Supine Straight Leg Stretch', blank=True, null=True)
    St_Sp_Double = models.CharField(max_length=40, verbose_name='Supine Double Straight Leg Stretch', blank=True,
                                    null=True)
    St_Sp_Crisscross = models.CharField(max_length=40, verbose_name='Supine Crisscross', blank=True, null=True)
    St_Sp_Teaser = models.CharField(max_length=40, verbose_name='Supine Teaser', blank=True, null=True)
    St_Sp_Shoulder = models.CharField(max_length=40, verbose_name='Supine Shoulder Bridge', blank=True, null=True)
    St_Sp_Bicycle = models.CharField(max_length=40, verbose_name='Supine Bicycle', blank=True, null=True)
    St_Sp_RollOver = models.CharField(max_length=40, verbose_name='Supine Roll–Over', blank=True, null=True)
    St_Sp_Corksrew = models.CharField(max_length=40, verbose_name='Supine Corksrew', blank=True, null=True)
    St_Sp_NeckPull = models.CharField(max_length=40, verbose_name='Supine Neck–Pull', blank=True, null=True)
    St_Sp_Scissors = models.CharField(max_length=40, verbose_name='Supine Scissors', blank=True, null=True)
    St_Sp_Jaknife = models.CharField(max_length=40, verbose_name='Supine Jaknife', blank=True, null=True)
    St_St_Spine = models.CharField(max_length=40, verbose_name='Seated Spine Stretch Forward and Side', blank=True,
                                   null=True)
    St_St_Mermaid = models.CharField(max_length=40, verbose_name='Seated Mermaid Variations', blank=True, null=True)
    St_Std_RollUp = models.CharField(max_length=40, verbose_name='Standing Roll Up', blank=True, null=True)
    St_Footwork = models.CharField(max_length=65,
                                   verbose_name='Footwork Series (Dorsi-Planter Flexion –Eversion –Inversion)',
                                   blank=True, null=True)
    St_Std_Calf = models.CharField(max_length=40, verbose_name='Standing Calf Stretch', blank=True, null=True)
    St_Std_Soleus = models.CharField(max_length=40, verbose_name='Standing Soleus Stretching', blank=True, null=True)
    St_Std_Planter = models.CharField(max_length=40, verbose_name='Standing Planter Flexion', blank=True, null=True)
    St_Planter = models.CharField(max_length=40, verbose_name='Planter Flexion w/Elastic', blank=True, null=True)
    St_Ank_Stabilization = models.CharField(max_length=40, verbose_name='Ankle Stabilization Walk', blank=True,
                                            null=True)
    St_Rs_Dorsiflexion = models.CharField(max_length=40, verbose_name='Resisted Dorsiflexion', blank=True, null=True)
    St_Rs_Inversion = models.CharField(max_length=40, verbose_name='Resisted Inversion', blank=True, null=True)
    St_Ank_Activate = models.CharField(max_length=40, verbose_name='Ankle Activate Range of Motion', blank=True,
                                       null=True)
    St_Rolling = models.CharField(max_length=40, verbose_name='Rolling Like a Ball', blank=True, null=True)
    St_Sd_Bend = models.CharField(max_length=40, verbose_name='Side Bend Variations', blank=True, null=True)
    St_Open = models.CharField(max_length=40, verbose_name='Open Leg Circle', blank=True, null=True)
    St_St_Twist = models.CharField(max_length=40, verbose_name='Seated Spine Twist', blank=True, null=True)
    St_Saw = models.CharField(max_length=40, verbose_name='Saw', blank=True, null=True)
    St_Seal = models.CharField(max_length=40, verbose_name='Seal', blank=True, null=True)
    St_Crab = models.CharField(max_length=40, verbose_name='Crab', blank=True, null=True)
    St_Rocking = models.CharField(max_length=40, verbose_name='Rocking', blank=True, null=True)
    St_Lg_Stretch = models.CharField(max_length=40, verbose_name='Leg Stretch', blank=True, null=True)
    St_Knee = models.CharField(max_length=40, verbose_name='Knee Stretch', blank=True, null=True)
    St_Heal = models.CharField(max_length=40, verbose_name='Heal Raise and Arms Overhead', blank=True, null=True)
    St_Child = models.CharField(max_length=40, verbose_name='Child Pose', blank=True, null=True)
    St_External = models.CharField(max_length=40, verbose_name='External Rotation  W/ARM', blank=True, null=True)
    St_Ct_Cow = models.CharField(max_length=40, verbose_name='Cat – Cow', blank=True, null=True)
    St_Tail = models.CharField(max_length=40, verbose_name='Tail Wag', blank=True, null=True)
    St_Kneeling = models.CharField(max_length=40, verbose_name='Kneeling Side Back', blank=True, null=True)
    St_Pin = models.CharField(max_length=40, verbose_name='Pin Wheel', blank=True, null=True)
    St_Std_Lunge = models.CharField(max_length=40, verbose_name='Standing Lunge', blank=True, null=True)
    St_Std_Squat = models.CharField(max_length=40, verbose_name='Standing Squat', blank=True, null=True)
    St_Std_Warm = models.CharField(max_length=40, verbose_name='Standing Warm', blank=True, null=True)
    St_Donkey = models.CharField(max_length=40, verbose_name='Donkey Kick', blank=True, null=True)
    St_Lg_Lift = models.CharField(max_length=40, verbose_name='Leg Lift', blank=True, null=True)
    St_Sd_Lying = models.CharField(max_length=40, verbose_name='Side-Lying –Leg Circle', blank=True, null=True)
    St_Front = models.CharField(max_length=40, verbose_name='Front Kick', blank=True, null=True)
    St_Lg_Front = models.CharField(max_length=40, verbose_name='Leg Pull Front', blank=True, null=True)
    St_Lg_Back = models.CharField(max_length=40, verbose_name='Leg Pull Back', blank=True, null=True)
    St_Lg_Tob = models.CharField(max_length=40, verbose_name='Leg Tob', blank=True, null=True)
    St_Sd_Bicycle = models.CharField(max_length=40, verbose_name='Side Lying Bicycle', blank=True, null=True)
    St_Std_Plank = models.CharField(max_length=40, verbose_name='Standing Plank Series', blank=True, null=True)
    St_Sd_Plank = models.CharField(max_length=40, verbose_name='Side Plank Series', blank=True, null=True)
    St_Bird = models.CharField(max_length=40, verbose_name='Bird Dog', blank=True, null=True)
    St_Dead = models.CharField(max_length=40, verbose_name='Dead Bag', blank=True, null=True)
    St_Neck = models.CharField(max_length=40, verbose_name='Neck Bending Pose', blank=True, null=True)
    St_Shldr_Stretching = models.CharField(max_length=40, verbose_name='Shoulder Stretching Pose', blank=True,
                                           null=True)
    St_Shldr_Rotation = models.CharField(max_length=40, verbose_name='Shoulder Rotation Pose', blank=True, null=True)
    St_Cw_Face = models.CharField(max_length=40, verbose_name='Cow Face Pose', blank=True, null=True)
    St_Mountain = models.CharField(max_length=40, verbose_name='Mountain Variations Pose', blank=True, null=True)
    St_Tree = models.CharField(max_length=40, verbose_name='Tree Pose', blank=True, null=True)
    St_Chair = models.CharField(max_length=40, verbose_name='Chair Pose', blank=True, null=True)
    St_Hlf_Lift = models.CharField(max_length=40, verbose_name='Half Lift', blank=True, null=True)
    St_Forward = models.CharField(max_length=40, verbose_name='Forward Fold', blank=True, null=True)
    St_Ragdoll = models.CharField(max_length=40, verbose_name='Ragdoll Pose', blank=True, null=True)
    St_St_Forward = models.CharField(max_length=40, verbose_name='Seated Forward Bend', blank=True, null=True)
    St_Downward = models.CharField(max_length=40, verbose_name='Downward Facing Dog', blank=True, null=True)
    St_Puppy = models.CharField(max_length=40, verbose_name='Puppy Dog - (Band or Straight)', blank=True, null=True)
    St_Upward = models.CharField(max_length=40, verbose_name='Upward Facing Dog Pose', blank=True, null=True)
    St_Dwn_Crunch = models.CharField(max_length=40, verbose_name='Downdog Crunch Pose', blank=True, null=True)
    St_Dwn_Tuck = models.CharField(max_length=40, verbose_name='Downdog Tuck Pose', blank=True, null=True)
    St_Dwn_Knee = models.CharField(max_length=40, verbose_name='Downdog Knee Circles Pose', blank=True, null=True)
    St_Legged = models.CharField(max_length=40, verbose_name='Legged Dog Pose', blank=True, null=True)
    St_Walk = models.CharField(max_length=40, verbose_name='Walk the Dog Pose', blank=True, null=True)
    St_Four = models.CharField(max_length=40, verbose_name='Four Limbed Staff Pose', blank=True, null=True)
    St_Wrr_left = models.CharField(max_length=40, verbose_name='Warrior (left) Pose', blank=True, null=True)
    St_Wrr_right = models.CharField(max_length=40, verbose_name='Warrior (right) Pose', blank=True, null=True)
    St_Trg_left = models.CharField(max_length=40, verbose_name='Triangle (left) Pose', blank=True, null=True)
    St_Trg_right = models.CharField(max_length=40, verbose_name='Triangle (right) Pose', blank=True, null=True)
    St_Hg_left = models.CharField(max_length=40, verbose_name='Hight Lunge (left)', blank=True, null=True)
    St_Hg_right = models.CharField(max_length=40, verbose_name='Hight Lunge (right)', blank=True, null=True)
    St_Wide = models.CharField(max_length=40, verbose_name='Wide Pyramid Pose', blank=True, null=True)
    St_Hlf_Moon = models.CharField(max_length=40, verbose_name='Half Moon', blank=True, null=True)
    St_Hlf_Monkey = models.CharField(max_length=40, verbose_name='Half Monkey', blank=True, null=True)
    St_Std_Quad = models.CharField(max_length=40, verbose_name='Standing Quad Stretch', blank=True, null=True)
    St_Crescent = models.CharField(max_length=40, verbose_name='Crescent Lunge Pose', blank=True, null=True)
    St_Sd_Lunge = models.CharField(max_length=40, verbose_name='Side Lunge Pose', blank=True, null=True)
    St_Deep = models.CharField(max_length=40, verbose_name='Deep Lunge Pose', blank=True, null=True)
    St_Revolved = models.CharField(max_length=50, verbose_name='Revolved Crescent Lunge/Knee with Extended Arms',
                                   blank=True, null=True)
    St_Kn_Circles = models.CharField(max_length=40, verbose_name='Knee Circles Pose', blank=True, null=True)
    St_Riding = models.CharField(max_length=40, verbose_name='Riding Pose Variations', blank=True, null=True)
    St_Figure = models.CharField(max_length=40, verbose_name='Figure 4 Chair', blank=True, null=True)
    St_Airplane = models.CharField(max_length=40, verbose_name='Airplane', blank=True, null=True)
    St_Goddess = models.CharField(max_length=40, verbose_name='Goddess Pose', blank=True, null=True)
    St_Extended = models.CharField(max_length=40, verbose_name='Extended Wide Squat', blank=True, null=True)
    St_Std_Camel = models.CharField(max_length=40, verbose_name='Standing Camel Pose', blank=True, null=True)
    St_Garland = models.CharField(max_length=40, verbose_name='Garland Pose', blank=True, null=True)
    St_Butterfly = models.CharField(max_length=40, verbose_name='Butterfly Pose', blank=True, null=True)
    St_Frog = models.CharField(max_length=40, verbose_name='Frog Pose', blank=True, null=True)
    St_Hd_Knee = models.CharField(max_length=40, verbose_name='Head to Knee', blank=True, null=True)
    St_Pigeon = models.CharField(max_length=40, verbose_name='Pigeon Pose Pose', blank=True, null=True)
    St_Sp_Pigeon = models.CharField(max_length=40, verbose_name='Supine Pigeon', blank=True, null=True)
    St_Kns_Chest = models.CharField(max_length=40, verbose_name='Knees to  Chest', blank=True, null=True)
    St_Hlf_Split = models.CharField(max_length=40, verbose_name='Half Split Pose', blank=True, null=True)
    St_Hlf_Middle = models.CharField(max_length=40, verbose_name='Half Middle Split', blank=True, null=True)
    St_Transversal = models.CharField(max_length=40, verbose_name='Transversal Split', blank=True, null=True)
    St_Rc_Middle = models.CharField(max_length=40, verbose_name='Reclined Middle Split', blank=True, null=True)
    St_Rc_Hand = models.CharField(max_length=40, verbose_name='Reclined Hand to Toe', blank=True, null=True)
    St_Mermaid = models.CharField(max_length=40, verbose_name='Mermaid Pose', blank=True, null=True)
    St_Rc_Twist = models.CharField(max_length=40, verbose_name='Reclined Twist Pose', blank=True, null=True)
    St_Rc_Cobbler = models.CharField(max_length=40, verbose_name='Reclined Cobbler', blank=True, null=True)
    St_Windshield = models.CharField(max_length=40, verbose_name='Windshield Wipers', blank=True, null=True)
    St_Thunderbolt = models.CharField(max_length=40, verbose_name='Thunderbolt Pose', blank=True, null=True)
    St_St_Easy = models.CharField(max_length=40, verbose_name='Seated Easy  Twist Pose (left-right)', blank=True,
                                  null=True)
    St_St_left = models.CharField(max_length=40, verbose_name='Seated Twist (left) Pose', blank=True, null=True)
    St_St_right = models.CharField(max_length=40, verbose_name='Seated Twist (right) Pose', blank=True, null=True)
    St_Sp_Twisting = models.CharField(max_length=40, verbose_name='Supine Twisting Poses', blank=True, null=True)
    St_Marichi = models.CharField(max_length=40, verbose_name='Marichi’s Pose', blank=True, null=True)
    St_Hlf_Fish = models.CharField(max_length=40, verbose_name='The Half Fish Pose', blank=True, null=True)
    St_Fsh_Pose = models.CharField(max_length=40, verbose_name='Fish Pose Variations', blank=True, null=True)
    St_Ct_Pose = models.CharField(max_length=40, verbose_name='Cat Pose', blank=True, null=True)
    St_Cw_Pose = models.CharField(max_length=40, verbose_name='Cow Pose', blank=True, null=True)
    St_Childs = models.CharField(max_length=40, verbose_name='Childs Pose', blank=True, null=True)
    St_Happy = models.CharField(max_length=40, verbose_name='Happy Baby Pose', blank=True, null=True)
    St_Staff = models.CharField(max_length=40, verbose_name='Staff Pose', blank=True, null=True)
    St_Boot = models.CharField(max_length=40, verbose_name='Boot Pose Variations', blank=True, null=True)
    St_Bridge = models.CharField(max_length=40, verbose_name='Bridge Pose', blank=True, null=True)
    St_Lotus = models.CharField(max_length=40, verbose_name='Lotus Pose Variations', blank=True, null=True)
    St_Cbr_Pose = models.CharField(max_length=40, verbose_name='Cobra Pose', blank=True, null=True)
    St_Cbr_Twist = models.CharField(max_length=40, verbose_name='Cobra W/a Twist', blank=True, null=True)
    St_Low = models.CharField(max_length=40, verbose_name='Low Cobra', blank=True, null=True)
    St_Locust = models.CharField(max_length=40, verbose_name='Locust Pose', blank=True, null=True)
    St_Bow = models.CharField(max_length=40, verbose_name='Bow Pose', blank=True, null=True)
    St_Plnk_Pose = models.CharField(max_length=40, verbose_name='Plank Pose', blank=True, null=True)
    St_Sd_Variations = models.CharField(max_length=40, verbose_name='Side Plank Pose Variations', blank=True, null=True)
    St_Reverse = models.CharField(max_length=40, verbose_name='Reverse Crow Crunches Pose', blank=True, null=True)
    St_Wild = models.CharField(max_length=40, verbose_name='Wild Thing Pose', blank=True, null=True)
    St_Plow = models.CharField(max_length=40, verbose_name='Plow Pose', blank=True, null=True)
    St_Ear = models.CharField(max_length=40, verbose_name='Ear Pressive Pose', blank=True, null=True)
    St_Fll_Boddy = models.CharField(max_length=40, verbose_name='Full Boddy Posture Pose', blank=True, null=True)
    St_Sd_Body = models.CharField(max_length=40, verbose_name='Side Body  Stretch’s Pose', blank=True, null=True)
    St_Shldr_stand = models.CharField(max_length=40, verbose_name='Shoulder stand Lotus Pose', blank=True, null=True)
    St_Wheal = models.CharField(max_length=40, verbose_name='Wheal Pose', blank=True, null=True)
    St_Crw_Pose = models.CharField(max_length=40, verbose_name='Crow Pose Variations', blank=True, null=True)
    St_Dragonfly = models.CharField(max_length=40, verbose_name='Dragonfly Pose', blank=True, null=True)
    St_Firefly = models.CharField(max_length=40, verbose_name='Firefly Pose', blank=True, null=True)
    St_Hd_Stand = models.CharField(max_length=40, verbose_name='Head Stand Pose', blank=True, null=True)
    St_Corpse = models.CharField(max_length=40, verbose_name='Corpse Pose', blank=True, null=True)
    St_Kn_Lunge = models.CharField(max_length=40, verbose_name='Kneeling Lunge', blank=True, null=True)
    St_Fll_Lunge = models.CharField(max_length=40, verbose_name='Full Lunge', blank=True, null=True)
    St_Scooter = models.CharField(max_length=40, verbose_name='Scooter', blank=True, null=True)
    St_Kn_Round = models.CharField(max_length=40, verbose_name='Knee Stretch –Round Back', blank=True, null=True)
    St_Kn_Flatt = models.CharField(max_length=40, verbose_name='Knee Stretch-Flatt Back', blank=True, null=True)
    St_Kn_Reverse = models.CharField(max_length=40, verbose_name='Knee Stretch Reverse', blank=True, null=True)
    St_Down = models.CharField(max_length=40, verbose_name='Down Stretch', blank=True, null=True)
    St_Elephant = models.CharField(max_length=40, verbose_name='Elephant', blank=True, null=True)
    St_Up = models.CharField(max_length=40, verbose_name='Up Stretch', blank=True, null=True)
    St_Long = models.CharField(max_length=40, verbose_name='Long Stretch', blank=True, null=True)

    class Meta:
        verbose_name = 'Personal Training'
        verbose_name_plural = 'Personal Training'


class personalTrainingInput3(models.Model):
    # REFORMER
    Rfr_Prl_Heels = models.CharField(max_length=40, verbose_name='Parallel Heels', blank=True, null=True)
    Rfr_Prl_Toes = models.CharField(max_length=40, verbose_name='Parallel Toes', blank=True, null=True)
    Rfr_Position = models.CharField(max_length=40, verbose_name='V Position Toes', blank=True, null=True)
    Rfr_Openv = models.CharField(max_length=40, verbose_name='Open V Position Toes', blank=True, null=True)
    Rfr_Calf = models.CharField(max_length=40, verbose_name='Calf Raise', blank=True, null=True)
    Rfr_Prance = models.CharField(max_length=40, verbose_name='Prance', blank=True, null=True)
    Rfr_Prehensile = models.CharField(max_length=40, verbose_name='Prehensile', blank=True, null=True)
    Rfr_Sng_Heels = models.CharField(max_length=40, verbose_name='Single Leg Heels', blank=True, null=True)
    Rfr_Sng_Toes = models.CharField(max_length=40, verbose_name='Single Leg Toes', blank=True, null=True)
    Rfr_Sng_Foot = models.CharField(max_length=40, verbose_name='Single Leg Foot in Strap', blank=True, null=True)
    Rfr_Sd_Lying = models.CharField(max_length=40, verbose_name='Side Lying Footwork', blank=True, null=True)
    Rfr_Sd_Leg = models.CharField(max_length=40, verbose_name='Side Leg Series on Reformers', blank=True, null=True)
    Rfr_Frog = models.CharField(max_length=40, verbose_name='Frog', blank=True, null=True)
    Rfr_Hp_Down = models.CharField(max_length=40, verbose_name='Hip Circle Down', blank=True, null=True)
    Rfr_Hp_Up = models.CharField(max_length=40, verbose_name='Hip Circle Up', blank=True, null=True)
    Rfr_Opening = models.CharField(max_length=40, verbose_name='Opening', blank=True, null=True)
    Rfr_Extended = models.CharField(max_length=40, verbose_name='Extended Frog', blank=True, null=True)
    Rfr_Bt_Lift = models.CharField(max_length=40, verbose_name='Bottom Lift', blank=True, null=True)
    Rfr_Bt_Extension = models.CharField(max_length=40, verbose_name='Bottom Lift W/Extension', blank=True, null=True)
    Rfr_Semicircle = models.CharField(max_length=40, verbose_name='Semicircle', blank=True, null=True)
    Rfr_Short = models.CharField(max_length=40, verbose_name='Short and Long', blank=True, null=True)
    Rfr_Kn_Side = models.CharField(max_length=40, verbose_name='Kneeling Side Split Series', blank=True, null=True)
    Rfr_Kn_Adductor = models.CharField(max_length=40, verbose_name='Kneeling Adductor Leg', blank=True, null=True)
    Rfr_Std_Hamstring = models.CharField(max_length=40, verbose_name='Seated Hamstring Curls', blank=True, null=True)
    Rfr_Sd_Split = models.CharField(max_length=40, verbose_name='Side Split', blank=True, null=True)
    Rfr_Back = models.CharField(max_length=40, verbose_name='Back Split', blank=True, null=True)
    Rfr_Squat = models.CharField(max_length=40, verbose_name='Squat to Side', blank=True, null=True)
    Rfr_Scooting = models.CharField(max_length=40, verbose_name='Scooting', blank=True, null=True)
    Rfr_Hamstring = models.CharField(max_length=40, verbose_name='Hamstring Curl', blank=True, null=True)
    Rfr_Prep = models.CharField(max_length=40, verbose_name='Hundred Prep', blank=True, null=True)
    Rfr_Hundred = models.CharField(max_length=40, verbose_name='Hundred', blank=True, null=True)
    Rfr_Round = models.CharField(max_length=40, verbose_name='Round Back', blank=True, null=True)
    Rfr_Flat = models.CharField(max_length=40, verbose_name='Flat Back', blank=True, null=True)
    Rfr_Climb = models.CharField(max_length=40, verbose_name='Climb a Tree', blank=True, null=True)
    Rfr_Backstroke = models.CharField(max_length=40, verbose_name='Backstroke', blank=True, null=True)
    Rfr_Tilt = models.CharField(max_length=40, verbose_name='Tilt Variations', blank=True, null=True)
    Rfr_Plank = models.CharField(max_length=40, verbose_name='Plank Series /R', blank=True, null=True)
    Rfr_Twist = models.CharField(max_length=40, verbose_name='Twist', blank=True, null=True)
    Rfr_Sd_Twist = models.CharField(max_length=40, verbose_name='Side Twist Kneeling', blank=True, null=True)
    Rfr_Sd_Over = models.CharField(max_length=40, verbose_name='Side Over', blank=True, null=True)
    Rfr_Mermaid = models.CharField(max_length=40, verbose_name='Mermaid', blank=True, null=True)
    Rfr_Shldr_Extension = models.CharField(max_length=40, verbose_name='Shoulder Extension', blank=True, null=True)
    Rfr_Sp_Extension = models.CharField(max_length=40, verbose_name='Supine Shoulder Extension', blank=True, null=True)
    Rfr_Sp_Adduction = models.CharField(max_length=40, verbose_name='Supine Shoulders Adduction', blank=True, null=True)
    Rfr_Sp_Arm = models.CharField(max_length=40, verbose_name='Supine Arm Circle Up', blank=True, null=True)
    Rfr_Sp_Triceps = models.CharField(max_length=40, verbose_name='Supine Triceps', blank=True, null=True)
    Rfr_St_Chest = models.CharField(max_length=40, verbose_name='Seated Chest Expansion', blank=True, null=True)
    Rfr_St_Biceps = models.CharField(max_length=40, verbose_name='Seated Biceps Curl', blank=True, null=True)
    Rfr_Std_Biceps = models.CharField(max_length=40, verbose_name='Standing Biceps Curl', blank=True, null=True)
    Rfr_Bicep = models.CharField(max_length=40, verbose_name='Bicep Curls on the Long Box', blank=True, null=True)
    Rfr_St_Rhomboid = models.CharField(max_length=40, verbose_name='Seated Rhomboid', blank=True, null=True)
    Rfr_St_Hug = models.CharField(max_length=40, verbose_name='Seated Hug a Tree', blank=True, null=True)
    Rfr_St_Salute = models.CharField(max_length=40, verbose_name='Seated Salute', blank=True, null=True)
    Rfr_Horseback = models.CharField(max_length=40, verbose_name='Horseback', blank=True, null=True)
    Rfr_Kn_Chest = models.CharField(max_length=40, verbose_name='Kneeling Chest Expansion', blank=True, null=True)
    Rfr_Kn_Arm = models.CharField(max_length=40, verbose_name='Kneeling Arm Circle Up', blank=True, null=True)
    Rfr_Kn_Triceps = models.CharField(max_length=40, verbose_name='Kneeling Triceps', blank=True, null=True)
    Rfr_Rw_Front = models.CharField(max_length=40, verbose_name='Rowing Front Variations', blank=True, null=True)
    Rfr_Rw_Back = models.CharField(max_length=40, verbose_name='Rowing Back Variations', blank=True, null=True)
    Rfr_Bck_Extension = models.CharField(max_length=40, verbose_name='Back Extension', blank=True, null=True)
    Rfr_Breaststroke = models.CharField(max_length=40, verbose_name='Breaststroke', blank=True, null=True)
    Rfr_Pulling = models.CharField(max_length=40, verbose_name='Pulling Strap', blank=True, null=True)
    Rfr_Arabesque = models.CharField(max_length=40, verbose_name='Arabesque', blank=True, null=True)
    Rfr_Tendon = models.CharField(max_length=40, verbose_name='Tendon Stretch', blank=True, null=True)
    Rfr_Tight = models.CharField(max_length=40, verbose_name='Tight Stretch–No Arch', blank=True, null=True)
    # JUMPBOARD
    Jmp_Footwork = models.CharField(max_length=40, verbose_name='Footwork Series', blank=True, null=True)
    Jmp_Leg = models.CharField(max_length=40, verbose_name='Leg Circles Jumpboard', blank=True, null=True)
    Jmp_Single = models.CharField(max_length=40, verbose_name='Single Leg Stretch', blank=True, null=True)
    Jmp_Sd_Lying = models.CharField(max_length=40, verbose_name='Side Lying Tuck Jump', blank=True, null=True)
    Jmp_Sd_Kneeling = models.CharField(max_length=40, verbose_name='Side Kneeling Single Leg Jumps', blank=True,
                                       null=True)
    Jmp_Kn_Butterfly = models.CharField(max_length=40, verbose_name='Kneeling Butterfly', blank=True, null=True)
    Jmp_Quadruped = models.CharField(max_length=40, verbose_name='Quadruped Single Leg Jumps', blank=True, null=True)
    Jmp_Frog = models.CharField(max_length=40, verbose_name='Frog Jumps –Frog Extension', blank=True, null=True)
    Jmp_Fun = models.CharField(max_length=40, verbose_name='Fun variations', blank=True, null=True)
    Jmp_Crisscross = models.CharField(max_length=40, verbose_name='Crisscross/ Jumpboard Variations', blank=True,
                                      null=True)
    Jmp_Hundred = models.CharField(max_length=40, verbose_name='Hundred /Jumpboard', blank=True, null=True)
    Jmp_Kn_Seated = models.CharField(max_length=45, verbose_name='Kneeling Seated Triceps Press/Jumpboard', blank=True,
                                     null=True)
    Jmp_Kn_Stretch = models.CharField(max_length=40, verbose_name='Knee Stretch /Long stretch', blank=True, null=True)
    #
    Cd_VPosition = models.CharField(max_length=40, verbose_name='V Position Toes', blank=True, null=True)
    Cd_Wide = models.CharField(max_length=40, verbose_name='Wide V Position Heels and Toes', blank=True, null=True)
    Cd_Prance = models.CharField(max_length=40, verbose_name='Prance', blank=True, null=True)
    Cd_Sng_Heel = models.CharField(max_length=40, verbose_name='Single Leg Heel', blank=True, null=True)
    Cd_Sng_Toes = models.CharField(max_length=40, verbose_name='Single Leg Toes', blank=True, null=True)
    Cd_RollUp = models.CharField(max_length=40, verbose_name='Roll Up', blank=True, null=True)
    Cd_Mn_RollUp = models.CharField(max_length=40, verbose_name='Mini Roll Up', blank=True, null=True)
    Cd_Mn_Oblique = models.CharField(max_length=40, verbose_name='Mini Roll Up Oblique', blank=True, null=True)
    Cd_Rl_Arm = models.CharField(max_length=40, verbose_name='Roll Back  One Arm', blank=True, null=True)
    Cd_Sitting = models.CharField(max_length=40, verbose_name='Sitting Rolling in and Out', blank=True, null=True)
    Cd_Rolling = models.CharField(max_length=40, verbose_name='Rolling Stomach Message', blank=True, null=True)
    Cd_Rl_Stretch = models.CharField(max_length=40, verbose_name='Roll Back Bar: Tight Stretch', blank=True, null=True)
    Cd_Tilt = models.CharField(max_length=40, verbose_name='Tilt Variations Cadillac Series', blank=True, null=True)
    Cd_Teaser = models.CharField(max_length=40, verbose_name='Teaser', blank=True, null=True)
    Cd_Frog = models.CharField(max_length=40, verbose_name='Frog', blank=True, null=True)
    Cd_Springs = models.CharField(max_length=45, verbose_name='Leg Springs Series: Point Frog- Airplane', blank=True,
                                  null=True)
    Cd_Hp_Circle = models.CharField(max_length=40, verbose_name='Hip Circle', blank=True, null=True)
    Cd_Walking = models.CharField(max_length=40, verbose_name='Walking', blank=True, null=True)
    Cd_Bicycle = models.CharField(max_length=40, verbose_name='Bicycle', blank=True, null=True)
    Cd_Monkey = models.CharField(max_length=40, verbose_name='Monkey', blank=True, null=True)
    Cd_Tower = models.CharField(max_length=40, verbose_name='Tower', blank=True, null=True)
    Cd_Cat = models.CharField(max_length=40, verbose_name='Cat Stretch', blank=True, null=True)
    Cd_Psh_Mermaid = models.CharField(max_length=40, verbose_name='Push Through Bar Exercise: Mermaid', blank=True,
                                      null=True)
    Cd_Psh_Long = models.CharField(max_length=40, verbose_name='Push Through Long and Short', blank=True, null=True)
    Cd_Shldr_Dow = models.CharField(max_length=40, verbose_name='Shoulder Roll Dow', blank=True, null=True)
    Cd_Std_Chest = models.CharField(max_length=40, verbose_name='Standing Chest Expansion', blank=True, null=True)
    Cd_Std_Hug = models.CharField(max_length=40, verbose_name='Standing Hug a Tree', blank=True, null=True)
    Cd_Std_Circle = models.CharField(max_length=40, verbose_name='Standing Arm Circle', blank=True, null=True)
    Cd_Std_Punch = models.CharField(max_length=40, verbose_name='Standing Arm Punch', blank=True, null=True)
    Cd_Std_Biceps = models.CharField(max_length=40, verbose_name='Standing Biceps', blank=True, null=True)
    Cd_Std_Side = models.CharField(max_length=45, verbose_name='Standing Arm Springs Series: Side Pull', blank=True,
                                   null=True)
    Cd_Std_Up = models.CharField(max_length=40, verbose_name='Standing Arm Push Up', blank=True, null=True)
    Cd_Std_Raise = models.CharField(max_length=40, verbose_name='Standing Arm Springs Series: Raise', blank=True,
                                    null=True)
    Cd_Std_Salute = models.CharField(max_length=40, verbose_name='Standing Arm Springs Series: Salute', blank=True,
                                     null=True)
    Cd_Reverse = models.CharField(max_length=40, verbose_name='Reverse Pull Up /Cadillac', blank=True, null=True)
    Cd_Squat = models.CharField(max_length=40, verbose_name='Squat Cadillac Series', blank=True, null=True)
    Cd_Butterfly = models.CharField(max_length=40, verbose_name='Butterfly', blank=True, null=True)
    Cd_Sd_Lift = models.CharField(max_length=40, verbose_name='Side Lift', blank=True, null=True)
    Cd_Sd_Leg = models.CharField(max_length=40, verbose_name='Side Leg Lift', blank=True, null=True)
    Cd_Sd_Rich = models.CharField(max_length=40, verbose_name='Side Rich', blank=True, null=True)
    Cd_Pr1 = models.CharField(max_length=40, verbose_name='Prone 1', blank=True, null=True)
    Cd_Pr2 = models.CharField(max_length=40, verbose_name='Prone 2', blank=True, null=True)
    Cd_Hanging = models.CharField(max_length=40, verbose_name='Hanging Back', blank=True, null=True)
    # WUNDA
    Wnd_VPosition = models.CharField(max_length=40, verbose_name='V Position Toes', blank=True, null=True)
    Wnd_Wide = models.CharField(max_length=40, verbose_name='Wide V Position Heels and Toes', blank=True, null=True)
    Wnd_Sng_Leg = models.CharField(max_length=40, verbose_name='Single Leg Heels and Toes', blank=True, null=True)
    Wnd_Std = models.CharField(max_length=40, verbose_name='Standing Pike', blank=True, null=True)
    Wnd_Cat = models.CharField(max_length=40, verbose_name='Cat Stretch', blank=True, null=True)
    Wnd_Full = models.CharField(max_length=40, verbose_name='Full Pike', blank=True, null=True)
    Wnd_Torso = models.CharField(max_length=40, verbose_name='Torso Press Sit', blank=True, null=True)
    Wnd_St_Triceps = models.CharField(max_length=40, verbose_name='Seated Triceps', blank=True, null=True)
    Wnd_Prone = models.CharField(max_length=40, verbose_name='Prone Triceps', blank=True, null=True)
    Wnd_Backward = models.CharField(max_length=40, verbose_name='Backward Dips', blank=True, null=True)
    Wnd_Side = models.CharField(max_length=40, verbose_name='Side over', blank=True, null=True)
    Wnd_Bridge = models.CharField(max_length=40, verbose_name='Bridge – Wunda Chair', blank=True, null=True)
    Wnd_Hamstring = models.CharField(max_length=40, verbose_name='Hamstring Curl', blank=True, null=True)
    Wnd_Leg = models.CharField(max_length=40, verbose_name='Leg Press Standing', blank=True, null=True)
    Wnd_Forward = models.CharField(max_length=40, verbose_name='Forward Lunge', blank=True, null=True)
    Wnd_Basic = models.CharField(max_length=40, verbose_name='Basic Swan', blank=True, null=True)
    Wnd_Horseback = models.CharField(max_length=40, verbose_name='Horseback', blank=True, null=True)
    Wnd_Tendon = models.CharField(max_length=40, verbose_name='Tendon Stretch', blank=True, null=True)
    # BARREL
    Br_Hamstring = models.CharField(max_length=40, verbose_name='Hamstring Stretch', blank=True, null=True)
    Br_Gluteal = models.CharField(max_length=40, verbose_name='Gluteal Stretch', blank=True, null=True)
    Br_Adductor = models.CharField(max_length=40, verbose_name='Adductor Stretch', blank=True, null=True)
    Br_Side = models.CharField(max_length=40, verbose_name='Side over', blank=True, null=True)
    Br_Back = models.CharField(max_length=40, verbose_name='Back Extension', blank=True, null=True)
    Br_Swan = models.CharField(max_length=40, verbose_name='Swan', blank=True, null=True)
    Br_Reach = models.CharField(max_length=40, verbose_name='Reach', blank=True, null=True)
    Br_Overhead = models.CharField(max_length=40, verbose_name='Overhead Stretch', blank=True, null=True)
    Br_Chest = models.CharField(max_length=40, verbose_name='Chest Lif', blank=True, null=True)
    Br_Opening = models.CharField(max_length=40, verbose_name='Opening', blank=True, null=True)
    Br_Scissors = models.CharField(max_length=40, verbose_name='Scissors', blank=True, null=True)
    Br_Helicopter = models.CharField(max_length=40, verbose_name='Helicopter', blank=True, null=True)
    Br_Bicycle = models.CharField(max_length=40, verbose_name='Bicycle', blank=True, null=True)
    Br_Roll = models.CharField(max_length=40, verbose_name='Roll over', blank=True, null=True)
    Br_Teaser = models.CharField(max_length=40, verbose_name='Teaser Prep', blank=True, null=True)
    Br_Horseback = models.CharField(max_length=40, verbose_name='Horseback', blank=True, null=True)

    class Meta:
        verbose_name = 'Personal Training'
        verbose_name_plural = 'Personal Training'


class personalTrainingInput4(models.Model):
    # MAGIC
    Mg_Arm_Bent = models.CharField(max_length=40, verbose_name='Arms Bent', blank=True, null=True)
    Mg_Arm_Overhead = models.CharField(max_length=40, verbose_name='Arms Overhead ', blank=True, null=True)
    Mg_Rl_up = models.CharField(max_length=40, verbose_name='Roll-up w/Circle', blank=True, null=True)
    Mg_Rl_over = models.CharField(max_length=40, verbose_name='Roll-over w/Circle', blank=True, null=True)
    Mg_Sp_Double = models.CharField(max_length=50, verbose_name='Supine Double Straight Leg Stretch w/Circle',
                                    blank=True, null=True)
    Mg_Sp_Crisscross = models.CharField(max_length=40, verbose_name='Supine Crisscross w/Circle', blank=True, null=True)
    Mg_Sp_Teaser = models.CharField(max_length=40, verbose_name='Supine Teaser Variations w/Circle', blank=True,
                                    null=True)
    Mg_Sp_Knee = models.CharField(max_length=40, verbose_name='Supine Knee Squeeze', blank=True, null=True)
    Mg_Sp_Ankle = models.CharField(max_length=40, verbose_name='Supine Ankle Squeeze', blank=True, null=True)
    Mg_Prn_Bent = models.CharField(max_length=40, verbose_name='Prone Knee Bent Press w/Circle', blank=True, null=True)
    Mg_Prn_Straight = models.CharField(max_length=40, verbose_name='Prone Knee Straight Squeeze', blank=True, null=True)
    Mg_Prn_Hamstring = models.CharField(max_length=40, verbose_name='Prone Hamstring Squeeze', blank=True, null=True)
    Mg_St_Adductor = models.CharField(max_length=40, verbose_name='Seated Knee Adductor Squeeze', blank=True, null=True)
    Mg_Sd_down = models.CharField(max_length=40, verbose_name='Side Lying Top Leg Press-down w/Circle', blank=True,
                                  null=True)
    Mg_Sd_up = models.CharField(max_length=40, verbose_name='Side Lying Top Leg Press-up w/Circle', blank=True,
                                null=True)
    Mg_Sd_Tap = models.CharField(max_length=40, verbose_name='Side Lying Top Leg Tap w/Circle', blank=True, null=True)
    # STABILITY
    Stbt_Crunch = models.CharField(max_length=40, verbose_name='Crunch- Side Crunch w/Exercise Ball', blank=True,
                                   null=True)
    Stbt_Ball = models.CharField(max_length=40, verbose_name='Ball Pass', blank=True, null=True)
    Stbt_Push = models.CharField(max_length=40, verbose_name='Push Up w/Exercise Ball Toe Tuck', blank=True, null=True)
    Stbt_Brd_Series = models.CharField(max_length=40, verbose_name='Bridge Series Swiss Ball', blank=True, null=True)
    Stbt_Brd_Curl = models.CharField(max_length=40, verbose_name='Bridge Curl', blank=True, null=True)
    Stbt_Single = models.CharField(max_length=40, verbose_name='Single Leg Bridge Curl on Exercise Ball', blank=True,
                                   null=True)
    Stbt_Scorpion = models.CharField(max_length=40, verbose_name='The Scorpion', blank=True, null=True)
    Stbt_Back = models.CharField(max_length=40, verbose_name='Back Extension on Exercise Ball', blank=True, null=True)
    Stbt_Bird = models.CharField(max_length=40, verbose_name='Bird Dog on Exercise Ball', blank=True, null=True)
    Stbt_Spine = models.CharField(max_length=40, verbose_name='Spine Stretch', blank=True, null=True)
    Stbt_Stability = models.CharField(max_length=40, verbose_name='Stability Ball Wall Squats', blank=True, null=True)
    Stbt_Lunge = models.CharField(max_length=40, verbose_name='Lunge Using a Stability', blank=True, null=True)
    Stbt_Sws_Reverse = models.CharField(max_length=40, verbose_name='Swiss Ball Reverse Lunge', blank=True, null=True)
    Stbt_Sws_Anterior = models.CharField(max_length=50, verbose_name='Swiss Ball Anterior-Posterior Pelvic Tilts',
                                         blank=True, null=True)
    Stbt_Sws_Mermaid = models.CharField(max_length=40, verbose_name='Swiss Ball Mermaid', blank=True, null=True)
    Stbt_Mermaid = models.CharField(max_length=40, verbose_name='Strong Mermaid', blank=True, null=True)
    Stbt_Thoracic = models.CharField(max_length=40, verbose_name='Thoracic spine Stretch', blank=True, null=True)
    Stbt_stretch = models.CharField(max_length=40, verbose_name='Back stretch swiss ball', blank=True, null=True)
    Stbt_Brd_Dog = models.CharField(max_length=40, verbose_name='Bird –Dog w/Swiss Ball', blank=True, null=True)
    Stbt_Dead = models.CharField(max_length=40, verbose_name='Dead Bag w/Swiss Ball', blank=True, null=True)
    Stbt_Swiss = models.CharField(max_length=40, verbose_name='Swiss Ball Planks', blank=True, null=True)
    Stbt_Low = models.CharField(max_length=40, verbose_name='Low Back Stretch Swiss Ball', blank=True, null=True)
    Stbt_Bench = models.CharField(max_length=40, verbose_name='Bench Fly-Bench Press Swiss Bal', blank=True, null=True)
    # MINIBALL
    Mnb_Footwork = models.CharField(max_length=40, verbose_name='Footwork on Ball', blank=True, null=True)
    Mnb_Inc_Variations = models.CharField(max_length=40, verbose_name='Incline Leg-Drop Variations', blank=True,
                                          null=True)
    Mnb_Inc_Continued = models.CharField(max_length=40, verbose_name='Incline Leg Drop-Continued', blank=True,
                                         null=True)
    Mnb_High = models.CharField(max_length=40, verbose_name='High ‘c’ Curve Mini Ball', blank=True, null=True)
    Mnb_Lw_Mini = models.CharField(max_length=40, verbose_name='Low ‘c’ Curve Mini Ball', blank=True, null=True)
    Mnb_Lw_Oblique = models.CharField(max_length=40, verbose_name='Low ‘c’ Curve - Oblique Crunches', blank=True,
                                      null=True)
    Mnb_Coordination = models.CharField(max_length=40, verbose_name='Coordination with Ball', blank=True, null=True)
    Mnb_Mn_Ball = models.CharField(max_length=40, verbose_name='Mini Ball Pass', blank=True, null=True)
    Mnb_Plank = models.CharField(max_length=40, verbose_name='Plank Plus Mini V', blank=True, null=True)
    Mnb_Sd_Plank = models.CharField(max_length=40, verbose_name='Side Plank Mini Ball', blank=True, null=True)
    Mnb_Oblq_Crunches = models.CharField(max_length=40, verbose_name='Oblique Side Crunches', blank=True, null=True)
    Mnb_Oblq_Inner = models.CharField(max_length=40, verbose_name='Oblique & Inner Thight Squeezes', blank=True,
                                      null=True)
    Mnb_Sd_Crunch = models.CharField(max_length=40, verbose_name='Side Crunch /Inner Thight Burner', blank=True,
                                     null=True)
    Mnb_Mr_Ball = models.CharField(max_length=40, verbose_name='Mermaid with Ball', blank=True, null=True)
    Mnb_Mr_Twist = models.CharField(max_length=40, verbose_name='Mermaid with Twist', blank=True, null=True)
    Mnb_Thg_Parallel = models.CharField(max_length=40, verbose_name='Thighs –Parallel Plies Mini Ball', blank=True,
                                        null=True)
    Mnb_Thg_Dancing = models.CharField(max_length=40, verbose_name='Thighs-Thigh Dancing', blank=True, null=True)
    Mnb_Thg_Lunges = models.CharField(max_length=40, verbose_name='Thighs- Lunges', blank=True, null=True)
    Mnb_Donkey = models.CharField(max_length=40, verbose_name='Donkey Kicks & Hamstring Curl Mini Ball', blank=True,
                                  null=True)
    Mnb_In_Booty = models.CharField(max_length=40, verbose_name='Inner Thigh Booty Bridge-Pulses', blank=True,
                                    null=True)
    Mnb_In_Leg = models.CharField(max_length=40, verbose_name='Inner Thigh –Leg Circles', blank=True, null=True)
    Mnb_Lg_Lifts = models.CharField(max_length=40, verbose_name='Leg Lifts', blank=True, null=True)
    Mnb_Toe = models.CharField(max_length=40, verbose_name='Toe Taps', blank=True, null=True)
    Mnb_Frog = models.CharField(max_length=40, verbose_name='Frog Leg Press', blank=True, null=True)
    Mnb_Single = models.CharField(max_length=60, verbose_name='Single Leg Booty Bridge –Pulses (Ball Stabilization)',
                                  blank=True, null=True)
    Mnb_Booty = models.CharField(max_length=40, verbose_name='Booty Bridge –Pulses', blank=True, null=True)
    Mnb_Squats = models.CharField(max_length=40, verbose_name='Squats –Pulses', blank=True, null=True)
    Mnb_St_Pretzel = models.CharField(max_length=40, verbose_name='Seated Pretzel (Glutes) –Mini Bal', blank=True,
                                      null=True)
    Mnb_Ball = models.CharField(max_length=40, verbose_name='Ball Push Up- Arms', blank=True, null=True)
    Mnb_Chest = models.CharField(max_length=40, verbose_name='Chest Squeezes Arms-Mini Ball', blank=True, null=True)
    Mnb_Rl_Over = models.CharField(max_length=40, verbose_name='Roll Over Ball', blank=True, null=True)
    Mnb_Rl_Back = models.CharField(max_length=40, verbose_name='Roll Back and Up', blank=True, null=True)
    Mnb_Bck_Extension = models.CharField(max_length=40, verbose_name='Back Extension Ball', blank=True, null=True)
    Mnb_Extension = models.CharField(max_length=40, verbose_name='Swan on Ball', blank=True, null=True)

    class Meta:
        verbose_name = 'Personal Training'
        verbose_name_plural = 'Personal Training'


class personalTrainingInput1(models.Model):
    trainer = models.ForeignKey(to=Trainer, verbose_name="Antrenör", on_delete=models.CASCADE, blank=True, null=True)
    personal = models.ForeignKey(to=Personal, verbose_name="Danışan", on_delete=models.CASCADE, blank=True, null=True)
    training2 = models.ForeignKey(to=personalTrainingInput2, verbose_name="Danışan", on_delete=models.CASCADE, blank=True, null=True)
    training3 = models.ForeignKey(to=personalTrainingInput3, verbose_name="Danışan", on_delete=models.CASCADE, blank=True, null=True)
    training4 = models.ForeignKey(to=personalTrainingInput4, verbose_name="Danışan", on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateField(("Date"), default=datetime.now(), blank=True)
    # Amaç Belirle
    health1 = models.CharField(max_length=50, verbose_name='Genel Sağlık Gelişimi', blank=True, null=True)
    force = models.CharField(max_length=50, verbose_name='Genel Kuvvet Gelişimi', blank=True, null=True)
    muscular_endurance = models.CharField(max_length=50, verbose_name='Kas Dayanıklılık Gelişimi', blank=True,
                                          null=True)
    muscle_mass = models.CharField(max_length=50, verbose_name='Kas Kütlesi Artışı', blank=True, null=True)
    mekanik = models.CharField(max_length=50, verbose_name='Mekanik Ağrıların Önlenmesi', blank=True, null=True)
    fonksiyonel = models.CharField(max_length=50, verbose_name='Fonksiyonellik Kazanımı', blank=True, null=True)
    # Gün sayısı
    monday = models.CharField(max_length=50, verbose_name='Pazartesi', blank=True, null=True)
    tuesday = models.CharField(max_length=50, verbose_name='Salı', blank=True, null=True)
    wednesday = models.CharField(max_length=50, verbose_name='Çarşamba', blank=True, null=True)
    thursday = models.CharField(max_length=50, verbose_name='Perşembe', blank=True, null=True)
    friday = models.CharField(max_length=50, verbose_name='Cuma', blank=True, null=True)
    saturday = models.CharField(max_length=50, verbose_name='Cumartesi', blank=True, null=True)
    sunday = models.CharField(max_length=50, verbose_name='Pazar', blank=True, null=True)
    train_time = models.CharField(max_length=20, verbose_name="Antrenman Süresi Belirle", blank=True, null=True)
    # Set Sayısı & Tekrar Sayısı
    set_number = models.CharField(max_length=5, verbose_name="Set Sayısı", blank=True, null=True)
    over_number = models.CharField(max_length=5, verbose_name="Tekrar Sayısı", blank=True, null=True)
    # Setler arası dinlenme
    sets_between = models.CharField(max_length=10, verbose_name="Setler Arası Dinlenme", blank=True, null=True)
    move_between = models.CharField(max_length=10, verbose_name="Hareketler Arası Dinlenme", blank=True,
                                    null=True)
    # RESPIRATORY
    Rs_Rs_Diaphragm = models.CharField(max_length=50, verbose_name='Diaphragm Breating', blank=True, null=True)
    Rs_Stability = models.CharField(max_length=50, verbose_name='Stability and Control Breath', blank=True, null=True)
    Rs_Lateral = models.CharField(max_length=50, verbose_name='Lateral Breath', blank=True, null=True)
    Rs_Crocodile = models.CharField(max_length=50, verbose_name='Crocodile Breathing', blank=True, null=True)
    Rs_Breath = models.CharField(max_length=50, verbose_name='90-90 Nefes Tekniği (Soft Ball-Kettlebell)', blank=True,
                                 null=True)
    Rs_Ballon = models.CharField(max_length=50, verbose_name='Ballon Breaths', blank=True, null=True)
    Rs_Br_Exercise = models.CharField(max_length=50, verbose_name='4-7-8 Breathing Exercise', blank=True, null=True)
    Rs_Notr = models.CharField(max_length=50, verbose_name='Nötr Nefes (Neutral Breath)', blank=True, null=True)
    Rs_Steps = models.CharField(max_length=50, verbose_name='Steps & Benefits (Kapalabhati)-Ateş Nefesi', blank=True,
                                null=True)
    Rs_Bastrika = models.CharField(max_length=50, verbose_name='Körük Nefesi (Bastrika)', blank=True, null=True)
    Rs_Nadishadlana = models.CharField(max_length=50, verbose_name='Dönüşümlü Burun Nefesi (Nadishadlana)',
                                       blank=True, null=True)
    Rs_Suryonulama = models.CharField(max_length=50, verbose_name='Sağ Burun Deliği Nefesi (Suryonulama Vilama)',
                                      blank=True, null=True)
    Rs_Chandronulama = models.CharField(max_length=50, verbose_name='Sol Burun Deliği Nefesi (Chandronulama Vilama)',
                                        blank=True, null=True)
    Rs_Suryabhadana = models.CharField(max_length=50, verbose_name='Tek Burun Deliği Nefesi (Suryabhadana)',
                                       blank=True, null=True)
    Rs_Ujjoyi = models.CharField(max_length=50, verbose_name='Okyanus Nefesi (Ujjoyi)', blank=True, null=True)
    Rs_Bhromeri = models.CharField(max_length=50, verbose_name='Arı Nefesi (Bhromeri)', blank=True, null=True)
    Rs_Anoluma = models.CharField(max_length=50, verbose_name='4-8 Burun Nefesi (Anoluma Viloma)', blank=True,
                                  null=True)
    Rs_Kumbhaka = models.CharField(max_length=50, verbose_name='4-4-8 Burun Nefesi (Kumbhaka)', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('corrective-exercise-detail', kwargs={'id': self.id})

    def get_update_url(self):
        return reverse('corrective-exercise-update', kwargs={'id': self.id})

    def get_trainer_pilates_delete_url(self):
        return reverse('trainer-pilates-delete', kwargs={'id': self.id})

    def get_corporate_pilates_delete_url(self):
        return reverse('corporate-pilates-delete', kwargs={'id': self.id})

    def get_personal_pilates_delete_url(self):
        return reverse('personal-pilates-delete', kwargs={'id': self.id})

    class Meta:
        verbose_name = 'Personal Training'
        verbose_name_plural = 'Personal Training'
